views/js/ui/incrementer.js

debounce the keyup callback to give user a chance to rectify an invalid input + allow negative value input

debounce the keyup callback to give user a chance to rectify

---

helpers/class.Export.php

Before sending archive to the end user should be cleaned all levels of output buffering. Otherwise user may get corrupted file.

TAO-435: QTI Item with PCI cannot export

---

views/js/test/util/url/test.js
views/js/util/url.js

Add new features to the URL util.
Also parsedUrl object's have now the toString method on their prototype so it can be used in strings

url util isRelative/Absolute and toString for parsed URL

---

views/js/ui/ckeditor/ckConfigurator.js

FIxed the issue #3 listed in https://oat-sa.atlassian.net/browse/TAO-726
> The buttons for "Insert math Expression", "Insert Shared Stimulus" and "Insert Image" display in author mode but not in preview mode.

fixed badly scoped positionedPlugins var

---

views/scss/inc/_autocomplete.scss

Set the cursor style when mouse is over autocomplete suggestions.
Prevent text selection within suggestions
To test the component, use the tao-dac-simple extension (requires https://github.com/oat-sa/extension-tao-dac-simple/pull/15)

Autocomplete: set the cursor style for suggestions, and avoid text selection

---

views/js/controller/login.js

Login input filed has `autofocus` attribute ([class.Login.php](https://github.com/oat-sa/tao-core/blob/master/actions/form/class.Login.php#L80)) so this method is redundant.

remove JS autofocus

---

views/js/iframeResizer.js
views/js/jquery.sizechange.js

This pull request fix the iframeResizer that was falling back into set interval instead of using the Mutation Observers.
To test it you can profile the browser during a delivery before and after applying the PR.

fix delivery performances

---

views/build/config/phantomjs-bridge.js
views/build/grunt/test.js

This task enables you to run a single unit test from the command line (useful to test directly on PhantomJS)  using for example : 
```
grunt connect qunit:single --test /taoQtiItem/views/js/test/runner/provider/test.html
```

enable to run a single test on phantomJs using grunt

---

views/js/lib/simulator/jquery.keystroker.js

Wrong argument given when mocking keyboard events for control keys

Fix the autocomplete unit test: wrong arguments for event mocks

---

views/js/ui/autocomplete.js

As discussed with @jbout the search queries must not be automatically altered with a wildward. This to allow a default behavior without interferences.
Now the wildcard char is not added by default to the query. An option allows to add it (`addWildcard`).

Add wildcard to query only is asked

---

views/js/serviceApi/StateStorage.js

This patch avoid the test runner to send several requests to store the same state each time an item is validated.

Keep the set state to avoid multi ajax calls

---

views/js/i18n.js

When a translation contains parameters, the `translate`method was using the source as a translation instead of the localized version...

Wrong translation when the key contains parameters

---

actions/class.Main.php

This fix removes the display issue that is shown with accented characters when warning about access denied.
Before: `"Acc&egrave;s refus&eacute;. Veuillez renouveler votre authentification !"`
After: `"Accès refusé. Veuillez renouveler votre authentification !"`
I don't know if such change couldn't led to a security issue.

Remove problematic htmlentities function for accented characters

---

views/js/test/ui/dialog/test.js
views/js/ui/dialog.js

Add full destroy to dialog box
Display immediately the dialog box by default (animate option)
Requires: https://github.com/oat-sa/tao-core/pull/492

Add full destroy to dialog box

---

views/js/ui/modal.js

The close and open actions were not called when animate is enabled and the modal is hidden.
Now, when the modal is hidden, the animate is not used.

Fix modal animate callback when not visible

---

views/scss/inc/_functions.scss

Related to https://oat-sa.atlassian.net/browse/TAO-1243 and https://github.com/oat-sa/extension-tao-testqti/pull/195
This fix allow use list of color with positions.
In past: 
```sass
@include linear-gradient((color1, color2, color3)) // generates gradient with 33,333% per color
```
Now you can define color and position:
```sass
@include linear-gradient((color1 0px, color2 30px, color3 50px))
```

Improved linear-gradient mixin

---

views/js/main.js

Enables you to start the js router using the current MVC context instead of the window URL.

use the context instead of the window url

---

views/templates/client_config.tpl

It makes client side templates to load even in a Cross Origin context
(Cherry pick from https://github.com/oat-sa/tao-core/pull/565)

configure the text plugin to use always xhr

---

doc/structures.dtd

Init event has been added earlier:
https://github.com/oat-sa/tao-core/blob/develop/views/js/layout/tree.js#L261
but I forgot add init attribute to the `structures.dtd` file

Add init attribute to the structures.dtd

---

helpers/dateFormatter/EuropeanFormatter.php
test/helpers/DateHelperTest.php

remove milliseconds from ISO 8601 format

---

models/classes/controllerMap/Factory.php
models/classes/routing/Resolver.php

Possibility to define complex routes, not restricted by extension name schema, requires performance validation

Allow routes outside of extension names

---

views/js/test/ui/breadcrumbs/test.js
views/js/test/ui/component/test.js
views/js/test/ui/listbox/test.js
views/js/ui/breadcrumbs.js
views/js/ui/component.js
views/js/ui/listbox.js

changes : 
- `getContainer` returns the component container (= renderTo) 
- `getElement` (previously `getContainer`) returns the component element
- `render` chains to the API and does not return the container anymore
- events can only be attached using the eventifier API  (`on`) and there is no   `config.onSomething` anymore
- events doesn't use the context in arguments as the eventifier delegates already the context on this.

minor components API refactoring and simplifications

---

views/js/ui/resourcemgr/fileSelector.js

Under certain circumstances that are difficult to replicate a browser may report the mime type in quotes (e.g. "application/foo" instead of application/foo). This fix removes possibly existing surrounding quotes before checking against the filter list to avoid false positives.

Remove mime quotes

---

views/js/layout/tree.js

I cannot reproduce it on my local installation of TAO but i figured out the problem.
Sometimes after click "Open" button request to the /taoItems/Items/editItem executed twice (first with current selected item id and second with item id which should be opened).
You can check it by following steps:
- create folder and item in this folder
- select any item in the root folder
- refresh the page (created folder should be closed)
- input in the search field name of the created item
- click the "Open" button
You will see that editItem request will be executed twice. If first request will finished after the second then previously selected item will be selected on the tree (as described in the issue).

deselect tree node before refresh

---

views/js/test/ui/datatable/test.js
views/js/ui/datatable.js

When the datatable plugin is re-applied, the new config is merged, and the provided dataset is also taken into account.
The refresh method can be called with immediate dataset to prevent new query.

datatable: update options on reinit, accept predefined data on refresh

---

models/classes/requiredAction/RequiredActionAbstract.php
models/classes/requiredAction/RequiredActionInterface.php
models/classes/requiredAction/RequiredActionRuleInterface.php
models/classes/requiredAction/implementation/RequiredActionRedirect.php
models/classes/requiredAction/implementation/TimeRule.php

I have implemented `__toPhpCode()` method for action and rule classes but `TimeRule::__construct` waits to get `DateInterval` and `DateTime` instances. Obviously these objects has no `__toPhpCode()` method so i just serialized it.
So, config looks like this:
```php
return new oat\tao\model\requiredAction\implementation\RequiredActionService(array(
'required_actions' => array(
new oat\tao\model\requiredAction\implementation\RequiredActionRedirect(
'codeOfConduct',
array(
new oat\taoAct\model\requiredAction\implementation\CodeOfConductRule(
unserialize('O:12:"DateInterval":15:{s:1:"y";i:1;s:1:"m";i:0;s:1:"d";i:0;s:1:"h";i:0;s:1:"i";i:0;s:1:"s";i:0;s:7:"weekday";i:0;s:16:"weekday_behavior";i:0;s:17:"first_last_day_of";i:0;s:6:"invert";i:0;s:4:"days";b:0;s:12:"special_type";i:0;s:14:"special_a …
```

Implement PhpSerializable interface

---

views/js/ui/uploader/uploader.tpl

Without `type="button"` attribute this button treats as submit button and triggers reset form on press Enter key.
See https://oat-sa.atlassian.net/browse/TAO-2070

TAO-2070 Add button type

---

views/js/core/timer.js
views/js/test/core/timer/test.js

The test got some changes, especially removing 1ms to the delay comparison because of the `setTimeout` accuracy that needs to be compensated ( a 10th of the test run was failing because of comparisons likes `199.9735 >= 200` ), but this is my first approach without being deeper in the details.

tick stops on pause, return nothing if not running

---

views/js/form/post-render-props.js
views/js/test/form/post-render-prop/test.html
views/js/test/form/post-render-prop/test.js

this was not a bug, as the "expected behaviour" wasn't implemented on purpose.
However, I think this is misleading having a button with no behaviour implemented, so I decided to hide it when in advanced mode.

hide search icon when advanced mode is active for custom properties

---

views/build/grunt/test.js

It was difficult to figure which test was failing in the reports. You can test the difference using :
```sh
grunt connect qunit_junit qunit:single --test=/tao/views/js/test/core/timer/test.html
```
and then check the file `reports/TEST-tao.views.js.test.core.timer.xml`

fix test names in the build report

---

views/js/ui/uploader.js

I was not able to reproduce the drag 'n drop issue, but while debugging, sometime the `dataTransfer`  from 'e.originalEvent` is null and then an error is thrown.
This is only a safety fix.
Test in different browsers if you can:
- import a test or an item using drag and drop.
- download one or multiple images from the item creator

better support of dropped files

---

views/build/grunt/s3.js

20 concurrent connections by default
You can also change the concurrency using a the flag `--s3-concurrency` :
```sh 
grunt awss3:upload --s3-concurrency=50
```

enable to change the s3 upload concurrency

---

views/js/ui/datatable.js

Issue: When a user is navigating a list of data and is on a page after the first, and then does a filter which results in only one page, then the user is not brought back to the first page.
This PR fix described issue.

Add reset to first page when filtering was used

---

views/js/core/plugin.js
views/js/core/pluginLoader.js
views/js/core/pluginifier.js
views/js/test/core/plugin/test.html
views/js/test/core/plugin/test.js
views/js/test/core/pluginLoader/mockPlugin.js
views/js/test/core/pluginLoader/test.html
views/js/test/core/pluginLoader/test.js

I've moved the plugin factory from taoTests to tao in order to use it in the item creator.
All references to the test runner should have been removed.
The plugins have now an access to it's "host" using the `getHost` method. For convenience it's possible to alias this method if the `hostName` is provided in the config.

Move the plugin model and pluginLoader to core

---

views/js/core/store.js
views/js/layout/tree.js
views/js/test/core/store/store/test.html
views/js/test/core/store/store/test.js

- indexdb support detection is async (open on error) so retrieving the store is
- prevent the invalidStateError to appear
- better fallback
Easiest way to reproduce is using FF in private browsing mode (beause `window.indexdb` is available but it fails while opening a db, see https://bugzilla.mozilla.org/show_bug.cgi?id=781982)

better backend detection, store returns a promise

---

views/js/ui/mediasizer.js

In the Item Creator, include an image, switch from responsive to normal mode.
This fix just prevent the error, but the mediasizer still doesn't work in normal mode.
The test is useless and should be rewritten. 
The file was wrongly encoded,  but the real change is made here (`this` to `self`) https://github.com/oat-sa/tao-core/compare/develop...fix/error-mediasizer-mode?expand=1#diff-c44a232380cb3c35bcfd1d7059f8eb3bR431

fix the TypeError

---

views/templates/layout.tpl

Prevent loading the file `taoItems/views/css/preview.css` on every page (yes, I know). 
See https://github.com/oat-sa/tao-core/compare/develop...fix/remove-preview-css?expand=1#diff-d9fd2dde1e713a8d3c14c24e45685535L28
The whole file seems to be be wrongly encoded, so it has been re-encoded on to `utf-8[unix]`.
Requires https://github.com/oat-sa/extension-tao-item/pull/214
Related to https://oat-sa.atlassian.net/browse/TAO-1439

remove preview.css from every page

---

views/build/package.json

I've updated the dependency to grunt (to grunt 1.0.0) and most of the grunt plugins. 
On my computer it reduces the compilation time from 27min to 3min.
Even if the requirejs, uglify and sass version are backward compatible this could have an impact everywhere.
Please reinstall the dependencies, compile all full build (`npm run build`) and test the platform in production mode (a configuration with the new TR for example because it involves a lot compiled bundles).
It requires https://github.com/oat-sa/extension-tao-delivery/pull/174 because the new version of `grunt-contrib-sass` is more strict and fails when a file does not exists.
Because this is a more or less risky PR, don't hesitate to involve the test team.

update grunt and plugins

---

actions/class.Users.php

Security testers found that they can change super user data by removing "disabled" attribute from button here:
I have added checking of user uri on server side.

Check user uri before editing

---

helpers/form/elements/xhtml/class.Treeview.php
manifest.php
scripts/update/Updater.php

Without this patch, it is impossible to remove all the selected elements of a Treeview widget. You can check that by installing taoClientRestrict. Without this patch, it's impossible to unslect all the browsers/os previously checked.

TAO-2811 Now you can deselect all values from a treeview.

---

manifest.php
scripts/update/Updater.php
views/js/ui/listbox.js

The `ui/component` component has been recently upgraded with a size handling. Unfortunately, the `ui/listbox` component has its own size handling, using CSS flex box. Obviously this is not compatible with pixels sizing. To fix the issue a remaping is done to prevent the new default component bahavior.

Fix the listbox width handling

---

views/js/core/customEvent.js

Prevent this error to occur under Internet Explorer when triggering a custom event: `"Object doesn't support this action"`.

Fix the CustomEvent emitter under IE

---

manifest.php
scripts/update/Updater.php
views/js/helpers.js
views/js/test/util/url/test.html
views/js/test/util/url/test.js
views/js/util/url.js

It's time to deprecate `helpers#_url` and move it into it's obvious location : `util/url#route`
The file `helpers` looks changed because I've converted the encoding but I've only added the `use strict` statement and the `@deprecated`tags.

from helpers#_url to util/url#route

---

helpers/form/data/class.UploadFileDescription.php
helpers/form/elements/xhtml/class.GenerisAsyncFile.php
manifest.php
models/classes/dataBinding/class.GenerisFormDataBinder.php
scripts/update/Updater.php

There should be a field in the POST data with the name of a resource as key and `{ action: delete }` as value
PR handles front-end only, server has not been implemented!

TAO-3167 now tells the server how to handle a file operation

---

views/build/Gruntfile.js
views/build/grunt/sass.js
views/build/grunt/test.js

1. Grunt merge style refactoring
2. Use a configurable `testUrl` : `grunt connect:test:keepalive --testUrl=0.0.0.0 --testPort=1234`
3. Enable livereload on test server, triggered by watch:
- `grunt connect:dev watch:taosass`
- Then open a test, for example http://127.0.0.1:8082/tao/views/js/test/ui/tooltip/test.html 
- Modify a SCSS file
- The test will reload automatically once the CSS compilation is done

livereload, config.merge & testUrl options

---

manifest.php
scripts/update/Updater.php
views/build/grunt/lint.js

Ignore the PCI and PIC runtimes from ESLint, since the code is considererd as content and might include external libraries we exclude it from the source code analysis.
To test please compare
```
cd tao/views/build
npm run lint -- --extension=qtiItemPci
```
the report will be in  `views/build/reports/qtiItemPci-checkstyle.xml`

ignore PCI and PCI content from ESLint

---

views/js/test/ui/keyNavigation/test.js

PhantomJS did not support the mix of the `navigator` variable name and a missing `QUnit.start` resulting in a broken test suite while running all tests : https://jenkins.taocloud.org/job/build-tao-js/767/console

make key navigation work inside a large test suite

---

helpers/Layout.php
manifest.php
scripts/update/Updater.php

On a vanilla TAO installation
- checkout this branch
- change `/tao/includes/constants.php#49` temporarily to `define('TAO_RELEASE_STATUS', 'alpha');`
- browse the site, paying attention to the bottom/right corner
The link should no longer point to the forge but rather to the forum

fixed forum link

---

manifest.php
scripts/update/Updater.php
views/js/layout/tree/provider/jstree.js

To reproduce this issue you may select any item in tree and then call
```
$('.tree').trigger('refresh.taotree');
```
in console.
The first item will be selected and two `editItem` requests will be performed.

Tao 6029 tree node selection after refresh

---

manifest.php
scripts/update/Updater.php
views/js/test/util/locale/test.js
views/js/util/locale.js

The bug arose because we are using our own locale-specific `parseFloat` function in `util/locale.js`. 
There was an edge case which was missed: splitting a string which begins with the decimal separator -> the part before the separator will end up empty. The first part will now become 0 in this case.

Fix / TAO-6994 Cover cases like .5 float input; 2 tests for that

---

actions/class.CommonModule.php
manifest.php
scripts/update/Updater.php

Please note that this PR is directly related to https://github.com/oat-sa/extension-tao-lti/pull/155. Please make sure these PR's get merged at the same time.
Added protected method that sets headers to protect against iframe attacks. Note that this method is protected so we can override this when needed (eg. in LTI modules)
Additionally I removed some trailing whitespaces and duplicate newlines.

TAO-7151 - Add iframe attack protection headers

---

manifest.php
scripts/update/Updater.php
views/js/lib/dompurify/purify.js
views/js/test/tpl/samples/dompurify_script.tpl
views/js/test/tpl/test.js
views/js/tpl.js
views/js/ui/datatable/tpl/layout.tpl
views/js/ui/feedback/feedback.tpl
views/js/ui/report/feedback.tpl

- DOMPurify lib has been pulled to the core
- dompurify handlebars helper has been created with test
- Two issues have been fixed
**1. Message content is able to evaluate scripts currently**
1. Log in as admin
2. Create a test with "<script>alert("test label alert")</script>" as label
3. Click on Publish on the action bar
4. Select destination
5. Publish should fail
6. Alert appears before the error message
Root cause:
 tao/views/js/ui/report/feedback.tpl line 4:
` {{{message}}} `
This way we don't escape dirty html in message content.
Suggestion for fixing: 
`{{{dompurify message}}}`
Another example:
 tao/views/js/ui/feedback/feedback.tpl line 3:
`{{{dompurify msg}}}`
**2. XSS on Result page**
1. Log in as admin
2. Create a test
3. Create a …

Fix/TAO-6785 - Add dompurify and related fixes

---

manifest.php
scripts/update/Updater.php
views/js/test/util/url/test.js
views/js/util/url.js

Amend for https://github.com/oat-sa/tao-core/pull/1967/files.
Parameter order for _.forOwn function has been confused before it was merged.
https://oat-sa.atlassian.net/browse/NCSUP-182

Fix/ncsup 182/wrong parameter order in route parameter serialization

---

manifest.php
scripts/update/Updater.php
views/js/test/tpl/samples/dompurify_script.tpl
views/js/test/tpl/test.js
views/js/tpl.js

This changes will allow `data-action` attribute to stay on its place in datatables

Fix/tao 7645/fix broken by dompurify datatables

---

manifest.php
scripts/update/Updater.php
views/build/config/requirejs.build.json
views/templates/client_config.tpl

This Pull Request Follow Up https://github.com/oat-sa/extension-tao-proctoring/pull/669
It adds the dependency between `c3` and `d3` at the configuration level (`c3` always required `d3`). It looks like it was previously loaded by _chance_/_accident_...
This Pull Request is somehow linked to https://oat-sa.atlassian.net/browse/TAO-7515 (since the regression appeared after the update of `c3`)
How to test this pull request : 
1. Ensure the activity graph is still working on the proctoring
2. Run the tests : 
```
cd tao/views/build
npx grunt connect:test taoproctoringtest
```

Fix/tao 7515/implicit dependency between d3 and c3

---

manifest.php
scripts/update/Updater.php
views/templates/layout.tpl

When TAO uses another language than set in the system google chrome suggest translation the page that if applied can raise unexpected errors or understanding from users. As we have own rules about the language of the interface it makes sense to turn off this feature for the application.
Google Help says that it can be done by adding special meta tag
https://support.google.com/webmasters/answer/79812?hl=en

Turn off google page translation

---

manifest.php
scripts/update/Updater.php
views/js/test/ui/tooltip/test.js
views/js/ui/tooltip.js

**Task** https://oat-sa.atlassian.net/browse/TAO-7512
**summary** tooltips are not shown randomly after test item being saved in back-office.
**What was fixed** Investigation took a bit longer than expected, but I found out, that the problem was in tooltip factory function, which has been taking its params in form of DOM element *by link* instead of *shallow copy* of original DOM element, so there was collision when Tooltip factory function was executed several times with same params given.
+ Proper unit test checking collision was added.

Fix/tao 7512/tooltips on item authoring

---

manifest.php
scripts/update/Updater.php
views/js/test/ui/highlighter/test.js
views/js/ui/highlighter.js

Related to : https://oat-sa.atlassian.net/browse/TAO-7935
Do not discard selection on touchend during highlighting
Allow do clear highlighted node by clicking on it
Change cursor when  highlighting is activated
- Run delivery as a test taker on touchscreen device with enabled highlighting tool
- Activate highlighting tool and start selecting the text
- After triggering selection you should be allowed to resize it
- Run delivery as a test taker with enabled highlighting tool
- Highlight some text 
- After click on highlighted text it should be cleared
- Run delivery as a test taker on desktop browser with enabled highlighting tool
- After activating highlighting tool cursor above test item should be changed to marker icon
Companion PR :

[TAO-7935] WK-1281 PG - TCiaB - highlighter behavior for touchscreen

---

manifest.php
scripts/update/Updater.php
views/js/controller/settings/extensionManager.js
views/templates/extensionManager/view.tpl

Regression found in https://oat-sa.atlassian.net/browse/TAO-7149
- The dependency to `jqueryui` wasn't declared by the module itself. It was working by chance (another module had to import it previously)
- This PR brings a quick fix to use `ui/modal` instead of jqueryui's `dialog` 
How to reproduce : 
- Ensure your instance is in `DEBUG_MODE` (in `config/generis.conf.php`)
- Open the `Extension Manager` from `Settings`
- Select extensions and click the `Install` button
What's expected : 
- A modal popup is displayed, you can confirm or cancel the installation, follow up the installation progress

Replace jqueryui dialog by ui/modal in extension manager

---

actions/class.ClientConfig.php
manifest.php
models/classes/security/xsrf/TokenService.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/browse/TAO-7306
We had a bug where the token pool keys were being regenerated (by `usort`) and therefore the form token was misidentified and returned to the FE as a normal token. Which eventually caused a CSRF Exception.
This fix switches to `uasort` and also applies checks to get the correct pool size if the form token is present.
BE pool size is now 6 to match the FE (and the browser's limit on concurrent requests).
(code by @martijn-tao, commit by me)

Fix/tao 7306/pool size fixes

---

manifest.php
scripts/update/Updater.php
views/js/core/request.js

We will allow a value `noToken` to be set in the client config for the module `core/request`. This will override whatever value the module's `request()` function is called with.
The purpose is to allow tokenisation to be turned off for testing purposes.

Fix/tao 7305/module config override for noToken

---

manifest.php
scripts/update/Updater.php
views/js/test/core/communicator/poll/test.html

The polling unit test was using up its supply of provided tokens. I'm turning off the token requirement in that file, using the module config.
To test: `cd tao/views/build && npm i && npx grunt connect:dev taotest`

Fix/tao 7305/poll unit test disable token

---

models/classes/taskQueue/Queue.php
test/unit/model/security/xsrf/TokenTest.php
test/unit/model/taskQueue/QueueTest.php

- TokenTest: used a fixed value for timestamp to avoid microtime difference.
- QueueTest: used a real Queue object for testing testDequeueWhenTaskPoppedOrNot instead of a mock.

Fixed TokenTest and QueueTest.

---

locales/en-GB/lang.rdf
manifest.php
scripts/update/Updater.php

Add British english language label value
1 Go to backend office -> user settings (/tao/Main/indexstructure=user_settings&ext=tao&section=settings_my_settings) 
2 look into Interface language list.
Expected result: in this list exist option value->en-GB, label->English British
Actual result: in this list exist option value->en-GB, but with an empty label

Fix/tao 8312/add British english language label

---

install/js/step_server_setup.js
install/services/class.CheckFileSystemComponentService.php
install/tpl_step_server_setup.html
manifest.php
scripts/update/Updater.php

We move the other way around: make the "file_path" parameter optional in both CLI and web installer.
To test it, try to install without specifying a path in the last left box on the second screnn of installer (see attachment in https://oat-sa.atlassian.net/browse/TAO-8162).

file_path is now optional in web installer.

---

manifest.php
models/classes/class.LanguageService.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/projects/SI/issues/SI-362
How to check:
install tao-core with v25.1.3, go to backoffice->test takers and try to import test taker with no default lang (example nl-NL). Language of the imported tt will be default (en-EN)
It will work after the update to v25.1.4

Importing .CSV file with students gives wrong interface language

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

https://oat-sa.atlassian.net/browse/TAO-8362
This is just to ensure that v0.3.2 of tao-core-sdk (which we changed [here](https://github.com/oat-sa/tao-core-sdk-fe/pull/14)) gets deployed.

Fix/tao 8362/connectivity error format

---

manifest.php
models/classes/export/PsrResponseExporter.php
models/classes/export/implementation/AbstractFileExporter.php
models/classes/export/implementation/CsvExporter.php
scripts/update/Updater.php
test/integration/export/CsvExporterTest.php

https://oat-sa.atlassian.net/browse/TAO-8214 (fix of nccer reports is in https://github.com/oat-sa/extension-tao-nccer-delivery/pull/908)
We started to use Psr Responses instead of directly writing to the output but AbstractFileExporter and CsvExporter conflict with it producing php warnings in output.
All changes don't break compatibility with old code, but the new recommended way to download file is to call `$csvExporter->exportFileResponse()` instead of `export(..., true, ...)` (which is still works for compatibility).
Interface `PsrResponseExporter` extending `Exporter` interface added with `exportFileResponse` method. `CsvExporter` implements it, but `AbstractFileExporter` doesn't, because I didn't want to add new abstract method to `AbstractFileExporter` which is extended in many …

Fix/tao 8214/psr response exporter

---

manifest.php
scripts/update/Updater.php
views/build/grunt/test.js

During ES6 refactoring in https://github.com/oat-sa/tao-core/pull/2195/commits/83eb25dad83, `paths` became `path`. The tests won't work this way! Reverting it.
`npx grunt connect:dev taoqtiitemtest` is the way to test it.

Fix/nex 91/grunt test config paths

---

actions/class.ClientConfig.php
manifest.php
models/classes/security/xsrf/TokenService.php
scripts/update/Updater.php
test/unit/model/security/xsrf/TokenServiceTest.php
views/package-lock.json
views/package.json
views/templates/client_config.tpl

Related to: https://oat-sa.atlassian.net/browse/TAO-8631
Requires: 
During an assessment, if the test taker spends more than 24 minutes on the same item without triggering any request to the server, the following error will be raised: `No tokens available. Please refresh the page.`. This event will occur no matter the duration of the server session.
The reason why is the anti-CSRF protection hardcodes the TTL of the token to 24 minutes, on the frontend side, no matter what is set on the platform.
To fix this wrong behavior, we need to address the issue on both sides:
- the frontend should take care of the platform configuration
- the backend should provide the plartform configuration to the frontend
The companion PR aims to address the frontend issue.
This PR rework the way the config is …

Fix/tao 8631/sync csrf token config

---

composer.json
manifest.php
models/classes/mvc/Bootstrap.php
scripts/update/Updater.php

Reads variables from .env file in project dir if it is provided. If no `.env` file is provided, just does nothing.
This allows us to then access variables values in `$_ENV` global array.
Works for CLI, Apache, Nginx, ...
Example:
.env file:
```
GENERIS_CACHE_URI=http://my-redis.com/blah/blah/blah
```
.php file:
```
echo $_ENV['GENERIS_CACHE_URI']; // => http://my-redis.com/blah/blah/blah
```

Read variables from .env file in project dir if it is provided.

---

models/classes/mvc/Bootstrap.php

Based on Jonathan's comment (https://github.com/oat-sa/tao-core/pull/2233#discussion_r309123955), this amends the directory separator problem by using a global constant.

Used ROOT_PATH to locate the .env file.

---

config/default/webhookEventLog.conf.php
config/default/webhookLogRepository.conf.php
manifest.php
models/classes/webhooks/log/WebhookEventLogInterface.php
models/classes/webhooks/log/WebhookEventLogRecord.php
models/classes/webhooks/log/WebhookLogRepository.php
models/classes/webhooks/log/WebhookLogRepositoryInterface.php
models/classes/webhooks/log/WebhookRdsEventLogService.php
models/classes/webhooks/task/WebhookTaskContext.php
scripts/install/CreateWebhookEventLogTable.php
scripts/update/Updater.php

According to https://oat-sa.atlassian.net/browse/TAO-8628, 
- the `webhook_event_log` table created,
- the table is to be deployed both when installing & updating,
- the `WebhookLogRepository` introduced at the level of persistence, this is to be a persistence wrapper on top of the table while the `WebhookRdsEventLogService ` is to be a business layer.
Both services operate the `WebhookEventLogRecord` entity. `WebhookLogRepository` only cares about how to hydrate the entity and `WebhookLogRepository` can build a row according to business rules.
Tests to be added soon.

Feature/tao 8628/webhook event log

---

manifest.php
models/classes/webhooks/log/WebhookEventLogInterface.php
models/classes/webhooks/log/WebhookRdsEventLogService.php
models/classes/webhooks/task/WebhookTask.php
models/classes/webhooks/task/WebhookTaskContext.php
models/classes/webhooks/task/WebhookTaskReports.php
scripts/update/Updater.php
test/unit/webhooks/task/WebhookTaskReportsTest.php
test/unit/webhooks/task/WebhookTaskTest.php

https://oat-sa.atlassian.net/browse/TAO-9282
During testing of salesforce authorization I noticed our log messages not always informative enough.
`OAuth2AuthType` for example, throws guzzle's `RequestException` which isn't properly handled in `WebhookTask`. Also it throws `common_exception_ValidationFailed` without message (while `getUserMessage()` has one)
After CodeClimate complaints (methods count exceeded) I had to split WebhooksTask class and I extracted logging and reporting logic to separate WebhookTaskReports class

Fix/tao 9282/webhook task logging

---

install/services/SetupSettingsStorage.php
manifest.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/browse/TAO-9303
reason
Default CSP_HEADER_SETTING is not provided, that's why we have an issue on the tao installation
solution
CSP_HEADER_SETTING = 'self' by default

Fix/tao 9303/default settings storage values

---

manifest.php
scripts/update/Updater.php
test/unit/model/security/xsrf/TokenStoreKeyValueTest.php
test/unit/model/security/xsrf/TokenTest.php

Related to: https://oat-sa.atlassian.net/browse/TTD-18
Depends on: https://github.com/oat-sa/generis/pull/678
All tests extends `generis\test\TestCase` instead of `\PHPUnit_Framework_TestCase`
All Mock objects instances of `generis\test\MockObject` instead of `\PHPUnit_Framework_MockObject_MockObject`. Mocks was used only in phpdoc.
Possible way to test:
1) run unit tests.
2) update code.
3) run unit tests again. result should be the same as in 1.

TTD-18 missed extending.

---

actions/class.Roles.php
manifest.php
scripts/update/Updater.php

The response missed the `success => true` parameter, which is used by the front-end to verify if the request was successful.

NEX-487 - Error displayed after deleting a role, even though role is deleted

---

helpers/form/class.FormContainer.php
manifest.php
scripts/update/Updater.php

Related to https://oat-sa.atlassian.net/browse/TAO-9602
Prevents the PHP warning :
How to reproduce : 
- PHP >= 7.2
- Open a page using a `FormContainer` and check the error logs

prevent count warning on recent php>=7.2

---

manifest.php
models/classes/oauth/OauthService.php
scripts/update/Updater.php

Task: https://oat-sa.atlassian.net/browse/NEX-320
Add methods to check that oauth_body_hash matches with body contents in OauthService, but do not perform actual check due to compatibility with unknown LTI clients. (should be fixed in the feature)
So, this PR should not change OauthService behavior, it only defines `protected function validateBodyHash(...)` which was overridden in https://github.com/oat-sa/extension-tao-lti/pull/215

add body hash validation stub in OauthService

---

manifest.php
scripts/update/Updater.php
views/package.json

Related to: https://oat-sa.atlassian.net/browse/TAO-9965
Requires: 
Update the package `@oat-sa/tao-core-ui` in order to get the last version of the `ui/dropdownForm` component
**Review Checklist**

Feature/tao 9965/Update ui/dropdownForm

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/TAO-9965
Requires: 
Update the package `@oat-sa/tao-core-ui` in order to get the last version of the `ui/dropdownForm` component
Fix a package versions issue (last PR was merged too quickly)
**Review Checklist**

Fix/tao 9965/Update ui/dropdownForm - Fix a package version issue

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/TAO-9965
The previously published package for `@oat-sa/tao-core-ui` was containing corrupted bundles. A component from a TAO extension has been added somehow in the dist folder.

Fix/tao 9965/fix bundling

---

manifest.php
scripts/update/Updater.php
views/build/package-lock.json
views/build/package.json

**Warning** Do not merge this PR before the companion PR. Once the companion is merged and released, update the version in the file `views/build/package.json` and run `npm i`. Then you'll can merge it.
Edit: companion PR has been merged, so you may proceed with the review and merge of this PR.
Related to: https://oat-sa.atlassian.net/browse/ACTP-283
Requires: 
When developing under Windows, we cannot bundle the assets since the bundler task is raising the error:
```
>> Error: SyntaxError: Invalid Unicode escape sequence
>>     at C:\xampp\apps\tao\tao\views\build\node_modules\requirejs\bin\r.js:27738:40
Fatal error: Unable to bundle your code
```
How to test:
- run `npm i` in the `tao/views/build` folder
- under a *nix machine, make sure the bundling is working well by running a bundling …

Fix/actp 283/bundling issue under windows

---

manifest.php
scripts/update/Updater.php
views/js/generis.tree.select.js
views/package-lock.json
views/package.json

**Related to task:**  https://oat-sa.atlassian.net/browse/NCC-110
On the "new assignment" when the user clicks on a sub-folder, event "change" is fired and handler subscribed on that event checks if folders has any selected items.
In case there is at least one selected item the button "Assign" change state to enabled.
The problem is on the first click on sub-folder there is no items and we do request to load them
When data for items is loaded the "change" event has been fired before items are rendered.
That's why we have to notify handler that items are loaded and rendered
**Steps to reproduce:** 
1. Log in as Sponsor
2. Go to Child Organization
3. Go to test Assignments
4. Click the "Add New assignment" button
5. Click the folder containing the desired battery
**Unit …

Fix/ncc 110/trigger select on items list loaded

---

manifest.php
scripts/update/Updater.php
views/js/form/post-render-props.js
views/js/uiForm.js

- TBD-13 feat: support `copy-to-clipboard` action on any form field with `copy-to-clipboard` class
Required by [taoLti extension](https://github.com/oat-sa/extension-tao-lti/pull/232).

TBD-13: Support custom copy-to-clipboard form fields

---

manifest.php
models/classes/theme/ConfigurableTheme.php
scripts/update/Updater.php
views/templates/blocks/head.tpl
views/templates/layout.tpl

- UDI-190 feat(layout): allow rendering `<head>`-nested elements via `head` template
- UDI-190 chore(layout): render a favicon `<link>` via `head` template
- UDI-190 chore(version): bump a minor one
- UDI-190 feat(layout): allow overriding a `title` tag via a themed `head` template
Is a dependency for [taoUdir PR #49](https://github.com/oat-sa/extension-tao-udir/pull/49)

UDI-190: Allow rendering of theme based head elements

---

manifest.php
scripts/update/Updater.php

This PR add dependency of tao-code on funcAcl extension without mentioning it in manifest.php:
https://github.com/oat-sa/tao-core/pull/1568/files
This adds cyclic dependency (tao-code and funcAcl depends on each other).
Current PR removes this cyclic dependency.

remove funcAcl dependency

---

manifest.php
models/classes/oauth/lockout/storage/KvLockoutStorage.php
models/classes/oauth/lockout/storage/LockoutStorageAbstract.php
models/classes/oauth/lockout/storage/LockoutStorageInterface.php
models/classes/oauth/lockout/storage/RdsLockoutStorage.php
scripts/install/SetUpOAuthLockoutService.php
scripts/update/Updater.php
test/unit/oauth/lockout/IPLockoutTest.php

- NFER-66 fix(setup): run migrations during `OAuthLockoutService` installation only in case of `RdsLockoutStorage`
- NFER-66 chore: extract a lockout persistence layer location from a storage implementation into `LockoutStorageAbstract`
- NFER-66 chore: inject a key-value persistence ID into `KvLockoutStorage` during the service installation
- NFER-66 feat: implement `KvLockoutStorage`
- NFER-66 chore: change `LockoutStorageInterface::store()` return type to `void`
- NFER-66 chore(version): bump a minor one

NFER-66:  Implement a key-value storage for the OAuth lockout service

---

manifest.php
scripts/update/Updater.php
views/js/layout/tree/provider/jstree.js

- BOSA-82 fix(tree): retain `lastSelected` item identifier
- BOSA-82 chore(tree): extract repeating node selection by ID into a method
- BOSA-82 chore(tree): reorganize and simplify `jstree.init.treeOptions.callback.onload.nodeSelection()` method
- BOSA-82 chore(version): bump a fix version
One way to reproduce the issue is to open a list of Tests, select a not-selected-by-default-test and publish it. The focus will jump back to the selected-on-render item.
This PR fixes it, and retains the focus on an item, selected last.

BOSA-82: Last selected tree item doesn't retain focus after performing an action on it

---

helpers/class.Display.php
manifest.php
scripts/update/Updater.php
test/unit/DisplayHelperTest.php

- UNO-195 fix(sanitization): respect unicode string length in `tao_helpers_Display::textCleaner()` method
- UNO-195 feat(sanitization): allow unicode characters for `UTF*` encodings in `tao_helpers_Display::textCleaner()` method
- UNO-195 chore(version): bump a fix one
One way to reproduce the issue is to try and export any item/test/delivery with a multibyte unicode symbol in its label. The suggested file name name would be distorted.

UNO-195: Support unicode display name

---

manifest.php
models/classes/extension/UpdateLogger.php
scripts/update/Updater.php
test/TaoPhpUnitTestRunner.php
test/integration/extension/UpdateLoggerTest.php

This backport will fix an issue when several instances launched at one time and try to create the same file.
Original PR: https://github.com/oat-sa/tao-core/pull/2318

Backport/act 404/fix tao update log

---

manifest.php
models/classes/service/InjectionAwareService.php
scripts/update/Updater.php
test/unit/models/classes/service/InjectionAwareServiceTest.php

skip checking parent constructor inherited from Configurable
added support of variadic parameters

UNO-205: Allow variadic arguments in InjectionAwareService implementations

---

actions/form/class.SimpleProperty.php
manifest.php
scripts/update/Updater.php

Requires [`generis`](https://github.com/oat-sa/generis/pull/784).
This PR doesn't do much, except for adding the `Alias` property to schema management form, and required for [`taoDeliverConnect`](https://github.com/oat-sa/extension-tao-deliver-connect/pull/58).
- [UNO-229](https://oat-sa.atlassian.net/browse/UNO-229) feature: add `GenerisRdf::PROPERTY_ALIAS` to the schema form
- [UNO-229](https://oat-sa.atlassian.net/browse/UNO-229) chore(dependency): depend on `generis` `12.21.0`, which introduced `GenerisRdf::PROPERTY_ALIAS`

UNO-229: Add alias to schema form

---

manifest.php
scripts/tools/CleanClass.php
scripts/update/Updater.php

Related to: BSA-119
Fixed deprecated class in cleanup script
How to test(example): `php index.php  '\oat\tao\scripts\tools\CleanClass' 'taoItems_models_classes_ItemsService' 'taoItems' 'http://sample/bosa.rdf#i5e284568c573919336809f37f03c7c0c9'`

Fix deprecated in cleanup

---

actions/class.RestController.php
manifest.php
models/classes/action/RestControllerInterface.php
models/classes/routing/ActionEnforcer.php
models/classes/session/restSessionFactory/RestSessionFactory.php
scripts/update/Updater.php
test/unit/session/RestSessionFactoryTest.php

This improvement allows using controllers as services.
Improvements:
1. Added an attempt to fetch service from the service locator
2. Is not mandatory to extend controllers from tao_actions_RestController or any other so a controller can be a `ConfigureableService` or `InjectionAwareService` or any other
3. Action parameters resolving using the service locator
4. To use facilities of Rest controllers `\oat\tao\model\action\RestControllerInterface` implemented
5. Controllers are more unittestable.
6. You can pass a Request as a parameter by just specifying it.
example of the controller
```php
class Controller implements RestControllerInterface
{
public function event(
ServerRequest $request,
NotificationService $notificationService,
LoggerService $logger
): Response { …
```

Feature/uno 267/enable oauth for pasp event

---

manifest.php
scripts/update/Updater.php
test/unit/http/formatter/ResponseFormatterTest.php
views/templates/blocks/header-main-navi.tpl

**Related to**
https://oat-sa.atlassian.net/browse/BSA-144
**Title**
Items in drop-down menus are not translated
As a user.
I want drop-down menus to be translated.
So I can better understand the meaning of menu items.
Translations are mostly present, but still, all items are in English
**Acceptance criteria**
The menus shown in the attached images have translated values

BSA 144 - Fix missing translations

---

manifest.php
scripts/update/Updater.php
views/js/controller/backoffice.js

Related to: https://oat-sa.atlassian.net/browse/NEX-1191
When user try to add an image by URL function getResourceType called
`getResourceType: function getResourceType(url, callback) {`
https://github.com/oat-sa/tao-core-sdk-fe/blob/d222ef0a28298b76eb1e5718a63a466a2a21356b/src/core/mimetype.js#L41-L61
Sometimes ajax request failed because of CORS policy in this case `request.status === 0`
In `views/js/controller/backoffice.js` we listen to all ajax errors.
No need to show a popup with error in this case because it will be handled in proper Widgets
1. Go to 'Items' tab.
2. Create a new item and go to Authoring.
3. Put inline bock and insert an image.
4. Put the image's URL into 'File' field in Image Properties.

Fix NEX-1191 don't show error if HEAD request failed because of CORS

---

manifest.php
views/package-lock.json
views/package.json

- [VFV-15](https://oat-sa.atlassian.net/browse/VFV-15) fix: upgrade `@oat-sa/tao-core-ui` to version `1.4.2`, which contains a fixed stylesheet, correcting the placement of test element action separators
- [VFV-15](https://oat-sa.atlassian.net/browse/VFV-15) chore(version): bump a fix one

Fix VFV-15 misplaced test element action separators

---

manifest.php
models/classes/extension/UpdateExtensions.php
test/unit/extension/UpdateExtensionsTest.php

Post update scripts have to be run after migrations applied.
Execution of migrations done in the `tao-core` extension so post update script must be run in the very end of tao update process.

move post update scripts call to tao-core

---

actions/class.CommonRestModule.php
manifest.php

Related to: https://oat-sa.atlassian.net/browse/TCA-678
REST API doesn't allow us to use a data from the body, that required with PUT action.
- send PUT with the data that has to be updated in the resource
- nothing changed
```
curl --location --request PUT 'http://tao-act.loc/taoLti/RestService/index?uri=http%3A%2F%2Fsample%2Fact.rdf%23i5ef44f33c222b694e6664782566e0038' \
--header 'Accept: application/json' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic ###' \
--data-raw '{
"oauth_consumer_key": "valfromput2",
"oauth-key": "valfromput2_oauth",
"label": "labelfromput2",
"oauth-secret": "secretfromput2",
"oauth-callback-url": "callbackfromput2"
}'
```
**uri** - ID of the LTI consumer
or use any other tools like a Storm's …

Fix/tca 678/rest put request

---

manifest.php
models/classes/event/UserCreatedEvent.php
models/classes/event/UserRemovedEvent.php
models/classes/event/UserUpdatedEvent.php
test/unit/models/classes/event/UserCreatedEventTest.php
test/unit/models/classes/event/UserRemovedEventTest.php

This PR aims to add webhook for user creation and deletion.
It covers: 
- From UI user manager, create and delete
- From TAO cli, user import is triggering userCreatedEvent (except test taker)
*NB:*
In user management we can add testtaker role to a user. In reality, this is not used like that and this testtaker cannot be assigned to any test. Business is considering all users created in this section as backoffice user

Feature/nex 1094/backoffice user metrics

---

models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php

On previous implementation we were checking if the `taoSimpleDac` extension was enabled, what isn't really a reliable way to check. Instead, we are now checking if the PermissionProvider implements an interface

TAO-10365 Changed IndexDocumentBuilder.php to not rely on Extension Manager

---

models/classes/WidgetDefinitions.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php
models/classes/search/tasks/UpdateResourceInIndex.php

The goal of this PR is to allow a resource with SearchTextBox property to be indexed properly
This change covers:
- Indexation when saving an resource
- Full indexation via UI (dev tools enabled
- Full indexation by CLI

TAO-10367 Add SearchTextBox to indexation process

---

config/default/security-xsrf-token.conf.php
manifest.php
migrations/Version202008030748582234_tao.php
models/classes/security/xsrf/TokenService.php
views/package-lock.json
views/package.json

NSUP-28 and NSUP-27
Depends on https://github.com/oat-sa/tao-core-sdk-fe/pull/68
For one of the our clients, we need to disable xsrf tokens. By default, we can disable only validation on the server-side, but on FE side we will still try to get a token from the queue.
Because of that we added a new option which allows to reuse tokens from the queue again and send it to the server. 
How to reproduce that issue:
1. `config/taoQtiTest/testRunner.conf.php` set: `'csrf-token' => false`
2. `config/tao/security-xsrf-token.conf.php` set `poolSize' => 5`
3. Run a test with more than 5 items
4.  While in passing the test you will see the next error: `No tokens available. Please refresh the page.`
How to check the fix:
1. Update tao-core with tao-core-sdk-fe.
2. …

Feature/nsup 27/disable validation tokens

---

manifest.php
models/classes/security/xsrf/TokenService.php
scripts/tools/SetupClientCsrfTokenPoolStore.php
test/unit/model/security/xsrf/TokenServiceTest.php
views/package-lock.json
views/package.json

- [TBD-48](https://oat-sa.atlassian.net/browse/TBD-48) chore: apply strict types and define return and argument types in `TokenService`
- [TBD-48](https://oat-sa.atlassian.net/browse/TBD-48) feat: add `TokenService::OPTION_CLIENT_STORE` option support, defining a client-side store for the token pool
- [TBD-48](https://oat-sa.atlassian.net/browse/TBD-48) feat: add `SetupClientCsrfTokenPoolStore` script action, allowing to redefine `TokenService`'s `clientStore` option value
- [TBD-48](https://oat-sa.atlassian.net/browse/TBD-48) chore(version): bump a minor one
- [TBD-48](https://oat-sa.atlassian.net/browse/TBD-48) chore(dependency): add a dependency on `@oat-sa/tao-test-runner-qti` `1.6.2`, fixing a client-side CSRF token pool initialization
ℹ️ Run `php index.php …

Feature TBD-48 configurable csrf token pool store

---

actions/class.Search.php
manifest.php
views/js/layout/search.js

- [TAO-10108](https://oat-sa.atlassian.net/browse/TAO-10108) chore: apply `strict_types` to `class.Search.php`
- [TAO-10108](https://oat-sa.atlassian.net/browse/TAO-10108) chore: declare return types of `tao_actions_Search` methods
- [TAO-10108](https://oat-sa.atlassian.net/browse/TAO-10108) chore: inject services into methods of `tao_actions_Search` instead of fetching them directly from a service locator
- [TAO-10108](https://oat-sa.atlassian.net/browse/TAO-10108) fix: remove a catch of never-thrown `SyntaxException` from `tao_actions_Search::search()`
- [TAO-10108](https://oat-sa.atlassian.net/browse/TAO-10108) feat: display `Access Denied` instead of a search result element in cases a current user has no `READ` permission on the element
- …

Fix TAO-10108 apply ACL to search results

---

manifest.php
views/package-lock.json
views/package.json

**Related to this PR - Needs to this PR merge before and published**
https://github.com/oat-sa/tao-core-ui-fe/pull/163
**Related to this issue**
https://oat-sa.atlassian.net/browse/TAO-10464
When the user drags the Media Interaction on the canvas, there's no file selection window opens. Instead 'Uncaught type error' appears on the browser console and the widow opens only after clicking empty space outside the interaction and clicking it again.
**Steps to reproduce**
- Go to the Items tab.
- Create a new item and go to Authoring.
- Drag and drop Media Interaction on the canvas.
**Actual result**
Error in console, the file selection window is not opened.
**Expected result**
The file selection window shows up without any errors.

Fix TAO 10464 - Uncaught type error upon dragging the Media Interaction on canvas

---

actions/class.Search.php
manifest.php
models/classes/routing/ActionEnforcer.php

JIRA ticket: https://oat-sa.atlassian.net/browse/TAO-10108
Fixed input parameter type to support other implementations of search service
Details: 
Previous change made in https://github.com/oat-sa/tao-core/pull/2636 broke advanced search functionality when using elasticsearch implementation - https://github.com/oat-sa/lib-tao-elasticsearch/blob/master/src/ElasticSearch.php as a SearchService.
How to test:
- configure search.conf.php to retunr instnce of `ElasticSearch` instead of `GenerisSearch`
- make sure it doesn't fail when trying to use advanced search

Fix/tao 10108/use interface in method type

---

manifest.php
views/package-lock.json
views/package.json

**Needs merge and publish this PR's first**
https://github.com/oat-sa/ckeditor-dev/pull/20
https://github.com/oat-sa/tao-core-shared-libs-fe/pull/9
**Related to**
https://oat-sa.atlassian.net/browse/UNO-444
There're some issues with layers when the browser window resolution set to the smaller size e.g. 900x700 and the item has a property type set to Text - Long - HTML editor: the list of background tasks partially covered by edit item properties form. Reproduced only in `UDIR` demo environment.
**Preconditions**
Class property type is set to Text - Long - HTML editor.
**Steps to reproduce**
- Navigate to the Items tab
- Narrow the browser window 
- Open the Background tasks menu
**Actual result**
The opened Background tasks menu is partially covered by 'Kommentar' field in …

Fix UNO 444 - Broken layers in DEMO when background tasks menu opened

---

actions/class.Search.php

Ticket: https://oat-sa.atlassian.net/browse/TAO-10495
The Problem:
To satisfy the requirements of US https://oat-sa.atlassian.net/browse/TAO-10454, we need to provide the totalCount attribute to FE be able to render it.
The Solution:
The information already exists on the BE, I just exposed it on the response.

TAO-10495 expose totalCount attribute on search endpoint

---

models/classes/resources/ResourceWatcher.php
models/classes/search/index/IndexIteratorFactory.php
models/classes/search/tasks/UpdateClassInIndex.php
test/unit/extension/UpdateExtensionsTest.php
test/unit/model/validator/PropertyChangedValidatorTest.php
test/unit/models/classes/resources/ResourceWatcherTest.php
test/unit/models/classes/search/index/GenerisIndexDocumentBuilderTest.php
test/unit/models/classes/search/index/IndexIteratorFactoryTest.php
test/unit/models/classes/search/index/IndexServiceTest.php
test/unit/models/classes/search/tasks/UpdateClassInIndexTest.php

This implementation is intended to cover the ticket https://oat-sa.atlassian.net/browse/TAO-10287.
**Before this implementation:**
- Resources were not indexed when the owner class was changed (Move the class to another one).
**After this implementation:**
- Resources are now indexed by using the ResourceUpdate event. Exception for the editItemClass HTTP action, which is using other events (ClassPropertiesChangedEvent, ClassPropertyRemovedEvent) to reindex the documents.
- Old unit tests were fixed by adding namespaces, mocks

TAO-10287 reindexed resources when moving classes

---

manifest.php
test/unit/service/EntryPointServiceTest.php
test/unit/session/Business/Service/SessionCookieServiceTest.php
test/unit/session/DataAccess/Factory/SessionCookieAttributesFactoryTest.php

- [CICD-141](https://oat-sa.atlassian.net/browse/CICD-141) fix: set `@runInSeparateProcess` on each test instead of running a whole test class in a separate proccess, which apparently fails for some set ups
- [CICD-141](https://oat-sa.atlassian.net/browse/CICD-141) chore(version): bump a fix one

Fix CICD-141 certain tests do not run in a separate process

---

manifest.php
models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

__task:__ https://oat-sa.atlassian.net/browse/UNO-490
__description:__ Creating list - Wrong order
__how to test:__
1. Add a new list with e.g. 5 elements;
2. Click 'Edit the list' button;
3. Add a new element to the list;
4. Save;
__expected Result:__ the order of the added elements must be preserved

Fix/uno 490/creating list wrong order

---

actions/form/class.UserSettings.php
manifest.php
models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

Related to : https://oat-sa.atlassian.net/browse/UNO-312
Make users timezone configurable.
1. Log in as admin
2. Click the 'User settings' button on the top right of the window (2nd button from the right);
3. There is no Timezone for the user if system configured with `config/generis/UserTimezoneService.conf.php`
```
'userTimezoneEnabled' => false
```
Requires :

Feature/uno 312/configured show users timezone

---

actions/class.PropertiesAuthoring.php
manifest.php

**Related to task:**  https://oat-sa.atlassian.net/browse/UNO-302
**Description:** 500 error when adding second property right after added first one without page refresh
**How to test:** 
1. Select a folder;
2. Click 'Manage Schema';
3. Click 'Add property';
4. Click pencil icon;
5. Select 'List - Single choice - Drop down' as a type';
6. Select any 'List values';
7. Save;
8. Repeat steps 3-7 to add one more property.

Fix/uno 302/500 error when adding second property item manage schema

---

actions/class.Export.php
actions/form/class.Export.php
manifest.php

Related to : https://oat-sa.atlassian.net/browse/UNO-277
Added InfoBox to the export form factory.
run $form->setInfoBox('message') and you will see this message on top of the export form:
Companion PR :

UNO-277: Added InfoBox to the export form

---

manifest.php
views/js/uiForm.js

Related to : https://oat-sa.atlassian.net/browse/TAO-10569
Do not set value for property list values, if it is empty.
- manage schema of any items class
- add some properties
- select `List - Single choice - Radio button` as property type
- select some list value
- save schema and make sure the property value and list type saved

[TAO-10569] Manage schema - List values don't preserve selected value if add several properties

---

manifest.php

When trying to use ClassMetadata endpoint I'm logged out from TAO
https://oat-sa.atlassian.net/browse/CON-23

ClassMetadata is missing acl

---

models/classes/Lists/Business/Service/ClassMetadataService.php

#Description
When the user sets a property to the item, he is not able to select this property as a criterion in the modal view. 
Preconditions: added property to the class.
#Steps to reproduce:
Trigger a search from the "Search bar" to open a modal view
Click "add criteria"
Actual result: no items shown in drop-down menu (please see actual_result.gif in the Attachments).
Expected result: existing properties are shown in the criteria drop-down menu (please see expected_result.gif in the Attachments).
ticket:
https://oat-sa.atlassian.net/browse/CON-176
can be tested here :
https://noudi01aud.udir.taocloud.org/tao/Main/index

removed condition and added check if there is a widget

---

manifest.php
models/classes/theme/ConfigurablePlatformTheme.php

Hotfix under task [CGF-69](https://oat-sa.atlassian.net/browse/CGF-69)
Due to the mess in theming code sometimes templates requested by path instead of ID and the current implementation does not handle such situations. My fix improves the situation but does not solve the root issue. In other words, it is a hotfix that avoids us unblock customers environments.
Install on any instance [Look & Feel extension](https://github.com/oat-sa/extension-tao-styles) (note, that it is private, so do not forget to add repo link into repositories section in composer file).
After go to https://YOUR_INSTANCE_URL/tao/Main/index?structure=settings&ext=tao&section=taoStyles_main and try to change the theme. Before with you will see a blank screen with javascript errors and nothing more. Also, in logs a lot of …

Determine when template requested by path instead of id

---

manifest.php
views/js/lib/raphael/raphael.js
views/package-lock.json
views/package.json

**Issue**
https://oat-sa.atlassian.net/browse/CON-203
**Related work**
https://github.com/oat-sa/extension-tao-itemqti/issues/1577
The color of all arrowheads (including axis arrowheads) changes, when we change the current line or add new. So, it will always inherit the color from the last path created with the arrow-end/ arrow-start attribute set.
The full description of [issue](https://github.com/oat-sa/extension-tao-itemqti)/issues/1577
Also, it looks like the PCI settings are broken on the construct side. When trying to open Lines options an error pops up in the console.
**AC**

Fix [CON-203] - Color of arrowheads does not match with color of lines

---

.github/workflows/release.yml

Automated release of the extensions fails because of the changes in repository:
```
➡ Checking extension status
The extension tao has local changes, please clean or stash them before releasing
```
The changes are:
```
Changes not staged for commit:
modified:   views/package-lock.json
```

ci: discard changes in repository before release

---

.github/workflows/release.yml

That fix should solve the error during automated release:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/adobe-webplatform/eve.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
```

ci: use https protocol instad of ssh

---

models/classes/security/xsrf/TokenService.php
test/unit/model/security/xsrf/TokenServiceTest.php

This fixes `TokenService::validateToken()` not actually checking the provided token value, and accepting anything.
- chore: [TR-908](https://oat-sa.atlassian.net/browse/TR-908) clean up useless test cases and conditions from `TokenServiceTest`
- fix: [TR-908](https://oat-sa.atlassian.net/browse/TR-908) check `X-CSRF-Token` header value against server-stored tokens via `TokenService::validateToken()`
Caused by https://github.com/oat-sa/tao-core/pull/2655/files#diff-755eff4da554fe5ca1678fdd0bce56daff2827518c160ba87f347a56051f9c47R147

fix: TR-908 enable CSRF token validation

---

views/package-lock.json

Previous package-lock gave error
> Could not install from "node_modules/raphael/eve@git:/github.com/adobe-webplatform/eve.git#eef80ed" as it does not contain a package.json file.
Please check:
`cd views`
`npm ci`

Regenerate package-lock without eve@git weirdness

---

actions/class.Main.php
actions/class.Users.php

https://oat-sa.atlassian.net/browse/AUT-342
This PR fixing html injection vulnerability according this report 1.1 https://www.exploit-db.com/exploits/48341
***How to check:***
- go to http://test-nik.playground.kitchen.it.taocloud.org:48161/
- Move on top right to the user button and click manage users
- Inject html script code payload into the vulnerable input fields
- Save the entry
- Open to the manage users listing
- Validate that html injections not appear as DOM objects

fix: draft fix for html injections in user management

---

views/package-lock.json
views/package.json

Related to: [AUT-396](https://oat-sa.atlassian.net/browse/AUT-396)
Related to: https://github.com/oat-sa/tao-core-ui-fe/pull/279
Added deleted node to `deleted.deleter` event. It is important because this event fires on the parent node, and we should have a possibility to detect which node was removed.

fix/AUT-396/update @oat-sa/tao-core-ui

---

models/classes/security/xsrf/TokenService.php
models/classes/security/xsrf/TokenStoreSession.php

Ticket: https://oat-sa.atlassian.net/browse/TR-1040
Root cause: TokenService relies on a storage key that doesn't exist when filtering out the form token before the token pull is provided to a client. As a result, there are 10 regular CSRF tokens mixed with a form token that should never be there.
This has been tested in Kitchen already by QA.

Fix: form token is no longer used as a regular CSRF token

---

views/js/layout/loading-bar.js

Related to: [TR-981](https://oat-sa.atlassian.net/browse/TR-981)
It happens when the page's height has decimals. Browser zoom enabled creates this situation. 
Loader set a full height without decimals and overflow the page.
I can reproduce it in any browser.
**Steps to reproduce**:
Ej: 881 x 982 px body height + zoom 150% (Chrome)

Fix: TR-981/scrollbar-between-item-pages

---

views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/TR-1207
Requires: 
Update the package `@oat-sa/tao-core-sdk`.
> Add a variant for the helper `formatDateTime()` to also support timestamp in UTC.
>
> By default, the helper will continue assuming the supplied timestamp is in the user's timezone. However, the second parameter of the helper allows qualifying the timestamp as being in UTC instead.

Feature/TR-1207/Add locale format for DateTime in UTC

---

views/js/layout/tree/provider/jstree.js

**Ticket**
https://oat-sa.atlassian.net/browse/ADF-100
**Environment to test**
The link to the playground is in the ticket
When user tries to move the item from one class to another using Drag-and-Drop, there's a warning pop-up message about replacing current object's properties with the new ones from destination class. However, clicking the 'Cancel' button in this message does not prevent the object from moving to the new class. Therefore, item is moved and the properties are replaced or removed nevertheless.
**Steps to reproduce**
- Go to Items tab and create 2 new classes.
- Click 'Manage schema' and then 'Add property' for one of the classes.
- Click on 'pencil' icon on the newly added property and set 'Type' (f.e. 'List - Single choice - Drop down')
- Create a new …

[Fix] ADF-100 - CORE: The 'Cancel' button in warning message does not prevent the object from moving to another class.

---

actions/class.Search.php
config/default/search.conf.php
manifest.php
migrations/Version202106010945122237_tao.php
models/classes/AdvancedSearch/AdvancedSearchChecker.php
models/classes/search/ElasticSearchBridge.php
models/classes/search/IdentifierSearcher.php
models/classes/search/Search.php
models/classes/search/SearchInterface.php
models/classes/search/SearchProxy.php
models/classes/search/SearchQuery.php
models/classes/search/strategy/GenerisSearch.php
models/classes/user/GenerisUserService.php
scripts/install/RegisterSearchServices.php
test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
test/unit/models/classes/search/IdentifierSearchTest.php
test/unit/models/classes/search/SearchProxyTest.php
test/unit/user/GenerisUserServiceTest.php

Centralize search to proxy, so we can manage the feature flag in a single place
https://oat-sa.atlassian.net/browse/ADF-258
Related PRs

feature: making search proxy central point for search

---

views/js/layout/actions/common.js

Whenever user is trying to move the object (item, test etc.) from one class to another by dragging the object, the error appear in browser console after clicking 'OK' in pop-up message (in case it appears).
**Preconditions**
Having at least 2 classes and at least 1 resource created on any tab.
**Steps to reproduce:**
- Go to Items tab.
- Choose any existing item.
- Drag and drop the chosen item to another class.
- Click 'OK' on pop-up message (if it appears).
**Actual result**
The error appears in browser console.
**Expected result**
No errors in browser console.
**Environment**
Deployed for testing, link in ticket

[Fix] ADF-450 Moving object from class to class by drag-and-drop causes error

---

actions/class.RdfController.php
models/classes/accessControl/ActionAccessControl.php
test/unit/accessControl/ActionAccessControlTest.php

**Relates to:** _[ADF-532](https://oat-sa.atlassian.net/browse/ADF-532)_
**Changes:**
* Fixed invalid annotation;
* Added log to check actions access;
* Fixed test.
**Require:** _installed `taoDacSimple`._
**How to test:**
1. Open Items tab;
2. Select any class;
3. Open `Schema Management`;
4. Add new property;
5. Try to delete it;
6. Click save or reload the page and reopen `Schema Management`.
**Bug:** _property was not deleted._
**Fix:** _property successfully deleted._

Fix/ADF-532/Fix DAC annotation which blocks class property deletion

---

views/cypress/support/resourceTree.js
views/js/layout/actions/common.js
views/js/layout/section.js

**Jira**
https://oat-sa.atlassian.net/browse/ADF-508
**The fix**
Clear content block before sending the request for `subClass`
**Bonus**
Added `wait` in class delete test helper to guarantee that the app is ready to open confirmation modal. The issue with cypress not catching the modal is not related directly to the fix, however appeared several times on my local machine while I was working on the ticket. For better understanding the issue with the modal we can create a tech debt ticket if needed. 
**How to test the fix**
Test locally with cypress, make sure the https://github.com/oat-sa/extension-tao-item is up to date with `develop` on your local env
**How to test for regressions**
// TODO: Kitchen env link is in the ticket

Fix/adf 508/cypress form flickering

---

actions/class.RdfController.php

When controllers that are based on `tao_actions_RdfController` were trying to execute event and they did not used use `\oat\oatbox\event\EventManagerAwareTrait`, it was causing fatal error. 
related  PR
https://github.com/oat-sa/extension-tao-mediamanager/pull/292

fix: add missing event manager

---

views/cypress.json
views/cypress/support/commands.js
views/cypress/support/userManagement.js
views/cypress/tests/item-author-role.spec.js
views/cypress/tests/login.spec.js
views/cypress/tests/test-author-role.spec.js
views/cypress/tests/test-taker-role.spec.js
views/cypress/tests/user-management.spec.js
views/cypress/utils/cleanup.js
views/cypress/utils/selectors.js
views/cypress/utils/urls.js
views/cypress/utils/userRoles.js
views/cypress/utils/users.js

**Jira task**
https://oat-sa.atlassian.net/browse/ADF-507
Cover by e2e testing screens authentication into the platform with various users, having different user roles:
- Admin
- Item Author
- Test Author
- Test Taker
**How to run locally:**
- Add admin's credentials in env-local.json in root of cypress/
- Set local TAO address in cypress.json file (baseUrl option)
- npm run cy:open - to run in browser
- or npm run cy:run - for headless execution

[Feature] ADF-507 - E2E user roles

---

views/js/controller/login.js
views/js/layout/search.js

**Ticket**
https://oat-sa.atlassian.net/browse/ADF-534
**What was done**
It turns out that this issue still persisted due to the fact that the client has a different login/logout functionality then where the [previous fix](https://github.com/oat-sa/tao-core/pull/2801) was developed. So in order to completely fix this issue the logic to clear the search store has been moved from the login component to the search component itself. It will now be triggered on every initialisation.

[Fix] ADF-534 AdSearch: Last searching result doesn't refresh after re-login

---

actions/class.PropertiesAuthoring.php

**Relates to** https://oat-sa.atlassian.net/browse/ADF-550
Whenever user adds a property in manage schema, choose it's type then sets the list for it and clicks 'Save' first time, list set for this property is removed and user has to set it up again in order to save added property. Second click on 'Save' button saves the list.

Clicking 'Save' in Manage schema removes the chosen List from the added property

---

views/cypress.json
views/cypress/support/commands.js
views/cypress/support/resourceTree.js
views/cypress/support/userManagement.js
views/cypress/tests/item-author-role.spec.js
views/cypress/tests/test-author-role.spec.js
views/cypress/tests/test-taker-role.spec.js
views/cypress/tests/user-management.spec.js
views/cypress/utils/cleanup.js

Related to: https://oat-sa.atlassian.net/browse/AUT-1034
We have explicitly defined a specific time for most of our request interception/waiting. 
i.e: .wait('@editItem', { requestTimeout: 10000 }) 
We should make this requestTimeout of 10000ms the norm by defining it as a default in cypress.json and removing each explicit mention of it in our .wait() function calls.
**How to test:**
Run cypress and check that all updated tests pass without errors after updating default request timeout.

AUT-1034 move requestTimeout to cypress.json configs

---

views/cypress/support/resourceTree.js

Jira task: https://oat-sa.atlassian.net/browse/ADF-635
Turns out that the `renameSelected` command had already been refactored in task https://oat-sa.atlassian.net/browse/AUT-1035. But two tests were failing after that, so this is now the fix of that refactor.
PR related to: https://github.com/oat-sa/extension-tao-itemqti/pull/1890

ADF-635: E2E testing - Group renameSelected command

---

models/classes/validator/PropertyChangedValidator.php
test/unit/model/validator/PropertyChangedValidatorTest.php

**Changes:**
* Broken tests where refactored and fixed.
* Method `isDependsOnPropertyCollectionChanged` fixed - it will return reversed boolean value.

Fix broken tests

---

views/package-lock.json

**Jira issue**
https://oat-sa.atlassian.net/browse/ADF-695
**Related PR**
https://github.com/oat-sa/tao-core-ui-fe/pull/368
**AC**
- Preselect item gallery when user doesn't have access to Assets.
- Preselect Assets when user does have access.
- Make "Add file" button appear without having to click a folder. (If permissions allow it).
**How to test**
- Make access to Assets forbidden for user. (By restricting access only to Global Manager role) (make it recursive)
- Login with user and author an item
- Try to insert media/image

CUNO-1853 / ADF-695: User without access to assets can save images trough the item

---

helpers/TreeHelper.php

When getOntology data has been called in order to provide tree list for class, endpoint will return only root uri as a return. This fix will fix this issue. 
How to check a bug: 
- Expand few classes levels. Select level 2 class. Refresh site. Tree should be kept in place where your class has been selected. 
- When move to is performed on class resource user will see tree rendered on a moved class resource 
https://oat-sa.atlassian.net/browse/AUT-787

fix: getOntology on class will retrive correect tree

---

helpers/form/elements/xhtml/AbstractXhtmlSearchElement.php

**Preconditions:** A class with 2 properties of Search Input type and one of the properties has 'not empty' option checked; an item created under this class;
- Go to items tab
- Click on item from Preconditions
- Assign list value for the property that is allowed to be empty in Item Properties
- Leave the property with 'not empty' restriction without any value
- Click 'Save'
**Actual result:** The value in the property without restriction replaced with it's URI.
**Expected result:** The value keeps it's label and is not replaced with URI.

[Fix] ADF-789: List values are replaced with URIs if validation of 'not empty' property failed in Item Properties

---

actions/form/class.Instance.php
helpers/form/ElementMapFactory.php

**Associated Jira ticket:** [ADF-841](https://oat-sa.atlassian.net/browse/ADF-841)
This fixes calls being made when creating new instances from the remote publishing admin panel, as there is no instance then (and `null` is passed instead). `ElementMapFactory::withInstance()` will fail in such cases, as it expects a non-null parameter.

fix: Skip calling ElementMapFactory::withInstance() if the instance is not set

---

views/cypress/support/resourceTree.js

**End to end testing.**
Related to: https://oat-sa.atlassian.net/browse/AUT-1195
**Depends on :**
- https://github.com/oat-sa/extension-tao-itemqti/pull/1960
- [oat-sa/tao-mediamanager#359](https://github.com/oat-sa/extension-tao-mediamanager/pull/359)
**Description of changes:**
fix for handling deleteClass function for assets related to e2e tests for: Creating and importing passages/asset and adding to prompt and choice of interaction
Checkout to branch `feature/AUT-1195/e2e-add-asset-passage-to-interaction`
in extensions:
- https://github.com/oat-sa/tao-core
- https://github.com/oat-sa/extension-tao-itemqti
- https://github.com/oat-sa/extension-tao-mediamanager
**run tests from tao core extn:**
npm run cy:open - to run in browser
or npm run cy:run - for headless execution
File to test: …

fix(e2e): adjust deleteClass handling for asset

---

helpers/form/AbstractFeatureFlagFormPropertyMapper.php

Prevents hidden fatal errors and unpredictable behavior whenever no options have been specified in the configuration

fix: gracefull fallback if no configured mapping has been provided

---

views/js/layout/generisRouter.js
views/js/test/layout/generisRouter/test.js

Related to: https://oat-sa.atlassian.net/browse/AUT-1531
Fixed `generisRoute.pushSectionState` - added case for redirected url with `section` and `uri`
**Preconditions**: Passage exported
**Steps to reproduce:**
Navigate to the 'Assets' page.
Click 'Import' button and select 'Shared Stimulus' radio button as import format.
Click 'Browse' and select shared stimulus package
Click 'Import' button.
Open imported passage in `Authoring`
Click Save and preview
Close preview and click "Manage Assets"
**Actual result:** Main tabs and clear panel-authoring displayed. 
**Expected result:** User navigated to the 'Assets' page.

fix/AUT-1531/ generisRoute.pushSectionState update state when redirect to imported resource

---

views/cypress/support/commands.js
views/cypress/support/resourceProperties.js
views/cypress/support/resourceTree.js
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/AUT-973
Update cypress to v9
Stabilize e2e tests
Depends on:

feat/AUT-973/e2e tests: update cypress to v9

---

views/cypress/support/search.js

Added advanced search criteria E2E test case
https://oat-sa.atlassian.net/browse/ADF-740
Must have taoAdvancedSearch extension installed and enabled in enviroment to test.
If it is not present (no extension found or feature flag is found disabling advancedSearch), test case will be skipped on execution time.
- checkout the branch tao core https://github.com/oat-sa/tao-core/pull/3333
- checkout tao items branch https://github.com/oat-sa/extension-tao-item/pull/559
- Run npm run cy:open from the ./tao/views
- Select tao/views/cypress/tests/search-advanced.spec.js

ADF-741 [Feat]E2E: Made default search type empty space

---

actions/class.RestController.php
helpers/RestExceptionHandler.php
helpers/class.Http.php
helpers/form/elements/xhtml/class.Calendar.php
models/classes/mvc/error/ExceptionInterpretor.php
models/classes/mvc/error/HtmlResponse.php
models/classes/mvc/error/ResponseAbstract.php

This is a helper PR to deliver the Delivery property PATCH API endpoint.
- fix: add `Allow` header in case of a `405 Method Not Allowed` request error
- fix: return a proper error response in case of a `406 Not Acceptable` request error
- fix: handle `*/*` `Accept` request header
- feat: treat `common_exception_RestApi` as an HTTP exception, allowing to set any response code and message
- fix: fallback to `user_error` template in case of an unknown http status code
- feat: treat `common_exception_ValidationFailed` as a "400 Bad request" case
- fix: support partially initialized form data retrieval
- feat: support any response code

Feature TR-3070 extend exception handler and response codes

---

views/templates/blocks/careers-js.tpl
views/templates/blocks/careers.tpl

Changed link protocol from `http://` to `https://` in console recruitment messages. For more up-to-date public image!

Use https protocol in console recruitment message

---

models/classes/Lists/Business/Domain/ValueCollection.php
test/unit/models/classes/Lists/Business/Domain/ValueCollectionTest.php

Ticket: https://oat-sa.atlassian.net/browse/ADF-915
We need to put back the previous behavior and ignore duplications in case on empty URIs (which means, new records).

fix: avoid consider duplicated empty URIs

---

views/package-lock.json

Related to https://oat-sa.atlassian.net/browse/TR-3287
- remove the git protocol from the package-lock to prevent issues installing the direct dependency

fix: update the protocol of the eve dependency

---

models/classes/password/PasswordConstraintsService.php
models/classes/taskQueue/Task/TaskLanguageLoader.php

Fix
- remove type hint to ensure php7.2 compatibility
- use extension id as string for exception message

fix: use string fr exception + remove type hint

---

models/classes/dataBinding/class.GenerisInstanceDataBinder.php
test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php

**Associated Jira issue:** [ADF-869](https://oat-sa.atlassian.net/browse/ADF-869)
This pull request fixes the call to `$instance->editPropertyValues()` (near line 140) to just call `removePropertyValues()` or `editPropertyValues()` depending on the value being considered as empty or not.
Previously,
1. The values provided were inserted as-is by calling `editPropertyValues()`, which removed all the values and then inserted the new ones with no conversion, and then
2. `removePropertyValues()` was called for values under the instance being edited **but** using an empty string (`''`) as the matching pattern for the values to be deleted.
This later step may fail in case the RDBMS doesn't _automagically_ turn strings containing only whitespaces into empty strings in step 1 (i.e. if it does not …

feature/ADF-869: Delete previous statements for a property when edited with an empty value

---

models/classes/oauth/OauthService.php

Oauth 1.0 parameters must be included either in request query parameters, `Authorization` header, or body. According to [protocol specification](https://datatracker.ietf.org/doc/html/rfc5849#section-3.5). Currently it was either query params, or query params + `Authorization` header.
Related to: https://oat-sa.atlassian.net/browse/TR-2754
Also updated the auth header construction, other http headers should not be included in signature calculation and replaced formatting with library implementation.
- launch delivery via LTI 1.1 with specified additional parameter `lis_outcome_service_url`, sending a url where result should be submitted. For testing you could use a webhook testing tool like https://webhook.site
- complete the test
- verify that generated request had oauth parameters only …

fix: include oauth parameters in only one place, either query or header

---

actions/class.UserSettings.php

**Associated Jira issue:** [ADF-929](https://oat-sa.atlassian.net/browse/ADF-929)
`tao_actions_UserSettings` was expecting the form container name to be `myForm`  ([here](https://github.com/oat-sa/tao-core/blob/develop/actions/class.UserSettings.php#L69)), but it has been since changed to `settingsForm` as part of another pull request and it seems the new name was not reflected on all places.
Checked as well if this template is used by other controllers -- it doesn't seem to be the case.

fix/ADF-929: Fix password form

---

actions/class.UserSettings.php

**Associated Jira issue:** [ADF-929](https://oat-sa.atlassian.net/browse/ADF-929).
Backporting the password form fix into the [release branch to be used for the February release](https://github.com/oat-sa/tao-community/blob/release-2022-02-lts/composer.json#L31).
This was previously released as tao-core fix version [v49.0.2](https://github.com/oat-sa/tao-core/releases/tag/v49.0.2) (pull request #3373).

fix/ADF-929: Fix password form (2022-02-lts)

---

actions/class.UserSettings.php

**Associated Jira issue:** [ADF-929](https://oat-sa.atlassian.net/browse/ADF-929).
Backporting the password form fix into the https://github.com/oat-sa/tao-core/releases/tag/v48.81.0
This was previously released as tao-core fix version [v49.0.2](https://github.com/oat-sa/tao-core/releases/tag/v49.0.2) (pull request #3373).

[backport] fix: Use the proper form container name for the change password form

---

models/classes/export/implementation/CsvExporter.php

result contains Arabic chars cannot be open be MS Excel correctly without adding BOM charset

TR-3401/BOM to csv exporter

---

views/js/controller/backoffice.js

ℹ️ Caused by #2584 ℹ️
1. Login as a bckoffice user
2. Cause a back-end error upon an action within the backoffice, e.g. ⬇️ 
3. Manually set the value of a delivery end date to a non-parsable one
4. Observe the error message
ℹ️ Indeed, the error message itself is still not human-readable, but it's a lot better than the whole response object displayed as is. The back-end messages will be improved further.
|Before|After|
|-|-| 
|<img width="409" alt="before" src="https://user-images.githubusercontent.com/2943256/154251144-605af23b-4878-4b07-b029-bd0c1c93f6bc.png">|<img width="409" alt="image" src="https://user-images.githubusercontent.com/2943256/154251249-5a55877b-ff7c-4977-9f86-6c9ae32850b6.png">|
- fix: display a human-readable request-handling error instead of a full response body in …

Fix TR-3469 Display human readable request-handling errors in Backoffice

---

manifest.php

Related to: https://oat-sa.atlassian.net/browse/AUT-1882
TAO Version was updated to 2022.02

fix: TAO Version  to '2022.02'

---

actions/form/class.Users.php
helpers/class.Display.php
helpers/form/Feeder/SanitizerValidationFeeder.php
helpers/form/Feeder/SanitizerValidationFeederInterface.php
helpers/form/ServiceProvider/FormServiceProvider.php
helpers/form/class.FormContainer.php
helpers/form/validators/class.Regex.php
models/classes/class.UserService.php
test/unit/helpers/form/Feeder/SanitizerValidationFeederTest.php

* https://github.com/oat-sa/extension-tao-delivery/pull/540
* Added regex validator for login field. The following characters no longer allowed: `"`, `'`, `\`, `/`, `>`, `<`
* Regex validator for login field is configured to be called during form initialization (preliminary validation) and after form submit
* Added possibility to fix existing logins, which contains invalid characters

fix: add regex validator for login and allow to fix broken login

---

helpers/form/class.FormContainer.php
models/classes/security/xsrf/TokenStore.php
models/classes/security/xsrf/TokenStoreKeyValue.php
test/unit/import/Form/MetadataImportFormTest.php
test/unit/model/security/xsrf/TokenStoreKeyValueTest.php

* https://github.com/oat-sa/extension-tao-bosa-selor/pull/117
* Removed unused `TOKEN_NAME` constant
* Added/changed constants' visibility:
* `const OPTION_PERSISTENCE` ===> `public const OPTION_PERSISTENCE`
* `const TOKENS_STORAGE_KEY` ===> `private const TOKENS_STORAGE_KEY`
* Changed visibility for methods:
* `protected function getPersistence()` ===> `private function getPersistence()`
* `protected function getKey()` ===> `private function getKey()`
* Changed all hash function calls to simple key functions
* Added new option `ttl` to configure TTL value

Fix/TR-3634/Switch from hash keys to simple keys, use ttl for tokens

---

models/classes/oauth/OauthService.php

Backport of https://github.com/oat-sa/tao-core/pull/3368 for https://oat-sa.atlassian.net/browse/TR-3785, targeting November release.

[Backport] TR-3785 oauth 1 parameters in header

---

views/js/layout/tree/provider/jstree.js

Related to: [AUT-1785](https://oat-sa.atlassian.net/browse/AUT-1785)
Remove the lock icon next to load more links in the resource tree.
**Changes:**
Exclude node type "more" from  addClassToNode logic that is decorating based on permission styles
**How to check:**
- Go to booklets
- Create multiple booklets to have more button
- Click the more button
- See lock icon is not appearing after loading the next items
**Requires:**
- Checkout tao-core https://github.com/oat-sa/tao-core/pull/3443
- Install taoBooklet extension
- For easy testing, you can decrease the limit amount booklets to show in tao/views/js/layout/tree/provider/jstree.js :42 var pageRange = 30;

AUT-1785 fix: exclude more type from permissions check

---

helpers/form/ElementMapFactory.php

Forgot return statement in the previous PR https://github.com/oat-sa/tao-core/pull/3463
**How to test**
- Pick a resource and replace one of it's properties label with an empty string in db
- Go to resource Edit form
- Verify that property description has uri w/o instance namespace, instead of empty string
**Ticket**
https://oat-sa.atlassian.net/browse/REL-665

fix: use uri for empty property label case

---

helpers/form/ElementMapFactory.php

The related task is [REL-665](https://oat-sa.atlassian.net/browse/REL-665)
It raises the issue on the Premium.
It fixes issues introduced [here](https://github.com/oat-sa/tao-core/pull/3463/files) and [here](https://github.com/oat-sa/tao-core/pull/3467/files)
**How to test?**
Create a user with a different than the default language interface language, log in with this user, and try to reach any type of object (or even rdf forms). For example, create a new user. You will get 500 error, which is unexpected normally.

Checking empty value of label to avoid fatal errors

---

models/classes/featureVisibility/FeatureVisibilityService.php
test/unit/featureVisibility/FeatureVisibilityServiceTest.php

Related to https://oat-sa.atlassian.net/browse/AUT-2081 and https://oat-sa.atlassian.net/browse/AUT-2042
The key in the configuration wasn't matching the implementation due to a mistake in the PR description. 
how to test:
- run the unit test `./vendor/bin/phpunit --color tao/test/unit/featureVisibility/FeatureVisibilityServiceTest.php`
- configure a key, using a script for example and inspect the file `config/tao/client_lib_config_registry.conf.php` to look for the something like 
```
'services/features' => array(
'visibility' => array(
'item/interaction/endAttempt' => 'hide'
)
)
```

fix: fix the configuration key for the feature visibility service

---

actions/form/class.Instance.php
helpers/form/ElementMapFactory.php

Backport of the following PRs:
https://github.com/oat-sa/tao-core/pull/3463
https://github.com/oat-sa/tao-core/pull/3467
https://github.com/oat-sa/tao-core/pull/3484
While editing a resource, property labels are not translated based on User Interface language.
This PR aims to fix it
**How to test**
- Change user language
- Go to item tab and select Item
- Edit form should be translated (Label) if token exist in PO files

[Hotfix] Make properties label searchable by language

---

models/classes/Lists/Business/Domain/ValueCollection.php
models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

**Associated Jira issue:** [ADF-978](https://oat-sa.atlassian.net/browse/ADF-978)
Note this removes the call to `enrichWithSelect()` from `count()` methods since the fields added with it are then replaced by `$query->select('count(t.id) AS c')`.
Related PRs:
- https://github.com/oat-sa/extension-tao-backoffice/pull/139

fix/ADF-978: Improve performance of item loading for lists in the backend

---

helpers/form/ElementMapFactory.php

Fallback to default language to translate form labels
Related to : https://oat-sa.atlassian.net/browse/REL-714
- Log in as a user which has interface language defined different than system default (f.e. jp-JP)
- Open a form with some missing label translations (f.e. Test Taker form)
- Verify that all labels are present, and label translation is shown in system language in case interface language translation is missing

fix: fallback to default language for form labels

---

helpers/form/ElementMapFactory.php

Backport of https://github.com/oat-sa/tao-core/pull/3492 for https://oat-sa.atlassian.net/browse/REL-714

[Backport] fix: fallback to default language for form labels

---

manifest.php

Related Issue: https://oat-sa.atlassian.net/browse/AUT-2137
Version mismatch for May release.
**SETPS to test:**
• Checkout to branch: fix/AUT-2137/incorrect-release-version-displayed-in-footer
• Check date on Footer version.
**Current behavior:**
Footer displays 2022.01 (January release)
**Expected behavior**
Footer should display  2022.05 (May) release like below.

fix: release version corrected for May

---

models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php

**Associated Jira issue:** [ADF-1054](https://oat-sa.atlassian.net/browse/ADF-1054)
This PR updates the tao-core branch used for the June release to include the fix in the query used to count items for remote lists.
- The branch is referenced here: https://github.com/oat-sa/tao-community/blob/release-2022-06/composer.json#L35
- Former PR for the develop tao-core branch here: https://github.com/oat-sa/tao-core/pull/3523/files

fix: Backport fix for ADF-1054 (element counting for remote lists)

---

composer.json

Fixing issue: https://oatsa.slack.com/archives/CHV6WAE90/p1655210839713339

chore: bump to safe guzzlehttp/guzzle version

---

composer.json
install/class.Installator.php
scripts/taoUpdate.php

When TAO instance is recreated and `taoUpdate.php` gets called, any migration trying to access DI container will fail with an error of missing cache directory. This change ensures the directory is present  
Related to : https://oat-sa.atlassian.net/browse/REL-783
Requires :

fix: check application cache directory during update

---

views/build/package-lock.json
views/build/package.json

Fix a regression that prevented to bundle due to a change in Babel and an [issue](https://github.com/babel/minify/issues/1028) on their side.
- `cd views/build`
- `npm ci`
- `npx grunt taobundle` 
You shouldn't have errors due to `this` or `self`

fix: update babel and grunt-tao-bundle

---

views/js/uiForm.js

This PR aims to fix the condition that currently prevents a resource form initialization when a currently handled ajax request URI has the word `authoring` within it. Apparently, that was done to suppress some initialization errors on the Item and Test authoring screens.
Below, you can see a proof that the form initialization would resolve the issue.
https://user-images.githubusercontent.com/2943256/183646666-7d82b5f8-89d9-4ca6-bbd9-db5c11e0942c.mov
#3347 
1. Have TAO 3.x running under a domain name with `authoring` in its name
2. Open a Delivery form
3. Save it

Fix TR-4529 impossible to edit a Delivery form

---

.github/workflows/continuous-integration.yaml
models/classes/AdvancedSearch/AdvancedSearchChecker.php
models/classes/search/SearchProxy.php
models/classes/search/tasks/UpdateDataAccessControlInIndex.php
scripts/update/Updater.php
test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
test/unit/models/classes/search/tasks/UpdateDataAccessControlInIndexTest.php

https://oat-sa.atlassian.net/browse/ADF-1163
- Make tao-core not use the ElasticSearch library anymore
- Use the new taoAdvancedSearch implementation instead
- https://github.com/oat-sa/extension-tao-advanced-search/pull/65

feat: add support for service from container for advanced search

---

actions/form/class.Instance.php
models/classes/controllerMap/ActionDescription.php
models/classes/mvc/error/HtmlResponse.php

**Associated Jira issue:** [ADF-1146](https://oat-sa.atlassian.net/browse/ADF-1146)
This fix enables sharing the `@requiresRight` cache between `ActionDescription` instances while keeping track about which method the cached data belongs to, so it avoids using permissions stored previously for a different action in later calls.
There are also two small changes introduced while debugging to avoid errors when running TAO in PHP 8:
- A deprecated warning when calling `strlen()` with a `null` value.
- A warning when no HTTP Referer header is present that may end up polluting the HTML output if E_ALL is enabled
Related PR: https://github.com/oat-sa/extension-tao-item/pull/595 (it has been closed, as this fix in tao-core alone solves the issue)

fix/ADF-1146: Distinguish which method requiresRight cached data belongs to

---

actions/class.Import.php

The purpose of action is to run the task so FE component is expecting a json response with a task report which is missing due to the condition, so if generic form validation fails nothing happening. 
This is a quick fix that allows user to see errors instead of blank screen, but we need a separate FE+BE task to add a proper validation messages in CSV import forms, cause it is missing seems from very beginning

fix: unexpected form response

---

views/package-lock.json
views/package.json

Related to styleManager issues fixes:  bump npm package to include fix for  [icons in media player not displaying]
[AUT- 2654](https://oat-sa.atlassian.net/browse/AUT-2654)
**Steps to check;**
- install npm pakage `tao-core-ui-fe`  new version `1.60.2`
**Expected behavior:**
- Package installs without any errors.
- Fix from package is present and Media player displays icons for play, stop, pause and music symbol correctly

fix: bump core-ui-fe lib to correct icon issue

---

composer.json

[ADF-1097](https://oat-sa.atlassian.net/browse/ADF-1097)
[ADF-1087](https://oat-sa.atlassian.net/browse/ADF-1087)
[ADF-1105](https://oat-sa.atlassian.net/browse/ADF-1105)
Make the extension not dictating PHP version to easier our PHP maintenance, since the extension does not work in isolation and PHP version should be equally respected to all TAO extensions.

PHP 8 migration

---

composer.json
helpers/form/validators/class.Integer.php
test/integration/ValidatorTest.php
test/unit/helpers/form/validators/IntegerValidatorTest.php

**Related ticket:** https://oat-sa.atlassian.net/browse/ADF-1145
Because of [difference in non-strict comparison behavior](https://onlinephp.io/?s=s7EvyChQKEssik8pzS3QMFCwtVVQUtK0BgA%2C&v=8.1.9%2C7.3.33) in PHP8, the validator does not pass empty string that way some form fields become "required" if the validator applied.
[Main fix](https://github.com/oat-sa/tao-core/pull/3599/files#diff-bb88207e6d211ad0bcc8edfd5e0163d7c6a3195c50030ea1b56b39cb27140e20R39) + [unit test](https://github.com/oat-sa/tao-core/pull/3599/files#diff-c61b9ddd5a635b286b109b90c381f049430ecba0bab4c1fe6887444963771cb4) 
Other not necessary changes are related to some old integration tests that was initially failing even on 7.3

[ADF-1145] fix integer form validator on PHP8

---

models/classes/search/ResultSetResponseNormalizer.php
test/unit/models/classes/search/ResultSetResponseNormalizerTest.php

https://oat-sa.atlassian.net/browse/ADF-1244
Make the view button disabled in case the resource has no read access for the user
- Disable read access for user in an item folder
- Login with the user without read access and search for the restricted item
- Check the button is disabled

fix: add ids to normalized so ACL is applied in the FE

---

helpers/form/class.Form.php
helpers/form/xhtml/class.Form.php
test/unit/helpers/form/FormContainerTest.php

Related to https://github.com/oat-sa/extension-tao-resource-workflow/pull/42
Assign resourceType attribute from an option passed from the resource edit form. This attribute may be used to define the initial state of the resource when not defined. 
How to reproduce:
- Ensure your instance has taoResourceWorkflow installed
- Create item with content
- Export Item
- Open another environment with taoResourceWorkflow installed
- Import item
- Ensure the item has initially stated and defined in the workflow

fix: pass option to element attribute for resource identification

---

views/js/layout/actions/common.js

When a user uses special characters for classes and tries to illegally move resources to classes that contain special characters, a warning message is broken. 
How to reproduce:
1. Create a class that contains special characters: i.e: æøå
2. Restrict class for the user so he will have only read access
3. Login as a restricted user 
4. Move resources to a restricted class
5. You should see the correct message without broken characters.

Fix/aut 38/disable htmlencoding in feedback

---

models/classes/http/ResponseEmitter.php

This PR changes the ResponseEmitter to replace new headers instead of duplicate them, because in some cases it could result in multiple `Content-Type` headers, that causes issues on the frontend side, because of the strict mime rules.

feat: changed ResponseEmitter to replace existing headers to avoid duplicates

---

views/package-lock.json
views/package.json

Ticket: https://oat-sa.atlassian.net/browse/AUT-1010
- Update tao-core-sdk to 1.23 - Add fallback for new BE error response
- https://github.com/oat-sa/tao-core-sdk-fe/pull/166
- https://github.com/oat-sa/extension-tao-testqti-previewer/pull/187

feature: update tao-core-sdk to 1.23

---

models/classes/event/DataAccessControlChangedEvent.php
models/classes/listener/DataAccessControlChangedListener.php
models/classes/taskQueue/Worker/AbstractWorker.php
test/unit/model/listener/DataAccessControlChangedListenerTest.php
test/unit/model/taskQueue/Worker/AbstractWorkerTest.php

**Associated Jira issue:** [ADF-1320](https://oat-sa.atlassian.net/browse/ADF-1320)
Changes in this PR introduce a new flag `applyToNestedResources` in `DataAccessControlChangedEvent` that, when is set, makes `DataAccessControlChangedListener` skip updates in search indexes for the class (previously that was the case when passing the recursive flag instead).
As part of this change, this PR updates unit tests to take into account that change and makes modified files to comply with PSR-12 (preventing validation errors in the pipelines).
Related PRs:
- https://github.com/oat-sa/extension-tao-dac-simple/pull/211
- https://github.com/oat-sa/extension-tao-advanced-search/pull/91
[ADF-1320]: https://oat-sa.atlassian.net/browse/ADF-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

feat: Extend DataAccessControlChangedEvent to support updates skipping nested resources

---

composer.json

Fix generis dependency for release-50.24.5
Error:
```
Error: Your requirements could not be resolved to an installable set of packages.
Problem 1
- oat-sa/tao-core v50.24.5 requires oat-sa/generis dev-php8-migration as v16.0.0 -> found oat-sa/generis[dev-fix/resource_tostring_do_not_add_label, ..., dev-prototype/spanner-schema, v0.6.1, 2.7-beta, ..., v2.31.6, v3.0.5, ..., v3.37.0, v4.0.0, ..., v4.4.2, v5.2.0, ..., v5.13.0, v6.1.0, ..., v6.18.0, v7.1.1, ..., v7.14.2, v8.1.0, ..., v8.4.0, v9.0.4, v9.0.6, v9.1.0, v10.0.0, v10.1.0, v10.1.0.1, v11.3.1, ..., v11.6.0.1, v12.0.0, ..., v12.33.2, v13.1.0, ..., v13.14.1, v14.0.0, ..., v14.4.0, v15.0.0, ..., v15.23.1] but it does not match the constraint.
- oat-sa/lib-tao-elasticsearch[v2.5.1, ..., v2.5.2] require oat-sa/tao-core …
```

chore: fix generis dependency for release-50.24.5

---

manifest.php

just bump up manifest version before creating stabilization branch

chore: bump up TAO_VERSION to 2023.05

---

scripts/tools/migrations/TaoComparator.php
test/unit/scripts/tools/migrations/TaoComparatorTest.php

In the qtiItemPci extension according to camel case class name rules, we changed migration names that did not match to regex used to sort migrations. 
- Version202209131056091465QtiItemPci.php
- Version202209141533261465QtiItemPci.php
- Version202211031046021465QtiItemPci.php
This fix will match those migrations and order them in the correct way.

fix: Change regex to accept CamelCase Migration Names

---

models/classes/resources/Service/ClassMover.php
test/unit/models/classes/resources/Service/ClassMoverTest.php

**Associated Jira issue:** [AUT-3113](https://oat-sa.atlassian.net/browse/AUT-3113)
Fixes a call to `EventManager::trigger()` so it provides a proper event instance instead of just the event name.
This is needed so the event carries the URI for the moved class: AdvancedSearch expects the event to be a `ClassMovedEvent` for that purpose [here](https://github.com/oat-sa/extension-tao-advanced-search/blob/master/model/Metadata/Listener/ClassMovedListener.php#L41).
<details>
<summary>Result for unit tests</summary>
```
root@0c0fdaa88445:/var/www/html# vendor/bin/phpunit tao/test/unit/
PHPUnit 8.5.33 by Sebastian Bergmann and contributors.
.............................................................   61 / 1694 (  3%)
.............................................................  122 / 1694 ( …
```

fix: Fix call to EventManager::trigger()

---

actions/class.Main.php

This change will allow disabling all navigation buttons using the feature flag with SectionVisibilityFilter config. 
How to use: 
- Create migration that will add desired section (perspective) to be disabled base on feature flag
- Define feature flag
- Clear cache

Fix/solar 270/allow section visibility filter apply on get navigation elements by group

---

composer.json
migrations/Version202306211310042234_tao.php
models/classes/Language/Listener/LanguageCacheWarmupListener.php
models/classes/LanguageServiceProvider.php
models/classes/featureFlag/FeatureFlagServiceProvider.php
models/classes/featureFlag/Listener/FeatureFlagCacheWarmupListener.php
models/classes/menu/Listener/MenuCacheWarmupListener.php
models/classes/menu/MenuServiceProvider.php
models/classes/routing/Listener/AnnotationCacheWarmupListener.php
models/classes/routing/ServiceProvider/RoutingServiceProvider.php
scripts/install/RegisterEvents.php
test/unit/models/classes/Language/Listener/LanguageCacheWarmupListenerTest.php
test/unit/models/classes/featureFlag/Listener/FeatureFlagCacheWarmupListenerTest.php

Premium EC2 instances are recycled every night. This clears the application cache and results in slow first requests until the cache is refilled. The purpose of this PR is to implement a solution for warming up the cache after the instance refresh to improve the performance of the first requests.
- feat: add new command which allow to warmup of the application cache.
You can run following command to execute  command. `--clear` flag clens up cache before warming it up and can be useful in case of issues or interrupted execution of previous command
```bash
php index.php 'oat\generis\scripts\tools\ApplicationCacheWarmup' --clear
```
- https://github.com/oat-sa/generis/pull/1051

feature/REL 985/application cache warmup after instance refresh

---

migrations/Version202307101518342234_tao.php
models/classes/TaoOntology.php
models/ontology/tao.rdf
scripts/tools/MigrateSqlToNeo4j.php
scripts/tools/export/RDF/ExportRdfStructure.php

As a part of effort to develop RDF persistence in neo4j, we need a procedure to migrate RDF data from SQL database (mysql or postgresql) to neo4j.
- feat: RDF migration from sql to neo4j 
```bash
php -dmemory_limit=1G index.php 'oat\tao\scripts\tools\MigrateSqlToNeo4j' -u -i -s 10000 -n 10000 -vvvv
```
- https://github.com/oat-sa/generis/pull/1054
- https://github.com/oat-sa/extension-tao-testcenter/pull/194

Feature / REL-1170 / Migration from sql to neo4j

---

models/classes/resources/CopierServiceProvider.php

https://oat-sa.atlassian.net/browse/ADF-1545
We need to fix the possibility of copying already copied classes.
How to test:
1. Go to items and create a new folder/class
2. Copy this class
3. Try to copy the folder you got in step 2
**After switching to the new version cache should be deleted to generate a new DI cache**

fix: fix copy of copied classes

---

models/classes/taskQueue/Queue.php
models/classes/taskQueue/Queue/Broker/AbstractQueueBroker.php
models/classes/taskQueue/Queue/Broker/QueueBrokerInterface.php
models/classes/taskQueue/QueueDispatcher.php
models/classes/taskQueue/QueueInterface.php
models/classes/taskQueue/QueuerInterface.php
models/classes/taskQueue/Worker/AbstractWorker.php

* Added method `hasPreFetchedMessages(): bool` to `AbstractQueueBroker` and related interface
* Added method `hasPreFetchedMessages(): bool` to `Queue` and related interface
* https://github.com/oat-sa/extension-tao-task-queue/pull/169
[ADF-1571]: https://oat-sa.atlassian.net/browse/ADF-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feature] Method to check if there are pre-fetched tasks

---

actions/class.ExtensionsManager.php
composer.json
install/class.Installator.php
scripts/installExtension.php
scripts/taoUpdate.php
scripts/uninstallExtension.php
scripts/update/MigrateWebhooksConfigsFromFileToRdf.php

Using another function to rebuild DI container.
Related to : https://oat-sa.atlassian.net/browse/REL-1275
Requires :

feat: use new container rebuild function that restarts as well

---

helpers/data/class.GenerisAdapterRdf.php
migrations/Version202309111518342234_tao.php
scripts/tools/MigrateSqlToNeo4j.php
scripts/update/OntologyUpdater.php

Rdf export/import from neo4j
- feat: ontology import/export for neo4j.
1. Install / Update platform
2. Migrate data to Neo4J
2. Change one of RDFs
3. Create Sync Ontology migration and run it
- https://github.com/oat-sa/extension-tao-outcome/pull/263
- https://github.com/oat-sa/extension-tao-testqti-previewer/pull/201
- https://github.com/oat-sa/extension-tao-proctoring/pull/952
- https://github.com/oat-sa/generis/pull/1068

REL-1197: Rdf export/import from neo4j

---

models/classes/Lists/Business/Contract/ValueCollectionRepositoryInterface.php
models/classes/Lists/Business/Domain/Value.php
models/classes/Lists/Business/Domain/ValueCollectionSearchRequest.php
models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
test/unit/models/classes/Lists/DataAccess/Repository/QueryStub.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

List value URIs can be modified via user interface. Yet implementation is modifying SQL statements table directly, and would not work with neo4j RDF storage.
- feat: updated list find/persist functionality to use complex search functionality to fetch lists data.
Lists are used in many places but the easiest way to test them is lists settings page.
1. Login to TAO Authoring / Studio
2. Open /tao/Main/index?structure=settings&ext=tao&section=taoBo_list
3. Try to create/update/delete lists and lists values.
- https://github.com/oat-sa/lib-generis-search/pull/32
- https://github.com/oat-sa/generis/pull/1075

REL-1198: List value URI definition should work with neo4j RDF storage.

---

models/classes/taskQueue/Queue.php
test/unit/model/taskQueue/QueueTest.php

- Fixed return type of oat\tao\model\taskQueue\Queue::count(): int
- Run worker process
- Watch logs:
`tail -f /var/www/html/tao.log`
- No errors should be visible in logs:
`Return type of oat\tao\model\taskQueue\Queue::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

fix: return type of oat\tao\model\taskQueue\Queue::count() should be int

---

views/build/package-lock.json
views/build/package.json

Ticket: https://oat-sa.atlassian.net/browse/ADF-1587
- Removed vulnerability of `minimist` package in views/build folder
- Removed `sass-lint` dependency as the latest version contains vulnerability and I didn't find usage of it
- Used node v.16 as `grunt@1.6.1` requires node >=16 (see https://github.com/gruntjs/grunt/blob/v1.6.1/package.json#L10)
- Check code still works

fix: remove minimist vilnerability

---

migrations/Version202312081310042234_tao.php
models/classes/listener/ClassPropertyRemovedListener.php

Ticket - https://oat-sa.atlassian.net/browse/REL-1376
Fix the issue when we try to delete the delivery
- fix: fix on property remove cache clear
- As admin go to the Deliveries tab
- Select any delivery in the tree
- Click  Delete and confirm

fix: internal server error is appearing when removing deliveries

---

actions/class.File.php

Fixing a phpdoc block that prevents cache warmup.
Related to : https://oat-sa.atlassian.net/browse/REL-985
Without the fix, phpdoc parser throws an error like:
```
Unexpected token "{", expected type at offset 0 on line 1
```
- Run `php index.php 'oat\generis\scripts\tools\ApplicationCacheWarmup'`
- Observer an error message `Cache warmup failed: Unexpected token "{", expected type at offset 0 on line 1`
To test, run the cache warmup command and get the `TAO cache warmed up!` report.

Fix/rel 1418/fix phpdoc blocking cache warmup

---

locales/cy-GB/lang.rdf
locales/en-CA/lang.rdf
locales/es-CO/lang.rdf
migrations/Version202402061413282234_tao.php

This PR adds values for _data_ (items, tests) localization.
For the moment, the locales will be applied to the actual environment manually via https://oat-sa.atlassian.net/browse/OSD-4736. This migration will then simply have no effect on the data on that particular environment.
1. `php tao/scripts/taoUpdate.php`
2. Author an Item via TAO 3.x
3. Observe the `Languages` drop down options in the right-hand side panel
[OAP-10]: https://oat-sa.atlassian.net/browse/OAP-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add `cy-GB`, `en-CA` and `es-CO` _data_ locales

---

helpers/class.Date.php
test/unit/helpers/DateTest.php

BACKPORT of https://github.com/oat-sa/tao-core/pull/3932
* fix: refactor and move format function to Date helper, pass deliveryExecution->getFinishTime() on delivery finish
* feat: add unit test
* feat: add unit test
* fix: codestyle
* fix: add new data
(cherry picked from commit 3c01dcf943eb64dc7cf36cc4ef5b3d45728349a3)

Add format microtime() to DateTimeInterface::RFC3339_EXTENDED function (#3928)

---

migrations/Version202402086838312237_tao.php
scripts/install/RegisterEvents.php

Related to - [https://oat-sa.atlassian.net/browse/ADF-1537](https://oat-sa.atlassian.net/browse/ADF-1537)
Fix the issue when we try to delete the delivery
- fix: remove Property Deleted listener, because property cache clearing on the separated property delete
- As admin go to the Deliveries tab
- Select any delivery in the tree
- Click  Delete and confirm
https://github.com/oat-sa/tao-core/assets/10648378/06ed912d-13f6-4032-b474-7e10b93ea269
https://github.com/oat-sa/tao-core/assets/10648378/180922b8-f081-4c2c-8971-fe2a050c1a4f

ADF-1537: internal server error appearing when delivery is deleted

---

models/classes/security/Business/Domain/Key/Key.php
models/classes/security/Business/Domain/Key/KeyChainCollection.php
test/unit/models/classes/security/Business/Domain/Key/KeyChainCollectionTest.php
test/unit/models/classes/security/Business/Domain/Key/KeyTest.php

https://github.com/oat-sa/extension-tao-lti/pull/398

feat: publish to two solar tenants

---

helpers/Layout.php
test/unit/helpers/LayoutTest.php
views/templates/layout.tpl

This PR aim to address issue with rendering of GA tag in some environments
- fixed usage of deprecated sort tag `<? ?>` (which at least on `uat.eu.premium.lab.taocloud.org` converted into html comment)
- used `$_ENV` instead of `getenv` (usage of which [discouraged](https://github.com/vlucas/phpdotenv?tab=readme-ov-file#putenv-and-getenv) by dotenv lib documentation )
[TR-6036]: https://oat-sa.atlassian.net/browse/TR-6036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix google tag rendering

---

actions/class.RdfController.php
actions/form/class.Clazz.php
actions/form/class.EditClassLabel.php
migrations/Version202403072011000000_tao.php
models/classes/dataBinding/class.GenerisInstanceDataBinder.php
test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php

This PR aims to avoid saving/duplicating system properties from UI
How to test:
- Install recent TAO release with test-centers extension
- Select Test-taker root class
- Submit edit from or submit schema (properties) form
- Create test-center
- See duplicates as described [in the ticket](https://oat-sa.atlassian.net/browse/AUT-3552)
- Switch tao-core to this PRs branch and run taoUpdate
- Ensure that the duplicate has gone
- Submit forms related Test-taker root class as before
- Check that the duplicates do not appear anymore
- Check that other properties (which form inputs are not disabled) still editable from UI

AUT-3552 fix: do not duplicate read only labels (model 2)

---

README.md
helpers/Layout.php
models/classes/featureFlag/FeatureFlagCheckerInterface.php
models/classes/theme/ConfigurablePlatformTheme.php
models/classes/theme/ConfigurableTheme.php
models/classes/theme/SolarDesignCheckerInterface.php
models/classes/theme/SolarDesignCheckerTrait.php
models/classes/theme/ThemeService.php
views/templates/layout.tpl

Add a feature flag to enable the Solar Design to the authoring.
Feature flag for activating the solar design system: `FEATURE_FLAG_SOLAR_DESIGN_ENABLED`
The feature flag will be activated with:
```sh
php index.php 'oat\tao\scripts\tools\FeatureFlag\FeatureFlagTool' -s FEATURE_FLAG_SOLAR_DESIGN_ENABLED -v true
```
Once activated, the CSS class `solar-design` is added to the body element of the page.
- check out the branch: `git checkout -t origin/feature/AUT-3626/feature-flag-for-solar-design`
- activate the feature flag: `php index.php 'oat\tao\scripts\tools\FeatureFlag\FeatureFlagTool' -s FEATURE_FLAG_SOLAR_DESIGN_ENABLED -v true`
- log in to TAO backoffice
- open the browser dev tools, and check that the body element received the CSS class `solar-design`

Feature/AUT-3626/Feature flag to enable the Solar Design

---

models/classes/action/ActionBlackList.php
test/unit/models/classes/action/ActionBlackListTest.php

This PR aims to add ability to enable disabled action by feature flag.
How to test:
```php
return new oat\tao\model\action\ActionBlackList(array(
'disabledActions' => array(
'action-name'
),
'enabledActionsByFeatureFlagMap' => array(
'action-name' => 'FEATURE_FLAG_THAT_ENABLES_ACTION_NAME'
)
));
```
- Add some action id in a list of `disabledActions` in  `config/tao/ActionBlackList.conf.php` as above
- Validate that action button is **not visible** in TAO3.x UI (existing functionality)
- Add a map pair into `enabledActionsByFeatureFlagMap` in the same conf file
- Set the chosen environment variable to `true`; validate that action button is **visible**
- Set the chosen environment variable to `false`; validate that action button is **not visible**

feat: enable disabled actions by feature flags

---

actions/class.Main.php

This is required to keep logout button when no children are included in User Settings.

fix: keep empty element when no children defined as user_settings

---

views/package-lock.json
views/package.json

https://oat-sa.atlassian.net/browse/TR-6195
Goal: TAO 3.x still working
- `tao-core-sdk` changes: https://github.com/oat-sa/tao-core-sdk-fe/pull/187
- local `oat-sa-tao-core-sdk-3.1.2.tgz` must be removed before merge
Deployed to: https://test-tr-6195-authoring.v3.playground.taocloud.org/

Fix/TR-6195/Upgrade tao-core-sdk

---

views/templates/blocks/portal/back-button.tpl

This PR removes the not-needed "Content Bank" title from TAO 3.x' nav bar when launched via TAO Portal.
|Before|After|
|-|-|
|<img width="719" alt="image" src="https://github.com/user-attachments/assets/e1e9586a-6f87-48b8-bc6f-1fd8d5d8baa0">|<img width="719" alt="image" src="https://github.com/user-attachments/assets/68c866d6-8426-4ee9-a62a-ebfb5fbfae1c">|
[ADF-1727]: https://oat-sa.atlassian.net/browse/ADF-1727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove the extra "Content Bank" title from the nav bar

---

actions/class.TaskQueueWebApi.php
migrations/Version202409301236442234_tao.php
models/classes/taskQueue/TaskLogInterface.php
scripts/install/RegisterTaskQueueServices.php

'php error(1) in /var/www/html/tao/tao/models/classes/taskQueue/TaskLog/Entity/TaskLogEntity.php@120: Allowed memory size of 536870912 bytes exhausted
During archiving a lot of tasks we may have the issue on the PHP side about memory size. For fixing that we will add updating by using batch size.
How to test:
1. Create a few tasks
2. Try to archive them
Deployed on unit07

Fix/aut 3877/archive tasks

---

models/classes/Translation/Service/ResourceTranslationRetriever.php
views/js/services/translation.js

Add support for querying multiple resources when listing the translations.
The `id` parameter can now accept an array of URI. In this case, the language URI is necessary.

Feature/adf 1789/side by side authoring

---

models/classes/resources/Service/ClassMetadataCopier.php
test/unit/models/classes/resources/Service/ClassMetadataCopierTest.php

do not duplicate property's alias

fix: class copy duplicates properties with same alias

---

manifest.php

https://oat-sa.atlassian.net/browse/ADF-1823
- Translation access is give to GlobalManager during installation

fix: add missing access to global manager

---

models/classes/GenerisTreeFactory.php

- In case class is root class, use this to filter out translations

fix: root class must be retrieved if root class

---

views/package-lock.json
views/package.json

Ticket: https://oat-sa.atlassian.net/browse/LSI-5002
- Fixed the issue when user is not able to download the PDF generated from booklet
- In the Tests tab, select a test
- Click “New booklet” button
- Click “Generate”
- In the Background tasks, find the task with generated booklet
- Click “Download” icon
- The booklet should be downloaded successfully

fix: booklet download from tasks queue

---

models/classes/Translation/Service/TranslatedIntoLanguagesSynchronizer.php
models/classes/dataBinding/class.GenerisInstanceDataBinder.php
test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php

https://oat-sa.atlassian.net/browse/ADF-1855
Allow callbacks to be executed for original test after sync it
- https://github.com/oat-sa/extension-tao-test/pull/495

fix: update original test after sync metadata

---

helpers/Layout.php
models/classes/menu/Action.php
views/templates/blocks/actions.tpl

Ticket: [AUT-3938](https://oat-sa.atlassian.net/browse/AUT-3938)
Connected PRs:
oat-sa/extension-tao-deliver-connect: [#250](https://github.com/oat-sa/extension-tao-deliver-connect/pull/250)
oat-sa/extension-tao-delivery-rdf: [#496](https://github.com/oat-sa/extension-tao-delivery-rdf/pull/496)
oat-sa/extension-tao-testtaker: [#248](https://github.com/oat-sa/extension-tao-testtaker/pull/248)
oat-sa/extension-tao-item: [#671](https://github.com/oat-sa/extension-tao-item/pull/671)
oat-sa/extension-tao-itemqti: [#2643](https://github.com/oat-sa/extension-tao-itemqti/pull/2643)
oat-sa/extension-tao-group: [#187](https://github.com/oat-sa/extension-tao-group/pull/187)
oat-sa/extension-tao-test: [#494](https://github.com/oat-sa/extension-tao-test/pull/494)
oat-sa/extension-tao-backoffice: …

[AUT-3938]: Weight attribute handling for actions lists

---

models/classes/dataBinding/class.GenerisInstanceDataBinder.php

Fix next error during saving settings after implementing ADF-1855
`ERROR] [tao] 'php error(1) in /var/www/html/tao/tao/models/classes/dataBinding/class.GenerisInstanceDataBinder.php@195: Uncaught Error: Call to a member function getUri() on null in /var/www/html/tao/tao/models/classes/dataBinding/class.GenerisInstanceDataBinder.php:195
`
How to test:
1. Open user setting page
2. Press save
https://github.com/user-attachments/assets/199c4910-bf38-412a-8d34-0abbfce5fde5

fix: update user setting

---

views/templates/blocks/sections.tpl

[AUT-4059](https://oat-sa.atlassian.net/browse/AUT-4059)
Subheading with typos is removed
[AUT-4059]: https://oat-sa.atlassian.net/browse/AUT-4059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AUT-4059] fix: removing subheading with typo from items tree

---

views/scss/inc/_action-bars.scss

[AUT-4070](https://oat-sa.atlassian.net/browse/AUT-4070)
Fix for redundant grey border in right of tree section
[AUT-4070]: https://oat-sa.atlassian.net/browse/AUT-4070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AUT-4070] fix: fix redundant grey space in tree section

---

views/templates/blocks/header-main-navi.tpl

[AUT-4071](https://oat-sa.atlassian.net/browse/AUT-4071)
Fix for labels duplications on mobile view of setting menu.
[AUT-4071]: https://oat-sa.atlassian.net/browse/AUT-4071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AUT-4071] fix: fix for labels duplication in mobile view

---

views/templates/blocks/portal/back-button.tpl

To fix issue:
When login via LTI by a user who does not have a name set in platform, we see logo instead of back button

fix: back to platform button

---

models/classes/Translation/Event/TranslationActionEvent.php
models/classes/Translation/Service/TranslationCreationService.php
models/classes/Translation/Service/TranslationDeletionService.php
models/classes/Translation/Service/TranslationUpdateService.php
models/classes/Translation/ServiceProvider/TranslationServiceProvider.php
test/unit/models/classes/Translation/Event/TranslationActionEventTest.php
test/unit/models/classes/Translation/Service/TranslationCreationServiceTest.php
test/unit/models/classes/Translation/Service/TranslationDeletionServiceTest.php
test/unit/models/classes/Translation/Service/TranslationUpdateServiceTest.php

* Added new event to cover translation actions:
* Create
* Update
* Delete
* New event is triggered in related services to create/update/delete a translation
* New event will share the following information:
* Action (create/update/delete)
* Original resource URI
* Translation resource URI
* Locale code
* Additional data, e.g. changed properties (old -> new)
[ADF-1851]: https://oat-sa.atlassian.net/browse/ADF-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: extend event logs

---

models/classes/Translation/Service/TranslationUniqueIdSetter.php
test/unit/models/classes/Translation/Service/TranslationUniqueIdSetterTest.php

* Keep the same QTI identifier for translations even if unique ID feature flag disabled
1. Disable `FEATURE_FLAG_UNIQUE_NUMERIC_QTI_IDENTIFIER` feature flag
2. Enable `FEATURE_FLAG_TRANSLATION_ENABLED` feature flag
3. Create new Item/Test
4. Add some content
5. Mark Item/Test as `Ready for translation`
6. Translate Item/Test
7. Compare original and translation QTI IDs
* Previous behaviour: QTI ID is different
* New behaviour: QTI ID is the same
* https://github.com/oat-sa/extension-tao-itemqti/pull/2687
* https://github.com/oat-sa/extension-tao-testqti/pull/2579
[AUT-3772]: https://oat-sa.atlassian.net/browse/AUT-3772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] Keep translation QTI ID the same

---

.github/workflows/continuous-integration.yaml
.github/workflows/sonar.yml
models/classes/Translation/Service/TranslationMoveService.php
models/classes/Translation/ServiceProvider/TranslationServiceProvider.php
models/classes/resources/CopierServiceProvider.php
models/classes/resources/Service/InstanceMover.php
test/unit/models/classes/Translation/Service/TranslationMoveServiceTest.php
test/unit/models/classes/resources/Service/InstanceMoverTest.php

This aims to keep a test/item translations (hidden resources) together with origin resource when moving it to another class. This fixes the following case:
- Create item/test
- Create a translation
- Move the origin item/test to another class
- Remove the first class (it looks empty but actually it is not due to the translation implementation)
- Check that the translations for the moved items/resource is not lost anymore

fix: move translations together with a resource

---

models/classes/resources/ResourceWatcher.php

This will prevent loosing events for indexUpdate. This change will cause the index update logic to run every time the method is called, regardless of whether the resource was actually updated recently or not.

fix: remove condition for event aggregation

---

models/classes/resources/ResourceWatcher.php
test/unit/models/classes/resources/ResourceWatcherTest.php

We found that during updating we also try to update the updatedAt which will also trigger onUpdate event which will be collected by the Event Aggregator
https://github.com/oat-sa/tao-core/blob/v54.39.2/models/classes/resources/ResourceWatcher.php#L95
How to test:
1. Update any resource and check that updatedAt was updated with the current timestamp
2. Import any test and check that we have only needed number of index tasks in task queue

fix: move updating updated_at to the generis during global onUpdate

---

views/js/uiForm.js

https://oat-sa.atlassian.net/browse/HKD-763
- remove `interactionsource` and `sourcedialog` buttons from item property editor
> Please tick the appropriate points
- Enable `interactionsource` and `sourcedialog` via FF `FEATURE_FLAG_CKEDITOR_SOURCEDIALOG` and `FEATURE_FLAG_CKEDITOR_INTERACTION_SOURCE`
- Go to Item schema and add property with Text Html Editor type
- Observe there is no additional buttons
- Go to item Authoring and buttons are there like should be
https://github.com/user-attachments/assets/3f792cb3-d422-4969-b0c1-e031760c0df9

fix: remove interactionsource and sourcedialog buttons from item property editor
