oat-sa/tao-core

helpers/MediaRetrieval.php
views/js/ui/resourcemgr/filePreview.js
views/js/ui/resourcemgr/fileSelector.js
views/js/ui/resourcemgr/tpl/fileSelect.tpl

https://github.com/oat-sa/extension-tao-itemqti/pull/45

Media retrieval

---

views/js/ui/resourcemgr/filePreview.js
views/js/ui/resourcemgr/fileSelector.js
views/js/ui/resourcemgr/tpl/fileSelect.tpl

https://github.com/oat-sa/extension-tao-itemqti/pull/44

add the alt text on file selection

---

helpers/form/class.GenerisFormFactory.php
helpers/form/elements/class.GenerisAsyncFile.php

depends on https://github.com/oat-sa/generis/pull/21

Use generis file widget in generated forms

---

actions/class.Main.php
models/classes/accessControl/class.AclProxy.php

Prevents redirects to shady urls outside of tao and redirects to actions the new user has no access to

Only redirect if user has access

---

models/classes/media/MediaBrowser.php
views/js/ui/resourcemgr/fileBrowser.js

allow subtree close only if the root is already selected

highlight the right root in filebrowser

---

views/js/controller/settings/extensionManager.js

Fixed css class of newly installed extension entries

---

models/classes/media/MediaManagement.php

will require a merge into zendSearch as well

Changed upload to add in media managerment

---

install/class.ExtensionInstaller.php

depends on https://github.com/oat-sa/generis/pull/39

refactoring of langpacks installation

---

views/js/lib/qunit/qunit-assert-close.js

Is required for oat-sa/extension-tao-itemqti#129

mathOperator  introduced TAO-415

---

actions/form/class.Users.php
install/ontology/superuser.rdf
manifest.php
models/classes/accessControl/func/implementation/SimpleAccess.php
models/ontology/tao.rdf
scripts/update/Updater.php

depends on https://github.com/oat-sa/extension-tao-funcacl/pull/6
depends on https://github.com/oat-sa/generis/pull/43

Restructured abstract and worker roles

---

manifest.php
scripts/update/OntologyUpdater.php

depends on https://github.com/oat-sa/generis/pull/47 and https://github.com/oat-sa/extension-tao-workspace/pull/1

Reversed rdf_diff application

---

views/templates/footer.tpl

Fix messages with a quotes crashing the app.

encode messages in footer

---

views/js/ui/ckeditor/ckConfigurator.js
views/js/ui/ckeditor/dtdHandler.js

Depends on https://github.com/oat-sa/extension-tao-itemqti/pull/167

centralize ckeditor configuration

---

views/js/ui/feedback.js
views/js/util/wrapLongWords.js

tao-576, for testing refer to readme in JIRA comment.
Also added license. Could not make JSHint compliant, see inline comments

Tao 576 feedback overflow

---

helpers/translation/class.POExtractor.php
helpers/translation/class.StructureExtractor.php
scripts/class.TaoTranslate.php
views/templates/blocks/actions.tpl

+ Structure extraction fixed.
+ More logs in taoTranslate script.
+ Fix actions.tpl template to show translated strings.

Structure extraction of translations are now all flagged public.

---

views/js/util/regexEscape.js
views/js/util/wrapLongWords.js

Use when concatenating a string for usage in new RegExp().

Escapes -\/\\^$*+?.()|[\]{} inside a string

---

views/js/layout/tree.js

I need to execute action after tree initialized.
`structures.xml` example:
```
<trees>
<tree name="My library"
initTree="init-tree"
/>
</trees>
<actions>
<action id="init-tree" name="init" url="/myExt/MyController/index">
</action>
...
```

add initTree action

---

views/js/uiForm.js

will require major refactoring in the future

Ensure uiForm js is included on PropertiesAuthoring

---

views/js/test/util/url/test.html
views/js/test/util/url/test.js
views/js/urlParser.js
views/js/util/url.js

Create a util to parse URLs from strings and extract infos.

Js url util

---

views/build/config/requirejs.build.js
views/build/config/requirejs.test.json

replicate history.js aliases in build configs

fix history path

---

actions/class.RdfController.php

Order only arrays where keys are integers.

order only indexed arrays

---

views/js/ui/ckeditor/ckConfigurator.js
views/js/ui/ckeditor/dtdHandler.js

requires:
- https://github.com/oat-sa/extension-tao-testqti/pull/59
- https://github.com/oat-sa/extension-tao-itemqti/pull/264

Tao 749 separate ckeditor from math jax in extended text interaction

---

manifest.php

Conflicts:
manifest.php
related to https://github.com/oat-sa/tao-core/pull/339

Removed outdated write requirements

---

helpers/form/class.FormElement.php
helpers/form/elements/xhtml/class.Textbox.php

cherry pick off https://github.com/oat-sa/tao-core/pull/352
fix on master @llecaque

Prevent 500 on multiple formelement classes

---

views/js/test/lib/history/test.js

Fix issue in URL matching when non standard port is used

Fix TU for lib/history

---

views/js/ui/themes.js

To get access to the configured themes.
Requires https://github.com/oat-sa/extension-tao-itemqti/pull/295 to be merge in order to work

theme config

---

views/js/layout/tree.js

Fix:
- https://oat-sa.atlassian.net/browse/TAO-784
- https://oat-sa.atlassian.net/browse/TAO-763

Tao 784 indexed search bug when opening a result

---

test/CSVMappingFormTest.php

Related to [TAO-835](https://oat-sa.atlassian.net/browse/TAO-835)
and pr https://github.com/oat-sa/tao-core/pull/368

Unit test for csv import form mapping

---

views/js/ui/resourcemgr/fileSelector.js

https://github.com/oat-sa/extension-tao-item/pull/110

TAO-702 display error message to help user

---

views/js/iframeResizer.js

Iframe height

---

views/js/ui/contextualPopup.js

The path of the tpl has to be relative to the baseUrl in order to compile it into the bundles otherwise the bundling fails (see [last build](http://build.taotesting.com:8180/job/build-tao-js/196/console))

fix tpl path to be able to compile the bundles

---

models/classes/import/class.CSVMappingForm.php
test/CSVMappingFormTest.php
test/form/CsvMappingFormTest.php

I added some logic to CSVMappingForm, that check labels from csv file (imported) and existing properties and then try make selected same.
When user load file with labels it would be awesome set checked those which coincide.
Task: https://oat-sa.atlassian.net/browse/TAO-835

Imporove CVS mapping form class for make selected matched labels

---

models/classes/ThemeRegistry.php
test/ThemeRegistryTest.php

- improved ThemeRegistry test case: added tests for new features; added negative behavior tests
- fixed and improved ThemeRegistry: added some exceptions on Register and Unregister

improved ThemeRegistry test case: added tests for new features

---

views/js/core/promise.js
views/js/lib/polyfill/es6-promise.js

add es6 promises

---

views/templates/client_config.tpl

Make the timeout config available through context

add timeout in context

---

install/class.Installator.php

requires https://github.com/oat-sa/generis/pull/71

Split host:port to individual params

---

manifest.php
scripts/install/setDefaultTheme.php

Related: oat-sa/extension-tao-itemqti#368

Moved ThemeRegistry init on install to core extension

---

models/classes/ThemeRegistry.php
test/ThemeRegistryTest.php

added unregisterTheme()

---

views/js/lib/polyfill/performance-now.js

window.performance.now() polyfill

---

doc/structures.dtd
models/classes/menu/Section.php

depends on https://github.com/oat-sa/extension-tao-backoffice/pull/9 until menu services have been migrated to taoBackOffice

Allow to define actions by class

---

actions/class.Main.php
models/classes/menu/Action.php

depends on https://github.com/oat-sa/extension-tao-backoffice/pull/12

Use new action interface

---

actions/class.Export.php
actions/class.Import.php
actions/class.PropertiesAuthoring.php
actions/class.RdfController.php

requires https://github.com/oat-sa/extension-tao-dac-simple/pull/22

Full DAC on tao

---

views/js/uiForm.js

Restore the condition enabling the property adder on all properties authoring pages

Property add

---

views/js/test/ui/modal/modal.tpl
views/js/test/ui/modal/test.html
views/js/test/ui/modal/test.js
views/js/ui/modal.js

Add destroy method to modal
Add option: animate
Update events

Enhancements and refactoring of modal

---

views/js/core/databinder.js

Fix TAO-1270
To reproduce, create a new QTI test in the test authoring : 
1. 2 sections with 1 item each
2. Delete 1 item from each section
3. Delete one of the sections

prevent to resync when there's no element anymore

---

actions/class.Export.php
models/classes/export/interface.ExportHandler.php
views/templates/form/export.tpl

Rebased branch _export-failure_ for this PR https://github.com/oat-sa/tao-core/pull/454

Export failure rebased

---

views/js/test/util/adaptSize/test.html
views/js/test/util/adaptSize/test.js
views/js/util/adaptSize.js

Also some re-factoring, added unit test

moved taoQtiItem/qtiCreator/helper/adaptSize to tao

---

actions/class.Main.php
actions/form/class.Login.php
manifest.php
scripts/install/addLoginFormConfig.php
scripts/update/Updater.php

Master PR: oat-sa/extension-tao-delivery#100

TAO 1227:  added possibility to add custom elements to login form

---

views/js/layout/section.js

this one is required for https://github.com/oat-sa/extension-tao-item/pull/136

Added method to remove listeners from sections

---

helpers/Layout.php

fix getThemeTemplate() to return the base template when not found in the default one

fix the returned template

---

views/js/test/util/url/test.js
views/js/util/url.js

yet another util to build URLs

add a url builder util

---

views/js/serviceApi/ServiceApi.js

Please test if it doesn't break test taking (it shouldn't)
You can batch the tests with https://github.com/oat-sa/extension-tao-delivery/pull/108

fix unused dependency and minor styling

---

views/templates/client_config.tpl

Please cherry-pick it also to develop

configure the text plugin to use always xhr

---

includes/class.Bootstrap.php
install/class.Installator.php
install/init.php
models/classes/mvc/Bootstrap.php
scripts/regenerateGetFileConfig.php
scripts/resetRootPassword.php
scripts/taoInstall.php
scripts/taoUpdate.php

Core fix for https://oat-sa.atlassian.net/browse/TAO-1311

Set default timezone in bootstrap

---

install/js/step_licenses.js

installer: fix the licenses step blocking issue

---

views/js/layout/tree.js

Related to https://oat-sa.atlassian.net/browse/TAO-1515

Add check if data parameter is empty or undefined

---

views/js/core/validator/validators.js

this is what created "unkonw error" popups

do not abort request, they create anoying error messages

---

views/build/config/aws.json
views/build/grunt/s3.js
views/build/package.json

To upload resources : 
- `cd tao/views/build && npm install`
- update the file `tao/views/build/config/aws.json`
- run `grunt compress:s3 awsS3:upload`
**Please cherry pick this PR to dev-act**

enable to upload the assets on AWS s3

---

views/js/ui/resourcemgr.js
views/js/ui/resourcemgr/fileBrowser.js
views/js/ui/resourcemgr/tpl/layout.tpl
views/scss/inc/_resourcemgr.scss

Related to https://oat-sa.atlassian.net/browse/TAO-1495
Previous disscusion here https://github.com/oat-sa/tao-core/pull/571

Fixed styles for modal window in media manager

---

helpers/ControllerHelper.php
helpers/class.Uri.php
models/classes/accessControl/data/DataAccessControl.php

linked with https://github.com/oat-sa/extension-tao-funcacl/pull/22

Tao 1687/ontology perfomance fix

---

views/js/core/historyRouter.js
views/js/router.js

Added history router.
There's no test because mocking up the browser history doesn't really work (the actual test fails and will be removed)

create an history router

---

views/js/core/validator/validators.js
views/js/test/core/validator/validators/test.html
views/js/test/core/validator/validators/test.js

Fix `validators.register` and enable to force registration.
Tests have been added

fix and test validator registration

---

models/classes/mvc/Bootstrap.php
models/classes/search/RunIndexing.php

depends on https://github.com/oat-sa/generis/pull/120

Use action resolution

---

views/js/core/polling.js
views/js/test/core/polling/test.html
views/js/test/core/polling/test.js

Polling manager: execute action at interval with async mode.
Each iteration wait for the previous one to be executed.

add a polling manager with async mode

---

views/js/core/polling.js
views/js/test/core/polling/test.js

- promise is better handled as the post actions are now set directly at create time
- the next() method, when called, will wait for the promise if any
- added better state handling
- added missing tests

polling.js: improved version

---

views/js/serviceApi/ServiceApi.js

Related to:
- https://oat-sa.atlassian.net/browse/TAO-1775
- https://oat-sa.atlassian.net/browse/TAO-1773

ServiceApi: add exit action

---

helpers/class.Date.php
helpers/dateFormatter/EuropeanFormatter.php
helpers/dateFormatter/Formatter.php
helpers/dateFormatter/IntlFormatter.php
test/helpers/DateHelperTest.php

add milliseconds to formater

---

views/js/test/ui/themes/test.js
views/js/ui/themeLoader.js

related to https://github.com/oat-sa/extension-tao-itemqti/pull/489

TAO-1759 delayed iframe resizing until custom CSS is applied

---

views/js/core/databinder.js
views/js/test/core/databinder/test.js

related to:
https://github.com/oat-sa/qti-sdk/pull/22

add value to the model if not exist

---

models/classes/import/CsvAbstractImporter.php

Here is a PR related to CSV import of  TAO-1769  
In order to be familiarised with PRs : 
Test it doesn't break existing CSV import (for example with test taker)
Test if the related unit tests are still running
Check the code to see if nothing hurts you (only on the changes/diff)

add missing options

---

models/classes/import/CsvAbstractImporter.php
models/classes/import/CsvBasicImporter.php
test/import/CsvImportTest.php

the getClassProperties method doesn't return the label property so add it in service

Add label property by default

---

views/js/ui/filesender.js
views/js/ui/uploader.js

- Modify params of the `uploader` to set the form manually
- Fix error throwing in `filesender`
- post the full form in `filesender`
- fix indentation in both files
Unit test for the 2 modules would have been more than welcome but the 2 components (especially `filesender`) would require a strong refactoring (because [xhr2](http://caniuse.com/#feat=xhr2) is now well supported) so let's write a test in the same time.

Enable to upload a full form along with a file

---

helpers/form/elements/xhtml/class.Checkbox.php
views/js/form/post-render-props.js

in csv import when you have a checkbox list it was displaying radio buttons but you could select multiple.
related to : TAO-1826

render properly checkboxes instead of putting radio buttons

---

views/js/test/ui/listbox/test.js
views/js/ui/listbox.js

Related to: https://oat-sa.atlassian.net/browse/TAO-1966
Add optional callback to allow custom rendering of the displayed count of boxes.

listbox: add renderer for displayed count

---

install/class.Installator.php
manifest.php
models/classes/class.FileSourceService.php

depends on https://github.com/oat-sa/generis/pull/133

Allow generis to setup FS and update on addFs

---

views/js/core/eventifier.js
views/js/core/logger/api.js
views/js/test/core/eventifier/test.js
views/js/test/core/logger/api/test.js

I don't stringify the messages anymore and move logger messages from trace to debug level

improve the logger messages

---

actions/class.Main.php

Temporary fix until history rewriting is available in back office

Redirect instead of forward final page

---

models/classes/requiredAction/RequiredActionAbstract.php
models/classes/requiredAction/RequiredActionInterface.php
models/classes/requiredAction/RequiredActionRuleInterface.php
models/classes/requiredAction/RequiredActionServiceInterface.php

Unused namespaces removed from use

Added missing visibility modificators

---

manifest.php
scripts/install/setLocaleNumbersConfig.php
scripts/update/Updater.php
views/js/test/util/locale/test.html
views/js/test/util/locale/test.js
views/js/util/locale.js

Related to https://oat-sa.atlassian.net/browse/TAO-1726

Tao 1726 localised number parser core

---

views/js/test/ui/actionbar/test.html
views/js/test/ui/actionbar/test.js
views/js/ui/actionbar.js
views/js/ui/actionbar/tpl/main.tpl

Exported component from datalist/datatable.
Will maybe replace the existing parts in these components.

Add an actionbar component

---

views/js/ui/previewer.js

Related to: https://oat-sa.atlassian.net/browse/TAO-2352

ui/previewer: trigger event when image is loaded

---

manifest.php
scripts/update/Updater.php

Just set a version to get the right dependency for core/asyncProcess in other extensions.
This will also need a merge from master into develop.

fix version

---

views/js/core/encoder/str2array.js
views/js/test/core/encoder/str2array/test.html
views/js/test/core/encoder/str2array/test.js

Validation can be made using the tests.

modify and test the str2array encoder

---

views/js/core/timer.js
views/js/test/core/timer/test.js

Add actions to arbitrary increase/decrease the timer

core/timer: add operation actions (add/sub)

---

manifest.php
scripts/update/Updater.php

increase version from `2.19.0` to `2.20.0`

increase version from 2.19.0 to 2.20.0

---

views/js/test/ui/dialog/test.js
views/js/ui/dialog.js

reason: https://oat-sa.atlassian.net/browse/TAO-2427

At the opening of the dialog, sets focus on a modal window

---

views/js/ui/dialog/tpl/body.tpl

backport of https://github.com/oat-sa/tao-core/pull/785

allow markup in dialog

---

views/js/core/store.js

Provides a better feature detection of the store backend. 
We need to open a DB because Firefox in private browsing mode exposes the indexedDB object but fails when we use it. This is a Firefox [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=781982) but we need to fallback to the other backends.
Test : 
- run a test with the new testrunner in FF, FF incognito, Chrome, Chrome incognito and they should all run without error
- the unit tests are not affected because they run against PhantomJs / Webkit

try to detect IndexedDB support

---

views/js/test/ui/autoscroll/test.html
views/js/test/ui/autoscroll/test.js
views/js/ui/autoscroll.js

New UI helper to autoscroll a container in order to make an element visible.

Add autoscroll UI helper

---

helpers/class.File.php
views/js/test/ui/previewer/test.js
views/js/ui/previewer.js

Related to: https://oat-sa.atlassian.net/browse/TAO-668

Use the new media player inside the the previewer

---

manifest.php
models/classes/GenerisTreeFactory.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/browse/TAO-2560

Updated generis tree form (all data sorted by label)

---

manifest.php
scripts/update/Updater.php
views/js/core/communicator.js
views/js/core/communicator/poll.js
views/js/test/core/communicator/poll/test.html
views/js/test/core/communicator/poll/test.js
views/js/test/core/communicator/test.js

Related to: https://oat-sa.atlassian.net/browse/TAO-2583
Add a communicator implementation that use polling to communicate with a remote service

Add polling communictor implementation

---

views/build/config/requirejs.build.js

this add the missing config for client bundle compilation from https://github.com/oat-sa/tao-core/pull/829

added interact js lib in the co,fig of build require

---

views/js/core/polling.js

Improved consistency of promise/resolver when using core/polling in async mode

Fix polling promise/resolver

---

views/js/core/plugin.js
views/js/test/core/plugin/test.js

Related to: https://oat-sa.atlassian.net/browse/TAO-2585

Place the install() method into the plugin's life cycle

---

views/js/core/delegator.js
views/js/core/plugin.js
views/js/test/core/delegator/test.js

Add a `wrapper` option in the delegator helper.
Use the `wrapper` option within the plugin API.

Use the delegator with the plugin component

---

views/js/ui/dynamicComponent.js

Optimize transform and some doc fixes

move translate calc to gpu

---

models/classes/menu/Section.php

for example:
clean cache: http://tao.loc/tao/Main/index?structure=tools&ext=taoDevTools&section=scripts
try to go in other section: http://tao.loc/tao/Main/index?structure=delivery&ext=taoDeliveryRdf

After clearing cache I see php notice that index in array is not exists

---

actions/class.RestController.php
manifest.php
scripts/update/Updater.php

required for https://github.com/oat-sa/extension-tao-itemqti/pull/724

REST controller supported mime type

---

actions/form/class.Instance.php
helpers/form/class.GenerisFormFactory.php
helpers/form/elements/class.Treeview.php
helpers/form/elements/xhtml/class.Treeview.php

related to https://oat-sa.atlassian.net/browse/TAO-2688

tree widget

---

actions/class.Main.php
manifest.php
models/classes/event/LoginEvent.php
models/classes/event/LoginFailedEvent.php
models/classes/event/LoginSucceedEvent.php
scripts/update/Updater.php

Related to https://oat-sa.atlassian.net/browse/TAO-2705
https://github.com/oat-sa/extension-tao-act/pull/271
https://github.com/oat-sa/tao-core/pull/881
https://github.com/oat-sa/extension-tao-eventlog/pull/6

TAO-2705 New Login events

---

helpers/class.Http.php
manifest.php
scripts/update/Updater.php

required for refactor/rest-test-import https://github.com/oat-sa/extension-tao-testqti/pull/505

add hasFileUploaded in http helper

---

manifest.php
scripts/update/Updater.php
views/js/lib/calculator/index.js

https://oat-sa.atlassian.net/browse/TAO-2787

Fix divide button on the calculator

---

views/js/core/pluginLoader.js
views/js/test/core/pluginLoader/mockBundle.min.js
views/js/test/core/pluginLoader/test.js

1st step to be able to load a plugin bundle

add pluginLoader.addBundle

---

views/js/layout/tree.js
views/templates/footer.tpl

Refreshing tree after edit instane

---

manifest.php
scripts/update/Updater.php
views/js/core/cachedStore.js
views/js/core/store.js
views/js/core/store/indexdb.js
views/js/core/store/localstorage.js
views/js/test/core/cachedStore/storeMock.js
views/js/test/core/cachedStore/test.js
views/js/test/core/store/indexdb/test.js
views/js/test/core/store/local/test.js
views/js/test/core/store/store/test.js

Related to: https://oat-sa.atlassian.net/browse/TAO-2641
Browser DB remover, extracted without "lastActivity" feature from the PR: https://github.com/oat-sa/tao-core/pull/855

Browser DB remover

---

manifest.php
scripts/update/Updater.php
views/js/test/ui/dateRange/test.html
views/js/test/ui/dateRange/test.js
views/js/ui/dateRange.js
views/js/ui/dateRange/tpl/select.tpl

https://oat-sa.atlassian.net/browse/TAO-2846

Date range picker component

---

models/classes/import/class.CSVMappingForm.php

Related to https://oat-sa.atlassian.net/browse/TAO-2830

Fixed issue, when import without headers imported data without first row

---

install/utils/class.ChecksHelper.php
manifest.php
scripts/update/Updater.php

(breaks if an extension only require generis)

define checkArray variable in all case

---

helpers/form/class.Validator.php
helpers/form/validators/class.AlphaNum.php
helpers/form/validators/class.FileName.php
helpers/form/validators/class.Url.php
manifest.php
scripts/update/Updater.php

depend on https://github.com/oat-sa/generis/pull/236

add validator interface

---

views/js/core/mimetype.js
views/js/core/mimetype/categories.json
views/js/test/core/mimetype/test.js

This PR fixes the last issue detected by the client on her windows machine. For more details, see the last comment on https://oat-sa.atlassian.net/browse/TAO-2838

added more generic mimetype to allow better mime detection

---

manifest.php
scripts/update/Updater.php

when php-curl extension isn't installed

Fixed output of the errors on installation Requirements Check

---

helpers/class.Environment.php
manifest.php
scripts/update/Updater.php

Based on http://php.net/manual/en/ini.core.php#ini.post-max-size we should still use memory_limit directive

reverted memory checking

---

helpers/form/validators/class.Regex.php
manifest.php
scripts/update/Updater.php

You can experiment it by creating test takers on a project having complex password validation rules. Only a generic message was displayed for each password constraint.

fix regex validator.

---

manifest.php
scripts/update/Updater.php
views/js/ui/datatable.js
views/js/ui/datatable/filterStrategy/filterStrategy.js
views/js/ui/datatable/filterStrategy/multiple.js
views/js/ui/datatable/filterStrategy/single.js

Related to https://oat-sa.atlassian.net/browse/TAO-3316
https://github.com/oat-sa/extension-tao-mpart/pull/364

Tao 3316 filter selector option

---

manifest.php
scripts/update/Updater.php
views/js/ui/datatable/tpl/layout.tpl

Column order is not correct. 
The buttons should be next to the status column as per the provided image.
If possible the button should be centre justified within the column.

Added actions class to the datatable component in the action column

---

views/js/test/ui/incrementer/test.html
views/js/test/ui/incrementer/test.js
views/js/ui/incrementer.js

Prevent the incrementer component to enable changing the input content when disabled

disable also the input

---

views/js/ui/movableComponent.js

Related to: https://oat-sa.atlassian.net/browse/TAO-3377
Forward  start/end events on drag and resize from the movableComponent

Add events on drag and resize

---

manifest.php
scripts/update/Updater.php
views/js/test/ui/cascadingComboBox/test.js
views/js/ui/cascadingComboBox.js

There is are less of changed lines ;)
https://github.com/oat-sa/tao-core/pull/1126/files?w=1

ODS Pause Report showing incorrect Subcategory

---

config/default/ExtraPoService.conf.php
helpers/class.I18n.php
manifest.php
models/classes/i18n/ExtraPoService.php
scripts/update/Updater.php

Ability for extensions (specifically customer extensions) to register extra PO files (either compiled in PHP or regular POs) in order to override TAO Core translations without having impact on the existing core translations.

Extra PO Service

---

manifest.php
scripts/update/Updater.php
views/js/ui/keyNavigation/navigableDomElement.js
views/js/ui/keyNavigation/navigableGroupElement.js
views/js/ui/keyNavigation/navigator.js

Depencies between:
https://github.com/oat-sa/extension-tao-testqti/pull/756
https://github.com/oat-sa/extension-tao-itemqti/pull/894
https://github.com/oat-sa/tao-core/pull/1199
https://github.com/oat-sa/extension-tao-act/pull/493, instructions are provided there

keyboard navigation now skips disabled elements

---

actions/class.Breadcrumbs.php
actions/class.SinglePageModule.php
manifest.php
models/classes/mvc/Breadcrumbs.php
scripts/update/Updater.php
views/templates/blocks/breadcrumbs.tpl
views/templates/pages/index.tpl

Related to: https://oat-sa.atlassian.net/browse/TAO-3496
Add abstract class for controllers that serve single page application.
Add API for breadcrumbs:
- provide an interface for service that should provide breadcrumbs
- add a base controller to serve breadcrumbs

Add single page app controller

---

manifest.php
scripts/update/Updater.php
views/templates/blocks/header-main-navi.tpl

Added hidden 'Logout' text, hidden to keep existing behaviour for all customer platforms

https://oat-sa.atlassian.net/browse/TAO-4056

---

actions/class.ClientConfig.php
manifest.php
scripts/update/Updater.php

test with tao installed in a sub folder, the resolver fails to validate the URL

fix config whitelisting in subfolder

---

actions/class.PropertiesAuthoring.php
manifest.php
scripts/update/Updater.php
views/templates/form/generis_tree_form.tpl

Everything related to URI have been fixed by https://github.com/oat-sa/tao-core/commit/b0a2a4e9f3f96044e5d1cfa97bcbf55c63b45921 
I've added a proper encoding to the values )

Prevent XSS

---

manifest.php
scripts/update/Updater.php
views/js/ui/datatable.js
views/js/ui/datatable/tpl/layout.tpl

https://oat-sa.atlassian.net/browse/TAO-4297
This changes required by the customer for NCCER but also it may be useful in the future.

Added labels for datatable config and ability change them by options

---

manifest.php
models/classes/mvc/DefaultUrlService.php
scripts/update/Updater.php

Create assessors to access configurable routes to make easier to override it

Use set/get route to access urlservice options

---

config/default/operatedby.conf.php
config/header/operatedby.conf.php
install/class.Installator.php
install/js/step_finalization.js
install/js/step_server_setup.js
install/tpl_step_server_setup.html
manifest.php
models/classes/OperatedByService.php
scripts/class.TaoInstall.php
scripts/taoInstall.php
scripts/update/Updater.php

**Depends on https://github.com/oat-sa/generis/pull/360**

Feature/tao 4414/operated by install

---

install/services/class.SyncService.php
lib/oauth/OAuth.php
manifest.php
models/classes/mvc/Bootstrap.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/browse/TAO-4493 
depends on https://github.com/oat-sa/generis/pull/376

Tao 4493/cookies secure flag

---

actions/class.PropertiesAuthoring.php
manifest.php
models/classes/event/ClassFormUpdatedEvent.php
models/classes/event/ClassUpdatedEvent.php
scripts/update/Updater.php

Related to https://oat-sa.atlassian.net/browse/TAO-3105

Tao 3105 event log issues

---

locales/it-IT/lang.rdf

fix Italian transaltion

---

manifest.php
models/classes/metadata/writer/ontologyWriter/PropertyWriter.php
scripts/tools/rdf/RdfDuplicates.php
scripts/update/Updater.php

FYI:
quick way to delete duplicates it's a direct query:
```
DELETE FROM statements s where s.id IN (SELECT s1.id FROM statements s1
LEFT OUTER JOIN (
SELECT MIN(s2.id) as id, s2.modelid, s2.subject, s2.predicate, s2.object, s2.l_language  
FROM statements s2
GROUP BY s2.modelid, s2.subject, s2.predicate, s2.object, s2.l_language
) as KeepRows ON
s1.id = KeepRows.id
WHERE
KeepRows.id IS NULL)
```

Fix/tao 5366/rdf duplications

---

manifest.php
scripts/update/Updater.php
views/js/ui/documentViewer/providers/pdfViewer/pdfjs/viewer.tpl

Related to https://oat-sa.atlassian.net/browse/TAO-5743

Tao 5743 fixed pdf viewer translation

---

manifest.php
models/classes/GenerisTreeFactory.php
models/classes/class.GenerisService.php
scripts/update/Updater.php

depends on https://github.com/oat-sa/generis/pull/447

Fix/tao 5793/filter out delivery not finished

---

install/services/class.InstallService.php

Revert "Loaded logger as pimple container"

---

manifest.php
scripts/update/Updater.php

Release 17.13.2

---

manifest.php
scripts/update/Updater.php
views/js/controller/users/index.js
views/js/test/ui/datatable/test.js
views/js/ui/datatable.js

In order to be able to disable/enable user data language we need to be able to disable/enable `Data Language` column on users table.

Allow to disable datatable columns

---

manifest.php
scripts/update/Updater.php
views/js/ui/mediasizer.js

https://oat-sa.atlassian.net/browse/TAO-6206

Fix/tao 6206/mediasizer ratio

---

actions/form/class.Login.php

To test, type a password in the login form. Password should be obfuscated.

changed textbox to hidden box

---

manifest.php
scripts/update/Updater.php
views/js/ui/datatable.js

https://oat-sa.atlassian.net/browse/TAO-6699

Tao 6699/waiting for responce

---

composer.json
helpers/RestExceptionHandler.php
install/api.php
install/api/NotAllowedAPICallException.php
install/init.php
install/services/class.Service.php
install/utils/class.System.php
manifest.php
models/classes/routing/AbstractApiRoute.php
models/classes/routing/CliController.php
models/classes/routing/LegacyRoute.php
models/classes/routing/NamespaceRoute.php
models/classes/routing/Resolver.php
models/classes/routing/Route.php
scripts/update/Updater.php

Release 20.0.0

---

getFile.php
getFileFlysystem.php
manifest.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/browse/TAO-7007

Tao 7007/error handler for file exposer

---

actions/class.CommonModule.php
manifest.php
scripts/update/Updater.php

The CSP header was causing issues in at least one existing project

Removed CSP header

---

actions/class.Export.php
actions/class.ExtensionsManager.php
actions/class.PropertiesAuthoring.php
actions/class.RdfController.php
actions/class.Roles.php
actions/class.Users.php
manifest.php
models/classes/accessControl/data/DataAccessControl.php
models/classes/class.MissingRequestParameterException.php
models/classes/mvc/error/ExceptionInterpretor.php
scripts/update/Updater.php
views/templates/error/error400.tpl
views/templates/error/error403.tpl
views/templates/error/error404.tpl
views/templates/error/error500.tpl
views/templates/error/maintenance.tpl
views/templates/error/user_error.tpl

According to https://oat-sa.atlassian.net/browse/TAO-7214

Tao 7214 fixed endpoints 500 errors

---

manifest.php
scripts/update/Updater.php
views/js/core/digest.js
views/js/lib/polyfill/webcrypto-shim.js
views/js/test/core/digest/test.html
views/js/test/core/digest/test.js

same as https://github.com/oat-sa/tao-core/tree/backport/release-15.6.0 but in against develop branch

Tao 7186/js digest

---

actions/class.RestResource.php
actions/class.Roles.php
manifest.php
scripts/update/Updater.php

This PR fixes two things:
1. The Manage Roles feature was not working anymore.
2. The EditRole action was buggy so that it was not possible to retrieve roles.

Fix issue with BRS and roles management.

---

manifest.php
scripts/update/Updater.php
views/js/ui/transformer.js

https://oat-sa.atlassian.net/browse/TAO-7340
Fix an iPad error related with computed styles
dependent
https://github.com/oat-sa/extension-tao-nfer/pull/89

Fix/tao 7340 Fix an iPad error related with computed styles

---

actions/class.Main.php
manifest.php
scripts/update/Updater.php
views/js/controller/login.js
views/js/test/ui/login/test.html
views/js/test/ui/login/test.js
views/js/ui/login/login.js
views/js/ui/login/tpl/fakeForm.tpl
views/js/ui/login/tpl/login.tpl
views/js/ui/login/tpl/passwordReveal.tpl
views/templates/blocks/login.tpl

*Note*: This is just a "branch-rename" change into the original PR #1923 .
This PR introduces login component.
It was done so to move some code and DOM manipulations from BE side to FE. As the way it is currently done on the BE side - just provides a lot of mess.

Feature/tao 7352/login component

---

manifest.php
scripts/update/Updater.php
views/js/ui/ckeditor/ckConfigurator.js

It is a part of oat-sa/extension-tao-testqti#1369.
Should be merged before it.

Fix/tao 6409/ckeditor toolbar layout

---

manifest.php
scripts/update/Updater.php

Release 22.13.1

---

manifest.php
scripts/update/Updater.php

Fixed versioning error at 22.13.2

Versioning correction in Updater

---

helpers/data/class.GenerisAdapterRdf.php
manifest.php
scripts/update/Updater.php

Made sure that RDF type gets exported. This solves the issue of tests not showing up after importing.

Fix/tao 7469 RDF subclass export

---

actions/class.CommonRestModule.php
actions/class.RestController.php
actions/class.RestTrait.php
doc/swagger.json
manifest.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/browse/TAO-7390

Feature/tao 7390/openapi docs

---

actions/class.RestController.php
manifest.php
scripts/update/Updater.php

Release 25.1.3

---

manifest.php
scripts/update/Updater.php
views/js/test/ui/maths/calculator/plugins/core/degrad/test.html
views/js/test/ui/maths/calculator/plugins/core/degrad/test.js

related to https://oat-sa.atlassian.net/browse/TAO-7703

Feature/tao 7703/scientific calculator tweaks

---

manifest.php
scripts/update/Updater.php
views/js/test/ui/maths/calculator/plugins/modifiers/sign/test.html
views/js/test/ui/maths/calculator/plugins/modifiers/sign/test.js
views/js/test/ui/maths/calculator/plugins/modifiers/sign/testCases.json
views/js/ui/maths/calculator/plugins/modifiers/sign.js

related to https://oat-sa.atlassian.net/browse/TAO-7704

Fix/tao 7704/plus minus signal not work previous expression

---

test/integration/user/import/RdsUserImportServiceTest.php
test/unit/actionQueue/AbstractActionTest.php
test/unit/datatable/DatatableRequestTest.php
test/unit/helpers/ArrayHelperTest.php
test/unit/helpers/DisplayTest.php
test/unit/helpers/FileTest.php
test/unit/helpers/NumericTest.php
test/unit/model/ClassServiceTest.php
test/unit/model/mvc/error/ExceptionInterpreterServiceTest.php
test/unit/model/mvc/error/ExceptionInterpretorTest.php
test/unit/model/security/TokenGeneratorTest.php
test/unit/model/security/xsrf/TokenServiceTest.php
test/unit/model/taskQueue/QueueTest.php
test/unit/model/taskQueue/TaskLogTest.php
test/unit/requiredAction/RequiredActionRedirectUrlPartTest.php
test/unit/service/ApplicationServiceTest.php
test/unit/translations/TranslationBundleTest.php

Unit tests are working. Integration tests are not all fixed yet.

TAO-7682: Fixed Unit tests.

---

views/js/layout/actions.js
views/js/layout/actions/common.js
views/js/layout/tree/provider/jstree.js
views/js/provider/resources.js
views/js/ui/resource/selectable.js

For actions "instanciate" and "subClass" server needs signature of class. When we select item inside class we need classSignature by analogy with the classUri

add classSignature for instanciate and subClass actions

---

actions/class.CommonModule.php

Add "|\JsonSerializable" to phpdoc

Small phpdoc fix

---

controller/api/Users.php
manifest.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/browse/TAO-7789

User API validate login parameter

---

manifest.php
models/classes/actionQueue/event/ActionQueueTrendEvent.php
models/classes/actionQueue/implementation/InstantActionQueue.php
scripts/update/Updater.php

- added `ActionQueueTrendEvent` which triggers when ActionQueue trend changes for given action. Trend (endbled/disabled) and action can be given from an event.

Tao 8020 notify action queue event

---

manifest.php
models/classes/requiredAction/implementation/RequiredActionService.php
scripts/update/Updater.php
test/unit/requiredAction/RequiredActionServiceTest.php

https://oat-sa.atlassian.net/browse/TAO-7918
Added the detach method for detaching actions from RequiredActionService. It's needed if you need to detach one action and attach another one.

Feature/tao 7918/key value security statement

---

manifest.php
models/classes/security/xsrf/Token.php
models/classes/security/xsrf/TokenService.php
models/classes/security/xsrf/TokenStoreKeyValue.php
scripts/update/Updater.php
test/unit/model/security/xsrf/TokenServiceTest.php
test/unit/model/security/xsrf/TokenStoreKeyValueTest.php
test/unit/model/security/xsrf/TokenTest.php

Hot fix for token pool issue with KV storage - details on https://oat-sa.atlassian.net/browse/TAO-7306

Hotfix/tao 7306/token error with kv storage

---

manifest.php
scripts/update/Updater.php
views/js/test/util/clipboard/test.js
views/js/util/clipboard.js

https://oat-sa.atlassian.net/browse/TAO-7852
Added commentaries into the code

added code commentaries

---

manifest.php
scripts/update/Updater.php
views/js/test/tpl/samples/property.tpl
views/js/test/tpl/test.js
views/js/tpl.js

fix datatable tpl (value "0" not show in datatable tpl).
Steps to reproduce 
Go to Test Center
Select Center
Create new Eligible without test takers
Expected behavior:
In "Eligible Test Takers" column value "0";
Actual behavior:
In "Eligible Test Takers" column value "" (empty);

Fix/tao 8387/fix datatable tpl

---

manifest.php
scripts/update/Updater.php
views/build/package.json

update dependency to the bundler

update dependency to the bundler

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/TAO-8246
Update the frontend packages in order to get the addition in UI components (collection of `ui/form/*`), and other fixes.

Feature/tao 8246/update frontend libs

---

manifest.php
models/classes/mvc/error/ExceptionInterpretor.php
models/classes/mvc/error/JsonResponse.php
models/classes/mvc/error/ResponseAbstract.php
scripts/update/Updater.php
views/templates/error/error405.tpl

https://oat-sa.atlassian.net/browse/TAO-8195
Depends on: https://github.com/oat-sa/generis/pull/644
Handle common_exception_MethodNotAllowed in a proper way 
(405 status code and 'Allow' header according to RFC
https://tools.ietf.org/html/rfc7231#section-6.5.5

Feature/tao 8195/method not allowed handling

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/TAO-8191
Update the frontend lib package `tao-core-sdk-fe` to version `0.5.0`.
You will need to run `npm i` in `tao/views`

Feature/tao 8191/update tao core sdk fe

---

manifest.php
scripts/update/Updater.php
views/js/generis.tree.select.js

https://oat-sa.atlassian.net/browse/TAO-8592
If configured order in tree it is not working while pagination.
To reproduce bug it is needed to publish 21+ deliveries (more deliveries published - more chance to reproduce).

fix/TAO-8592 incorrect order in tree.

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

ticket: https://oat-sa.atlassian.net/browse/TAO-8122
This PR upgrades the version of tao-core-ui-fe
relevant PRs:
https://github.com/oat-sa/tao-core-ui-fe/pull/37
https://github.com/oat-sa/extension-tao-nccer-delivery/pull/926

Fix/tao 8122/loading bar sync

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

Dependency increase following
- Feature/nex 201 implement session store  (https://github.com/oat-sa/tao-core-sdk-fe/pull/26)
- Fix/tao 8657/reuse rejected token  (https://github.com/oat-sa/tao-core-sdk-fe/pull/25)
- Fix/tao 8631/accept token lifetime from config (https://github.com/oat-sa/tao-core-sdk-fe/pull/24)

Increase tao core sdk to 0.6.0

---

manifest.php
scripts/update/Updater.php
views/js/form/post-render-props.js
views/js/test/form/post-render-prop/test.html
views/js/test/form/post-render-prop/test.js

Jira: https://oat-sa.atlassian.net/browse/TAO-7833
- JS check on regular property labels to keep them up to date
- unit test for the new method

Fix/tao 7833/update property labels

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

Following PR for https://github.com/oat-sa/tao-core-ui-fe/pull/62

update tao core ui

---

manifest.php
scripts/install/CreateWebhookEventLogTable.php
scripts/update/Updater.php

Webhook event log: fixed mysql schema

---

helpers/UrlHelper.php
includes/globalHelpers.php
manifest.php
scripts/update/Updater.php

This adds a simple class to encapsulate the call to global _url() function for unit tests.

Feature/nex 319/add non static url builder

---

manifest.php
scripts/update/Updater.php
views/build/grunt/s3.js

Fixed Typo in the ENV parameter name

Fixed typo

---

install/class.Installator.php
install/utils/class.DbalConfigCreator.php

This PR adds the option for Spanner as a DB engine in the installer.

Fixed database configurator.

---

models/classes/search/Search.php
models/classes/search/aggregator/UnionSearchService.php
test/unit/model/search/aggregator/UnionSearchServiceTest.php

The `UnionSearchService` is now covered with a few unit tests. Also, some minor improvements covering edge cases done.

Feature/nec 11/granularity search tests and minor improvements

---

helpers/class.Xml.php
manifest.php
scripts/update/Updater.php
test/unit/helpers/XmlHelperTest.php

Related to : https://oat-sa.atlassian.net/browse/TAO-9799
`extractElement` added to the Xml helper. With this helper we can find data in the xml.
UnitTests provided here:
```
tao/tao/test/unit/helpers/XmlHelperTest.php
```

Feature/tao 9799/xml helper

---

helpers/form/elements/xhtml/class.Treebox.php
manifest.php
scripts/update/Updater.php

Related with: https://oat-sa.atlassian.net/browse/TAO-6662
Fix treebox element
Fixed element rendering and getting values from post
1.Go to BackOffice -> settings -> Remote environments
2.Select env from the list with all checked Publish Actions or create it
3 Uncheck all and try to save
Actual result: they still checked
Expected result: they become unchecked

Fix/tao 6662/fix treebox element

---

manifest.php
scripts/update/Updater.php

Release 40.3.2

---

manifest.php
scripts/update/Updater.php
views/js/generis.tree.js

https://oat-sa.atlassian.net/browse/TAO-9431
Trees has this behavior because has same ID’s for tree nodes, it can be fixed by made node id’s more unique. Or by using id of the current touched container

Fix/tao 9431/generis tree paginator

---

manifest.php
scripts/update/Updater.php

Version was increased incorrectly

fixed versions in the updater

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/INV-43
This tooltip is applied for the inline text interactions.
Changed the tooltip size like it was in older sprints.

INV-43: Tooltip issue (Test text covered & unreadable)

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

**Related to this issue:** https://oat-sa.atlassian.net/browse/BOSA-37
**Related to this PR:** https://github.com/oat-sa/tao-core-ui-fe/pull/97
When I open a test with a folder name having special characters, the name of the folder is transformed is a strange format.
**Steps to reproduce**
Step 1: Open a test in authoring
Step 2: Click on Author
Step3: Take a look into the conversion of the folder name (print screen attached)
**Expected result**
The name of the folders in the Test tab should be converted correctly.

Fix/bosa 37/test authoring special characters

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

**Related to**
https://oat-sa.atlassian.net/browse/ACTP-312
Update npm package
**Companion PR :**
https://github.com/oat-sa/tao-core-ui-fe/pull/102

Feature/actp 312/add a11y compatibility to login errors

---

actions/class.Main.php
actions/class.Notification.php
models/classes/notification/Notification.php
models/classes/notification/NotificationInterface.php
models/classes/notification/NotificationServiceInterface.php
models/classes/notification/implementation/Notification.php
models/classes/notification/implementation/NotificationServiceAggregator.php
models/classes/notification/implementation/RdsNotification.php
test/unit/auth/BasicTypeTest.php
test/unit/models/classes/notification/NotificationTest.php
test/unit/models/classes/notification/implementation/RdsNotificationTest.php

Notification object moved the directory up.
The interface has required PHP docs.
Merge is a part of changes made in branch `feature/NEX-137/add-spanner-driver`
https://oat-sa.atlassian.net/browse/NEX-778

Merge/nex 778/notfication object

---

manifest.php
models/classes/resources/SecureResourceService.php
scripts/update/Updater.php
test/unit/models/classes/resources/SecureResourceServiceTest.php

added support of FreeAccess to SecureResourceService

Fix/udi 97/free access by default

---

composer.json
models/classes/oauth/lockout/storage/LockoutStorageInterface.php
models/classes/oauth/lockout/storage/RdsLockoutStorage.php
test/unit/oauth/lockout/IPLockoutTest.php

NFER-55 fix(dependencies): use less strict `oat-sa/generis` dependency

NFER-55 dependencies quickfix

---

actions/class.File.php
manifest.php
scripts/update/Updater.php

Fixes the invalid mime types on media and pci javascript.
This error is unfortunately not coverable by unit tests yet.

Fix mime type error on pci

---

manifest.php
models/classes/resources/SecureResourceService.php
scripts/update/Updater.php

checking permission we failed when a class didn't have ani instances

Fix/udi 97/no instances trigger error

---

manifest.php
models/classes/oauth/lockout/storage/RdsLockoutSchema.php
scripts/update/Updater.php
test/unit/model/taskQueue/Task/TaskSerializerServiceTest.php
test/unit/model/taskQueue/Worker/AbstractWorkerTest.php

Related to: TBD-8
Changed column type from integer to bigint to store ip2long()

TBD-8 changed column to bigint to store ip2long()

---

composer.json
manifest.php
models/classes/oauth/lockout/storage/RdsLockoutSchema.php
scripts/update/Updater.php
test/unit/model/taskQueue/Task/TaskSerializerServiceTest.php
test/unit/model/taskQueue/Worker/AbstractWorkerTest.php

Backport/tbd 8/bigint column

---

manifest.php
models/classes/oauth/lockout/storage/KvLockoutStorage.php
models/classes/oauth/lockout/storage/LockoutStorageAbstract.php
models/classes/oauth/lockout/storage/LockoutStorageInterface.php
models/classes/oauth/lockout/storage/RdsLockoutStorage.php
scripts/install/SetUpOAuthLockoutService.php
scripts/update/Updater.php

NFER-66 backport: #2472 into Sprint 111

NFER-66:  Backport a key-value storage for the OAuth lockout service

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

**Related to:**
https://oat-sa.atlassian.net/browse/ACTP-373
Login page: KB focus + hit "Enter" on "Show password" button triggers login
**How to check:**
Open TAO login.
Fill in some credentials.
Set focus to Show/Hide password button using KB.
Hit Enter button.
Password should be revealed, focus on password field.
Requires :

Fix/actp 373/hit enter show password

---

manifest.php
models/classes/http/RequestRebuilder.php
models/classes/mvc/Bootstrap.php
scripts/update/Updater.php
test/unit/http/RequestRebuilderTest.php

https://oat-sa.atlassian.net/browse/NEX-878

Feature/nex 878/ssl offloading rebuilder

---

install/class.Setup.php
install/utils/class.DbalConfigCreator.php
test/unit/model/taskQueue/Task/TaskSerializerServiceTest.php
test/unit/model/taskQueue/Worker/AbstractWorkerTest.php

https://oat-sa.atlassian.net/browse/NEX-778

Installer should be aware of custom drivers

---

manifest.php
scripts/update/Updater.php

As this has been forgotten in the https://github.com/oat-sa/tao-core/pull/2431

Bump version ( for newsql schema support - notifications )

---

manifest.php
models/classes/notification/implementation/AbstractSqlNotificationService.php
scripts/update/Updater.php
test/unit/models/classes/notification/NotificationTest.php

https://oat-sa.atlassian.net/browse/NEX-778
Fixed 
1. Logic of counting and instantiation for notifications 
2. PSR-12

Notification instantiation fixed

---

manifest.php
models/classes/webhooks/log/AbstractWebhookLogRepository.php
scripts/update/Updater.php

Prevents fatal error in updater caused by previous refactoring for https://oat-sa.atlassian.net/browse/NEX-778

Fix for broken by access modificator updater

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

Related to : https://oat-sa.atlassian.net/browse/TCA-557
Update package.json
Companion PR :

[TCA-557] Update package json

---

manifest.php
models/classes/media/MediaService.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/browse/NEX-1202

Fix/nex 1202/media service responsibility

---

actions/class.PropertiesAuthoring.php
actions/class.RdfController.php
actions/form/class.AbstractProperty.php
actions/form/class.Clazz.php
actions/form/class.SimpleProperty.php

- Removed index setup icon
- Icon is not rendered only when ElasticSearch library is installed and in use
- Changes on backend only

TAO-10253 Disabling index modification on all sections when ElasticSearch is enabled

---

manifest.php
models/classes/media/MediaBrowser.php
models/classes/media/MediaService.php
models/classes/media/ProcessedFileStreamAware.php
models/classes/media/sourceStrategy/HttpSource.php
scripts/update/Updater.php
views/package-lock.json

https://oat-sa.atlassian.net/browse/NEX-1202

Fix/nex 1202/reduce media service responcibility

---

manifest.php
scripts/update/Updater.php
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/BSA-147
Updated "@oat-sa/tao-core-ui" to "1.4.1"

Fix/bsa 147/update tao core ui

---

manifest.php
models/classes/actionQueue/implementation/InstantActionQueue.php
models/classes/actionQueue/restriction/BasicRestriction.php
scripts/update/Updater.php

Renamed abstract class & method to comply with PSR-12
Related to : https://oat-sa.atlassian.net/browse/TCA-651
There are no changes in the behavior in this PR. Correctness can be tested with the described scenarios in companion PR's.
Companion PR :

Breaking/tca 651/login queue ce

---

manifest.php
scripts/class.TaoTranslate.php
scripts/update/Updater.php

The original task is [BSA-128](https://oat-sa.atlassian.net/browse/BSA-128)
It is required for the proper building lines for translation from scripts, like [there](https://github.com/oat-sa/extension-tao-colorcontrast/pull/10).

Fetching lines for translation from scripts

---

scripts/install/RegisterClassPropertyRemovedEvent.php

Just a small fix for for the method name being called when event is triggered

TAO-10285 Fixed method to be called

---

composer.json
manifest.php
scripts/tools/Migrations.php

Change the doctrine/migrations dependency in order to get latest fixes.
Fix notice: `Notice: Trying to access array offset on value of type int in D:\domains\package-tao\vendor\symfony\console\Input\ArrayInput.php on line 135`

upgrade doctrine migrations to 3.0.1

---

manifest.php
views/package-lock.json
views/package.json

Related to : https://oat-sa.atlassian.net/browse/TCA-634
once the tool is enabled make sure that it fits container boundaries
- prepare an instance of TAO
- prepare a delivery with enabled calculator and scratchpad
- execute delivery as a test taker
- zoom delivery up to 200%
- enable calculator and scratchpad make sure that it fits container boundaries
Companion PR :

[TCA-634] Support Browser Zooming Customizations

---

manifest.php
views/package-lock.json
views/package.json

Related to : https://oat-sa.atlassian.net/browse/TCA-668
update package.json
- prepare an instance of TAO with taoAct extension
- navigate to login page
- make sure that on hidden form there is `aria-hidden` attribute
Companion PR :

[TCA-668] Delete hidden additional login form

---

manifest.php
views/js/controller/backoffice.js

**Related to**
https://oat-sa.atlassian.net/browse/NEX-1243
**Related to this PR**
https://github.com/oat-sa/tao-core/pull/2580
Support specific error `999` for handle in FE without errors

Feature NEX 1243 - Add support custom error

---

models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilderInterface.php
models/classes/search/index/IndexDocument.php
models/classes/search/index/IndexService.php
models/classes/search/tasks/UpdateResourceInIndex.php
test/unit/models/classes/search/index/GenerisIndexDocumentBuilderTest.php
test/unit/models/classes/search/index/IndexServiceTest.php

- Added logic to retrieve DACL data for indexation
- Included check to see if `taoDacSimple` is enabled

Add DACL to indexation

---

manifest.php
views/package-lock.json
views/package.json

**Related to this PR**
https://github.com/oat-sa/tao-core-ui-fe/pull/141
**Related to**
https://oat-sa.atlassian.net/browse/TAO-10122
Upgrade version of `npm package` in this extension

Fix TAO 10122 - IE11 graphic gap interaction when navigate to question since response

---

manifest.php
views/package-lock.json
views/package.json

**Related to**
https://oat-sa.atlassian.net/browse/BSA-183
**Related to this PR**
https://github.com/oat-sa/tao-core-ui-fe/pull/156
This PR is to allow dynamic translations of CKEditor based on selected language by the user

@oat-sa/tao-core-ui 1.5.4 -> 1.6.0

---

manifest.php
models/classes/routing/ActionEnforcer.php

Propagate service locator and logger to newly instantiated service

[TAO-10170] Fix: propagate service locator and logger to newly instantiated service 

---

manifest.php
views/package-lock.json
views/package.json

**Related to this PR that needs to be merge before**
https://github.com/oat-sa/tao-core-ui-fe/pull/176
Just bump versions

[FIX] CGA 138 - Dropdown arrow moved to top

---

manifest.php
views/package-lock.json
views/package.json

**Related to this npm package PR**
https://github.com/oat-sa/tao-core-ui-fe/pull/185

[Fix] TAO 10087 - Import button does not become disabled when user removes file which is uploaded for importing

---

helpers/class.File.php
helpers/class.Http.php
manifest.php
models/classes/http/ContentDetector.php
models/classes/websource/BaseWebsource.php
test/unit/http/ContentDetectorTest.php

https://oat-sa.atlassian.net/browse/NEX-1815

Gzip content detector for svgz outputs

---

README.md
manifest.php
models/classes/featureFlag/FeatureFlagChecker.php

https://oat-sa.atlassian.net/browse/NEX-1989
I updated `.ENV` variable in order to check if key exist. 
README updated with small instructions

Fix/nex 1989/feature flag undefined variable

---

manifest.php
models/classes/websource/BaseWebsource.php

https://oat-sa.atlassian.net/browse/NEX-2059
works together with https://github.com/oat-sa/extension-tao-itemqti/pull/1557

Feature/nex 2059/svgz support

---

manifest.php
views/package-lock.json
views/package.json

Related to : https://oat-sa.atlassian.net/browse/TAO-ID
Set the package.json to use updated list/tree component for resources
- please check  https://github.com/oat-sa/extension-tao-testqti/pull/1926
see https://github.com/oat-sa/extension-tao-testqti/pull/1926
Requires :
Companion PR :

fe library for the fix tree and list components

---

manifest.php
views/package-lock.json
views/package.json

Ticket: https://oat-sa.atlassian.net/browse/MS-469
- clearSingleHighlight is also exported with highlighter factory
https://github.com/oat-sa/extension-lti-outcomeui/pull/18

Feature/ms 512/highlight eraser

---

actions/class.ResourceRelations.php
config/default/ItemResourceRelationService.conf.php
config/default/ResourceRelationServiceProxy.conf.php
doc/taoApi.yml
manifest.php
migrations/Version202010301132112234_tao.php
migrations/Version202010301232112234_tao.php
models/classes/resources/relation/FindAllQuery.php
models/classes/resources/relation/ResourceRelation.php
models/classes/resources/relation/ResourceRelationCollection.php
models/classes/resources/relation/exception/NestedClassLimitExceededException.php
models/classes/resources/relation/service/ItemResourceRelationService.php
models/classes/resources/relation/service/ResourceRelationServiceInterface.php
models/classes/resources/relation/service/ResourceRelationServiceProxy.php
scripts/install/RegisterResourceRelationService.php
test/unit/model/resources/relation/FindAllQueryTest.php
test/unit/model/resources/relation/ResourceRelationCollectionTest.php
test/unit/model/resources/relation/ResourceRelationTest.php
test/unit/model/resources/relation/service/ItemResourceRelationServiceTest.php
test/unit/model/resources/relation/service/ResourceRelationServiceProxyTest.php
views/package-lock.json
views/package.json

- Return resources relation through an endpoint
- Create base classes to be used on specific extensions to deliver this feature.
https://oat-sa.atlassian.net/browse/CON-12

create resource relations proxy

---

composer.json
manifest.php

Work under [CGF-22](https://oat-sa.atlassian.net/browse/CGF-22)

Bump npm bridge version to make it compatible with composer 2.0

---

composer.json
manifest.php

Reverts oat-sa/tao-core#2734 to unblock tao update/install

Revert "Bump npm bridge version to make it compatible with composer 2.0"

---

manifest.php
models/classes/theme/ConfigurablePlatformTheme.php

**Related to task:**  https://oat-sa.atlassian.net/browse/CGF-164
**Description:** The TT and Guest pages are entirely blank

Fix/cgf 164/the tt and guest pages are entirely blank

---

manifest.php
models/classes/Lists/Business/Domain/ValueCollectionSearchRequest.php
models/classes/Lists/Business/Service/ValueCollectionService.php
models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
test/unit/models/classes/Lists/Business/Domain/ValueCollectionSearchRequestTest.php
test/unit/models/classes/Lists/Business/Service/ValueCollectionServiceTest.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

ticket : https://oat-sa.atlassian.net/browse/CON-316
fix: added dataLanguage for lists
blocker for  : https://github.com/oat-sa/extension-tao-backoffice/pull/98

Fix/con 316/lists default language

---

manifest.php
models/classes/Lists/Business/Domain/ValueCollectionSearchRequest.php
models/classes/Lists/Business/Service/ValueCollectionService.php
models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
models/classes/theme/ConfigurablePlatformTheme.php
test/unit/models/classes/Lists/Business/Domain/ValueCollectionSearchRequestTest.php
test/unit/models/classes/Lists/Business/Service/ValueCollectionServiceTest.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

Release 46.8.3

---

manifest.php
models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

Release 46.8.4

---

manifest.php
views/package-lock.json
views/package.json

**Dependency PR**
https://github.com/oat-sa/tao-core-ui-fe/pull/230
**Another related PR**
https://github.com/oat-sa/extension-tao-itemqti/pull/1600

[Fix] CON 122 - Graphic design match mockup

---

manifest.php
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/CON-185
Updated "@oat-sa/tao-core-ui": "1.20.2": fixed issues with loading subfolders
How to test:
- go to item Authoring
- add A-block
- click image in extend editor
- in resource manager select subfolders with pagination
- check that pages rendered correctly

fix/CON-185/ Resource manager - select and load subfolders 

---

actions/class.Health.php
config/default/ApplicationService.conf.php
install/class.Installator.php
install/class.Setup.php
install/utils/class.ConfigWriter.php
manifest.php
migrations/Version202012300805132234_tao.php
models/classes/service/ApplicationService.php

Tao health check not just checks that Tao is installed but also that all the post install scripts were executed and installation was finished and Tao is ready to be used.

Feature/cgf 179/tao health check

---

manifest.php
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/CON-30
https://github.com/oat-sa/extension-tao-mediamanager/pull/248
https://github.com/oat-sa/extension-tao-test-preview-ui-loader/pull/17
https://github.com/oat-sa/extension-tao-itemqti/pull/1610
https://github.com/oat-sa/tao-item-runner-qti-fe/pull/140
Update update @oat-sa/tao-core-ui to 1.22.0

Feature/CON-30/support responsive video 

---

models/classes/task/migration/service/ResultFilterFactory.php
models/classes/task/migration/service/SpawnMigrationConfigService.php
scripts/tools/index/IndexPopulator.sh
test/unit/models/classes/task/migration/service/ResultFilterFactoryTest.php
test/unit/models/classes/task/migration/service/SpawnMigrationConfigServiceTest.php

Extend migration tasks configs
Ticket: https://oat-sa.atlassian.net/browse/CON-256

Extend migration tasks configs

---

manifest.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

fix: tests fix

---

models/classes/Lists/Business/Service/ClassMetadataService.php
scripts/install/RegisterClassMetadataServices.php

Fix broken installation process
https://oat-sa.atlassian.net/browse/CON-496

Fix registration process

---

manifest.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

fix: fix tests

---

README.md
models/classes/webhooks/WebhookRegistryManager.php
models/classes/webhooks/WebhookRegistryManagerInterface.php
models/classes/webhooks/configEntity/Webhook.php
scripts/tools/RegisterEventWebhook.php
test/unit/webhooks/WebhookRegistryManagerTest.php

Allow to add configuration to WebHookService.
https://oat-sa.atlassian.net/browse/AUT-16

feat: AUT-16 webhook entry registry manager

---

install/class.Installator.php

**Related PR:** [oat-sa/generis#874](https://github.com/oat-sa/generis/pull/874)
**Changes:** define the ROOT_URL constant with the right value at the beginning of the installation, because it can be used in manifest files.

fix: define ROOT_URL constant at the beginning of the installation

---

views/package-lock.json
views/package.json

**Relates to:** [AUT-15](https://oat-sa.atlassian.net/browse/AUT-15)
**Changes:** `@oat-sa/tao-core-sdk` version was increased from 1.8.1 to 1.9.0.

chore: bump tao-core-sdk version

---

manifest.php

Release 47.1.1

---

composer.json

Release 47.1.3

---

views/package-lock.json

Fixes build affected by #2819.

fix: package-lock.json dependency paths

---

views/package-lock.json

Release 47.1.5

---

.github/workflows/release.yml

Release 47.1.8

---

views/package-lock.json
views/package.json

**Related to task:**  https://oat-sa.atlassian.net/browse/MS-1061
**Description:** Update tao core

fix/MS-1061/ Update tao-core-ui

---

manifest.php
models/classes/websource/BaseWebsource.php

Related to: https://oat-sa.atlassian.net/browse/TR-907
Backport of #2822

Hotfix/tr 552/fix javascript asset mime type

---

models/classes/Lists/Business/Service/ClassMetadataService.php
scripts/install/RegisterClassMetadataServices.php

https://oat-sa.atlassian.net/browse/ADF-114
Dead code and unused var that triggers error - removed

fix: dead code removed

---

.github/workflows/release.yml

ci: use github action for autorelease

---

.github/workflows/release.yml

Release 48.0.5

---

models/classes/security/xsrf/TokenService.php
test/unit/model/security/xsrf/TokenServiceTest.php

Release 48.0.6

---

views/package-lock.json
views/package.json

**Related to task:**  https://oat-sa.atlassian.net/browse/MS-1071
**Description:** Contains bug fixes for multi highlighter feature

fix/MS-1071/Update tao-core-ui

---

scripts/uninstallExtension.php

Allow uninstall extension via command line

feat: add new command to uninstall extension

---

scripts/uninstallExtension.php

Release 48.1.0

---

models/classes/search/GenerisSearchBridge.php
models/classes/search/strategy/GenerisSearch.php
test/unit/models/classes/search/GenerisSearchBridgeTest.php

Allow Generis search by URI
https://oat-sa.atlassian.net/browse/ADF-268

fix: add search by URI

---

models/classes/search/GenerisSearchBridge.php
test/unit/models/classes/search/GenerisSearchBridgeTest.php

Release 48.1.1

---

models/classes/resources/ResourceWatcher.php
test/unit/models/classes/resources/ResourceWatcherTest.php

https://oat-sa.atlassian.net/browse/ADF-270

Fix/adf 270/feature flag for advanced search event

---

models/classes/resources/ResourceWatcher.php
test/unit/models/classes/resources/ResourceWatcherTest.php

Release 48.1.2

---

views/package-lock.json
views/package.json

New version introduce core/mimetype/definitions file that is required by taoQtiItems.
https://oat-sa.atlassian.net/browse/AUT-2

taoc-core-sdk required at version ^1.12.0

---

views/package-lock.json

Release 48.1.4

---

models/classes/search/GenerisSearchBridge.php
test/unit/models/classes/search/GenerisSearchBridgeTest.php

chore: fix proxy test by injection local namespace

chore: fix proxy test by injection local namespace

---

models/classes/search/GenerisSearchBridge.php
test/unit/models/classes/search/GenerisSearchBridgeTest.php

Release 48.1.5

---

README.md
actions/class.Main.php
actions/class.RdfController.php
actions/class.Users.php
manifest.php
migrations/Version202104190709392234_tao.php
models/classes/accessControl/ActionAccessControl.php
scripts/install/RegisterActionAccessControl.php
scripts/tools/accessControl/SetRolesAccess.php
test/unit/accessControl/ActionAccessControlTest.php

Release 48.3.0

---

actions/class.UserSettings.php

Additional fix for commented in [AUT-342](https://oat-sa.atlassian.net/browse/AUT-342?focusedCommentId=131312) just another place found to be escaped in user management.
more info in previous PR: https://github.com/oat-sa/tao-core/pull/2880

Fix/aut 342/additional html injection fix for user label

---

actions/class.UserSettings.php

Release 48.3.2

---

models/classes/GenerisTreeFactory.php
views/js/layout/tree/provider/jstree.js

Fix ACL permissions to create passage when selecting an asset
https://oat-sa.atlassian.net/browse/ADF-311
Can be tested on http://test-gabriel.playground.kitchen.it.taocloud.org:42221/ 
admin/admin
Related PRs

Fix ACL permissions to create passage when selecting an asset

---

models/classes/security/xsrf/TokenService.php
models/classes/security/xsrf/TokenStoreSession.php

Release 48.3.6

---

views/package-lock.json
views/package.json

Jira
https://oat-sa.atlassian.net/browse/ADF-210
PR
https://github.com/oat-sa/tao-core-ui-fe/pull/296
This PR is just to bump the npm dependency version

fix: ADF-210 use criteria id instead of label for selectors and name attribute

---

actions/class.Search.php
config/default/search.conf.php
manifest.php
migrations/Version202106010945122237_tao.php
models/classes/AdvancedSearch/AdvancedSearchChecker.php
models/classes/search/ElasticSearchBridge.php
models/classes/search/IdentifierSearcher.php
models/classes/search/SearchInterface.php
models/classes/search/SearchProxy.php
models/classes/search/SearchQuery.php
models/classes/search/strategy/GenerisSearch.php
models/classes/user/GenerisUserService.php
scripts/install/RegisterSearchServices.php
test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
test/unit/models/classes/search/IdentifierSearchTest.php
test/unit/models/classes/search/SearchProxyTest.php
test/unit/user/GenerisUserServiceTest.php

Release 48.7.0

---

config/default/search.conf.php

fix: use class instance instead of constant

fix: use class instance instead of constant

---

config/default/search.conf.php

Release 48.7.1

---

manifest.php

Release 48.9.1

---

actions/class.TaskQueueWebApi.php
migrations/Version202106010921112234_tao.php
models/classes/taskQueue/Queue.php
models/classes/taskQueue/Queue/Broker/AbstractQueueBroker.php
models/classes/taskQueue/Queue/Broker/InMemoryQueueBroker.php
models/classes/taskQueue/Queue/Broker/QueueBrokerInterface.php
models/classes/taskQueue/QueueInterface.php
models/classes/taskQueue/README.md
models/classes/taskQueue/TaskLog.php
models/classes/taskQueue/TaskLog/TaskLogFilter.php
models/classes/taskQueue/TaskLogInterface.php
scripts/install/SetUpQueueTasks.php

Release 48.10.0

---

actions/class.TaskQueueWebApi.php

https://oat-sa.atlassian.net/browse/ADF-456

fix: rollback to support multiple types of request parameter

---

actions/class.TaskQueueWebApi.php

Release 48.11.1

---

models/classes/Lists/Business/Service/ClassMetadataSearcherProxy.php

Fix class metadata searcher 
https://oat-sa.atlassian.net/browse/ADF-461

fix: fix typo

---

models/classes/Lists/Business/Service/ClassMetadataSearcherProxy.php

Release 48.11.2

---

actions/class.RdfController.php

Release 48.12.1

---

actions/class.TaskQueueData.php
composer.json
models/classes/taskQueue/TaskLog/Broker/AbstractTaskLogBroker.php
models/classes/taskQueue/TaskLog/Entity/TaskLogEntity.php

Release 48.13.0

---

views/package-lock.json
views/package.json

**Related to task:**  https://oat-sa.atlassian.net/browse/MS-1185
**Description:** Update highlighter feature to clear multicolor highlight.

feature/MS-1185/Update tao-core-ui

---

models/classes/task/migration/AbstractMigrationTask.php
models/classes/task/migration/service/MigrationConfigFactory.php
models/classes/task/migration/service/ResultFilterFactory.php
models/classes/task/migration/service/SpawnMigrationConfigService.php
scripts/tools/MigrationAction.php

feat: allow custom parameters to be forwarded
https://oat-sa.atlassian.net/browse/ADF-461

feat: allow custom parameters to be forwarded

---

models/classes/task/migration/AbstractMigrationTask.php
models/classes/task/migration/service/MigrationConfigFactory.php
models/classes/task/migration/service/ResultFilterFactory.php
models/classes/task/migration/service/SpawnMigrationConfigService.php
scripts/tools/MigrationAction.php

Release 48.14.0

---

views/package-lock.json
views/package.json

Jira
[https://oat-sa.atlassian.net/browse/ADF-471](https://oat-sa.atlassian.net/browse/ADF-471)
Related PRs
[oat-sa/tao-core-ui-fe#319](https://github.com/oat-sa/tao-core-ui-fe/pull/319)
Env
Link in the ticket

[FIX] ADF-471: Select button is disabled in upload style sheet modal

---

views/package-lock.json
views/package.json

This PR is to bump tao-core-ui version
**Jira**
https://oat-sa.atlassian.net/browse/ADF-479
**Env**
Check the ticket. Credentials for both roles are there
**Result**
**Other PRs**
https://github.com/oat-sa/tao-core-ui-fe/pull/322

[Fix] disabled select2 control match other disabled inputs

---

manifest.php

Release 48.14.7

---

models/classes/listener/ClassPropertiesChangedListener.php
models/classes/listener/ClassPropertyRemovedListener.php
models/classes/listener/DataAccessControlChangedListener.php
test/unit/model/listener/ClassPropertiesChangedListenerTest.php
test/unit/model/listener/ClassPropertyRemovedListenerTest.php
test/unit/model/listener/DataAccessControlChangedListenerTest.php

https://oat-sa.atlassian.net/browse/ADF-270

fix: prevents putting meaningless tasks into the queue

---

models/classes/listener/ClassPropertiesChangedListener.php
models/classes/listener/ClassPropertyRemovedListener.php
models/classes/listener/DataAccessControlChangedListener.php
test/unit/model/listener/ClassPropertiesChangedListenerTest.php
test/unit/model/listener/ClassPropertyRemovedListenerTest.php
test/unit/model/listener/DataAccessControlChangedListenerTest.php

Release 48.14.8

---

.gitignore
views/cypress.json
views/cypress/README.md
views/cypress/envs/env.sample
views/cypress/fixtures/example.json
views/cypress/plugins/index.js
views/cypress/support/commands.js
views/cypress/support/index.js
views/cypress/support/resourceTree.js
views/cypress/tests/login.spec.js
views/cypress/utils/urls.js
views/package-lock.json
views/package.json

Release 48.15.0

---

actions/class.RdfController.php
models/classes/accessControl/ActionAccessControl.php
test/unit/accessControl/ActionAccessControlTest.php

Release 48.15.1

---

models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php

https://oat-sa.atlassian.net/browse/ADF-515

fix: collections of Literals should be searchable

---

models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php

Release 48.15.2

---

models/classes/search/SearchProxy.php
test/unit/models/classes/search/SearchProxyTest.php

Search by URI must return result
https://oat-sa.atlassian.net/browse/ADF-268

Search by URI must return result

---

models/classes/search/SearchProxy.php
test/unit/models/classes/search/SearchProxyTest.php

Release 48.15.3

---

actions/class.Main.php
config/default/ActionBlackList.conf.php
migrations/Version202107131252262234_tao.php
models/classes/action/ActionBlackList.php
test/unit/models/classes/action/ActionBlackListTest.php

This was caused by ticket [AUT-553](https://oat-sa.atlassian.net/browse/AUT-553) that required to add new action on class context that will be disabled unless feature flag is enabled. 
https://oat-sa.atlassian.net/browse/AUT-790

This feature will allow to disable any action in TAO using ConfigurableService. option or environment variable

---

actions/class.Main.php
config/default/ActionBlackList.conf.php
migrations/Version202107131252262234_tao.php
models/classes/action/ActionBlackList.php
test/unit/models/classes/action/ActionBlackListTest.php

Release 48.16.0

---

models/classes/action/ActionBlackList.php

fix: Introduced service when no option is configured causing fatal error

fix: options cast to array

---

models/classes/action/ActionBlackList.php

Release 48.16.1

---

actions/class.RdfController.php
models/classes/event/ResourceMovedEvent.php
test/unit/models/classes/event/ResourceMovedEventTest.php

Release 48.17.0

---

views/cypress/support/commands.js
views/cypress/utils/helpers.js
views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/TR-1080
**Requires:**
- Add the support for the LTI commands.
- Add a command to log in as a user, and refactor the `loginAsAdmin()` command
- Add a helper to get full url, taking of the baseUrl if needed (useful to build some url like for the LTI parameters)

Feature/TR-1080/Support LTI calls in E2E

---

views/cypress/utils/helpers.js
views/package-lock.json
views/package.json

Release 48.18.0

---

actions/class.RdfController.php

Release 48.18.1

---

views/package-lock.json
views/package.json

**Ticket**
https://oat-sa.atlassian.net/browse/ADF-475

[Fix] [Advanced search]: Properties containing space at the end of Label are not found

---

actions/class.RdfController.php
models/classes/accessControl/ActionAccessControl.php
test/unit/accessControl/ActionAccessControlTest.php

Backport [ADF-532](https://oat-sa.atlassian.net/browse/ADF-532)
https://github.com/oat-sa/tao-core/pull/2992/commits

Fix/adf 532/backport fix dac annotation

---

actions/class.Import.php
actions/class.RdfController.php

Release 48.18.4

---

views/cypress.json
views/cypress/support/commands.js
views/cypress/support/userManagement.js
views/cypress/tests/item-author-role.spec.js
views/cypress/tests/login.spec.js
views/cypress/tests/test-author-role.spec.js
views/cypress/tests/test-taker-role.spec.js
views/cypress/tests/user-management.spec.js
views/cypress/utils/cleanup.js
views/cypress/utils/selectors.js
views/cypress/utils/urls.js
views/cypress/utils/userRoles.js
views/cypress/utils/users.js

Release 48.19.0

---

models/classes/search/SearchTokenGenerator.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php
test/unit/models/classes/search/index/GenerisIndexDocumentBuilderTest.php
test/unit/models/classes/search/index/IndexServiceTest.php
views/package-lock.json
views/package.json

This PR links tao-core-ui-fe to a proper branch with a fix to be able to deploy fe changes for testing
https://oat-sa.atlassian.net/browse/ADF-570

fix: use uri in advanced search criteria

---

actions/class.CommonModule.php
helpers/form/class.FormContainer.php
models/classes/accessControl/ActionAccessControl.php
models/classes/media/mapper/MediaBrowserPermissionsMapper.php

Relates to https://oat-sa.atlassian.net/browse/ADF-208

chore: add function to get User role

---

actions/class.CommonModule.php
models/classes/accessControl/ActionAccessControl.php
models/classes/media/mapper/MediaBrowserPermissionsMapper.php

Release 48.19.2

---

actions/class.CommonModule.php

Release 48.20.2

---

views/cypress/support/resourceTree.js

Release 48.21.0

---

views/package-lock.json
views/package.json

**Ticket**
https://oat-sa.atlassian.net/browse/ADF-542
**Related PR's**
https://github.com/oat-sa/extension-tao-itemqti/pull/1846
https://github.com/oat-sa/tao-core-ui-fe/pull/338

[Fix][ADF-542]: Add min/max outcome values validation

---

actions/class.PropertiesAuthoring.php

Release 48.25.1

---

scripts/install/CreateRdsListStore.php

Release 48.27.1

---

views/templates/blocks/header-main-navi.tpl

Release 48.27.2

---

models/classes/GenerisServiceTrait.php
models/classes/event/ClassMovedEvent.php
models/classes/search/index/IndexIterator.php
models/classes/search/tasks/UpdateClassInIndex.php

Release 48.27.3

---

views/package-lock.json
views/package.json

https://oat-sa.atlassian.net/browse/ADF-542
commit 440105cfe5352b9c4b03905911516c3188cf3863
Author: Juan Luis Gutierrez Dos Santos <juanluis.gutierrezdossantos@taotesting.com>
Date:   Tue Aug 10 10:22:32 2021 +0200
chore: Update proper version

Backport/ADF-542/Add min-max outcome values validation

---

models/classes/Lists/Business/Service/GetClassMetadataValuesService.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php

`List Single Choice Search Input` must appear as a criteria filter
https://oat-sa.atlassian.net/browse/ADF-344

fix: allow search dropdown to be indexed as list property

---

models/classes/Lists/Business/Service/GetClassMetadataValuesService.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php

Release 48.27.5

---

helpers/form/class.FormFactory.php
helpers/form/elements/xhtml/class.Button.php
helpers/form/elements/xhtml/class.Checkbox.php
helpers/form/elements/xhtml/class.Combobox.php
helpers/form/elements/xhtml/class.Date.php
helpers/form/elements/xhtml/class.File.php
helpers/form/elements/xhtml/class.Hiddenbox.php
helpers/form/elements/xhtml/class.Htmlarea.php
helpers/form/elements/xhtml/class.Password.php
helpers/form/elements/xhtml/class.Radiobox.php
helpers/form/elements/xhtml/class.Readonly.php
helpers/form/elements/xhtml/class.ReadonlyLiteral.php
helpers/form/elements/xhtml/class.Textarea.php
helpers/form/elements/xhtml/class.Textbox.php
test/unit/helpers/form/FormContainerTest.php
views/cypress/support/resourceTree.js

Release 48.28.0

---

migrations/Version202108261748123245_tao.php

https://oat-sa.atlassian.net/browse/CGF-427
Japanese translations fixed for already existing instances

fix: ontology models to fix Japanese translations for existing instances

---

actions/form/class.EditClassLabel.php
config/default/NamespaceHelper.conf.php
config/default/namespace.conf.php
helpers/NamespaceHelper.php
test/unit/helpers/NamespaceHelperTest.php

1046/user cannot edit class label dev

Fix/aut 1046/user cannot edit class label dev

---

actions/form/class.EditClassLabel.php
config/default/NamespaceHelper.conf.php
helpers/NamespaceHelper.php
test/unit/helpers/NamespaceHelperTest.php

Release 48.32.0

---

models/classes/search/SearchTokenGenerator.php
models/classes/search/index/OntologyIndex.php
models/classes/search/tokenizer/ResourceClasses.php
test/unit/models/classes/search/tokenizer/ResourceClassesTest.php

-- WIP --
Bring resources in the search if typing class label
https://oat-sa.atlassian.net/browse/ADF-15

fix: index parent classes labels

---

models/classes/search/SearchTokenGenerator.php
models/classes/search/index/OntologyIndex.php
models/classes/search/tokenizer/ResourceClasses.php
test/unit/models/classes/search/tokenizer/ResourceClassesTest.php

Release 48.32.1

---

views/package-lock.json
views/package.json

**Ticket**
https://oat-sa.atlassian.net/browse/ADF-669

Tabular Import: Report does not appear and the environment gets stuck when Import item via CSV with partially successful result

---

scripts/install/SetImageAligmentConfig.php

Regression issue from https://github.com/oat-sa/tao-core/pull/3041
```
[2021-09-06 12:23][info]      Installing extension tao
Notice: Undefined index: mediaAlignment in /var/www/html/tao/scripts/install/SetImageAligmentConfig.php on line 47
Notice: Undefined index: mediaAlignment in /var/www/html/tao/scripts/install/SetImageAligmentConfig.php on line 51
```
Fix: set default $mediaAligment value

fix error Undefined index: mediaAlignment in SetImageAligmentConfig.php script

---

scripts/install/SetImageAligmentConfig.php

Release 48.32.3

---

views/package-lock.json
views/package.json

The E2E runner was placed at a wrong place in the dependencies. It is a development dependency, and as such it should be placed at the `devDependencies` section.

Fix/Move the E2E runner to devDependencies

---

views/package-lock.json
views/package.json

Release 48.32.4

---

views/cypress.json
views/cypress/support/commands.js
views/cypress/support/resourceTree.js
views/cypress/support/userManagement.js
views/cypress/tests/item-author-role.spec.js
views/cypress/tests/test-author-role.spec.js
views/cypress/tests/test-taker-role.spec.js
views/cypress/tests/user-management.spec.js
views/cypress/utils/cleanup.js

Release 48.33.1

---

actions/form/class.EditClassLabel.php
config/default/NamespaceHelper.conf.php
config/default/namespace.conf.php
helpers/NamespaceHelper.php
migrations/Version202109101332292234_tao.php
test/unit/helpers/NamespaceHelperTest.php

Fix/aut 1046/adding back edit label feature

---

actions/form/class.EditClassLabel.php
config/default/NamespaceHelper.conf.php
helpers/NamespaceHelper.php
migrations/Version202109101332292234_tao.php
test/unit/helpers/NamespaceHelperTest.php

Release 48.34.0

---

README.md
composer.json
config/default/MiddlewareRequestHandler.conf.php
config/default/OpenAPISchemaValidateRequestMiddleware.conf.php
migrations/Version202109081902202234_tao.php
models/classes/Middleware/Context/MiddlewareContext.php
models/classes/Middleware/Context/OpenApiMiddlewareContext.php
models/classes/Middleware/MiddlewareManager.php
models/classes/Middleware/MiddlewareRequestHandler.php
models/classes/Middleware/OpenAPISchemaValidateRequestMiddleware.php
models/classes/Middleware/README.md
models/classes/routing/ActionEnforcer.php

Release 48.35.0

---

models/classes/taskQueue/TaskLog/Broker/RdsTaskLogBroker.php

Release 48.35.1

---

manifest.php

After release code freeze we should always check that we increase release version.

chore: update tao-platform version

---

manifest.php

Release 48.35.2

---

views/cypress/support/commands.js
views/cypress/support/resourceTree.js

Release 48.35.3

---

views/cypress/plugins/downloads.js
views/cypress/plugins/index.js
views/cypress/support/commands.js
views/cypress/support/resourceTree.js
views/package-lock.json
views/package.json

**Related to:** https://oat-sa.atlassian.net/browse/AUT-969
Added import items tests
**How to test:**
- Run items import/export test

Task/aut 969/export item

---

views/cypress/plugins/downloads.js
views/cypress/plugins/index.js
views/cypress/support/commands.js
views/cypress/support/resourceTree.js
views/package-lock.json
views/package.json

Release 48.38.0

---

actions/class.ExtensionsManager.php
composer.json
install/class.Installator.php
models/classes/http/Controller.php
models/classes/service/InjectionAwareService.php
scripts/installExtension.php
scripts/taoUpdate.php
scripts/uninstallExtension.php

Release 48.39.0

---

views/cypress/support/resourceTree.js

Release 48.39.1

---

views/cypress/support/commands.js
views/cypress/support/drag-and-drop.js
views/cypress/support/file-upload.js
views/cypress/support/resourceTree.js

Release 48.40.0

---

views/cypress/support/resourceTree.js

Release 48.40.1

---

views/cypress/support/commands.js
views/cypress/support/manageSchema.js
views/cypress/support/resourceProperties.js
views/cypress/support/resourceTree.js
views/cypress/utils/selectors.js

Release 48.41.1

---

models/classes/validator/PropertyChangedValidator.php
test/unit/model/validator/PropertyChangedValidatorTest.php

Release 48.41.3

---

actions/class.PropertiesAuthoring.php
models/classes/ClassProperty/RemoveClassPropertyService.php
models/classes/Lists/Business/Contract/DependencyRepositoryInterface.php
models/classes/Lists/DataAccess/Repository/DependencyRepository.php
models/classes/Lists/DataAccess/Repository/DependsOnPropertyRepository.php
models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
test/unit/models/classes/Lists/DataAccess/Repository/DependencyRepositoryTest.php
test/unit/models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepositoryTest.php
test/unit/models/classes/Lists/DataAccess/Repository/ParentPropertyListRepositoryTest.php

Release 48.42.0

---

views/cypress/support/selection.js

Related to: https://oat-sa.atlassian.net/browse/AUT-964
Added command `selectTextWithin` needed for item Authoring https://github.com/oat-sa/extension-tao-itemqti/pull/1904
**How to test:**
- run cypress from tao/views 
- check test `taoQtiItem/views/cypress/tests/item-authoring-set-response.spec.js`

feat/AUT-964/ e2e added selectTextWithin command

---

views/cypress/support/selection.js

Release 48.43.0

---

views/package-lock.json
views/package.json

**Jira issue**
https://oat-sa.atlassian.net/browse/ADF-695
**Related PR**
https://github.com/oat-sa/tao-core-ui-fe/pull/368
**AC**
- Preselect item gallery when user doesn't have access to Assets.
- Preselect Assets when user does have access.
- Make "Add file" button appear without having to click a folder. (If permissions allow it).
**How to test**
- Make access to Assets forbidden for user. (By restricting access only to Global Manager role) (make it recursive)
- Login with user and author an item
- Try to insert media/image

CUNO-1853 / ADF-695: User without access to assets can save images trough the item

---

composer.json
helpers/form/Decorator/ElementDecorator.php
helpers/form/ElementMapFactory.php
helpers/form/class.FormElement.php
helpers/form/elements/AbstractSearchElement.php
helpers/form/validators/PreliminaryValidationInterface.php
helpers/form/xhtml/class.Form.php
models/classes/Lists/Business/Domain/ValueCollectionSearchRequest.php
models/classes/Lists/Business/Validation/DependsOnPropertyValidator.php
models/classes/Lists/DataAccess/Repository/DependsOnPropertyRepository.php
models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
models/classes/Lists/Presentation/Web/Factory/DependsOnPropertyFormFieldFactory.php
models/classes/Lists/ServiceProvider/ListsServiceProvider.php
test/unit/helpers/form/Decorator/ElementDecoratorTest.php
test/unit/models/classes/Lists/Business/Domain/ValueCollectionSearchRequestTest.php
test/unit/models/classes/Lists/Business/Validation/DependsOnPropertyValidatorTest.php
test/unit/models/classes/Lists/DataAccess/Repository/DependsOnPropertyRepositoryTest.php
test/unit/models/classes/Lists/Presentation/Web/Factory/DependsOnPropertyFormFieldFactoryTest.php

Release 48.54.0

---

helpers/TreeHelper.php

Release 48.54.1

---

actions/form/class.Clazz.php

Use NamespaceHelper to allow predefined namespace propertie to edit resource. 
https://oat-sa.atlassian.net/browse/AUT-1171

fix: apply namespace helper to allow class properties editing

---

actions/form/class.Clazz.php

Release 48.54.2

---

views/cypress/support/manageSchema.js
views/cypress/support/resourceProperties.js

**Ticket**
https://oat-sa.atlassian.net/browse/ADF-779
**Related PR's**
https://github.com/oat-sa/extension-tao-item/pull/544
https://github.com/oat-sa/extension-tao-test/pull/405

[Task] ADF-779: E2E Metadata - Validate property fields

---

views/cypress/support/manageSchema.js
views/cypress/support/resourceProperties.js

Release 48.55.0

---

composer.json
scripts/tools/e2e/PrepareEnvironment.php
scripts/tools/e2e/models/E2eConfigDriver.php

Release 48.56.0

---

manifest.php
models/classes/Lists/Business/Specification/LocalListClassSpecification.php
models/classes/Lists/ServiceProvider/ListsServiceProvider.php
models/classes/export/JsonLdExport.php
models/classes/export/Metadata/JsonLd/JsonLdBasicTripleEncoder.php
models/classes/export/Metadata/JsonLd/JsonLdListTripleEncoder.php
models/classes/export/Metadata/JsonLd/JsonLdTripleEncoderInterface.php
models/classes/export/Metadata/JsonLd/JsonLdTripleEncoderProxy.php
models/classes/export/ServiceProvider/MetadataServiceProvider.php
test/unit/models/classes/export/JsonLdExportTest.php
test/unit/models/classes/export/Metadata/JsonLdBasicTripleEncoderTest.php
test/unit/models/classes/export/Metadata/JsonLdListTripleEncoderTest.php
test/unit/models/classes/export/Metadata/JsonLdTripleEncoderProxyTest.php

Release 48.58.0

---

helpers/form/elements/xhtml/AbstractXhtmlSearchElement.php

Release 48.58.1

---

views/js/uiForm.js

**Ticket**
https://oat-sa.atlassian.net/browse/ADF-794

GREP: Informative warning message when removing a property on a dependency

---

views/package-lock.json
views/package.json

https://oat-sa.atlassian.net/browse/REL-472

Update ui core library with fixed translation

---

actions/class.RestResource.php
actions/class.RestTrait.php
composer.json

https://oat-sa.atlassian.net/browse/ADF-840
Testing locally:
1) Create access credentials:
```
php index.php '\oat\taoOauth\scripts\tools\GenerateCredentials' -r http://www.tao.lu/Ontologies/TAO.rdf#GlobalManagerRole
```
2) Try to create item, etc or any other rest API operation: Should work normally.
3) Try to provide invalid data to API and we should have error in the logs.

feat: log rest api errors

---

actions/class.RestResource.php
actions/class.RestTrait.php
composer.json

Release 48.61.0

---

actions/form/class.Instance.php
helpers/form/ElementMapFactory.php

Release 48.61.1

---

views/cypress/support/manageSchema.js

Release 48.62.0

---

composer.json
models/classes/accessControl/AccessControl.php
models/classes/accessControl/ActionAccessControl.php
models/classes/accessControl/data/DataAccessControl.php
models/classes/accessControl/func/FuncAccessControl.php
models/classes/accessControl/func/implementation/NoAccess.php
models/classes/accessControl/func/implementation/SimpleAccess.php
models/classes/menu/ActionService.php
models/classes/resources/SecureResourceService.php
models/classes/routing/RouteAnnotationService.php

* Added new log information
* Updated old log information
* Small code refactoring
* https://github.com/oat-sa/generis/pull/943
* https://github.com/oat-sa/extension-tao-funcacl/pull/97

Feature/ADF-525/Improve ACL logs

---

composer.json
models/classes/accessControl/AccessControl.php
models/classes/accessControl/ActionAccessControl.php
models/classes/accessControl/data/DataAccessControl.php
models/classes/accessControl/func/FuncAccessControl.php
models/classes/accessControl/func/implementation/NoAccess.php
models/classes/accessControl/func/implementation/SimpleAccess.php
models/classes/menu/ActionService.php
models/classes/resources/SecureResourceService.php
models/classes/routing/RouteAnnotationService.php

Release 48.63.0

---

models/classes/media/TaoMediaResolver.php
models/classes/media/sourceStrategy/InlineSource.php
test/unit/models/classes/media/InlineSourceTest.php

Release 48.64.0

---

helpers/form/elements/xhtml/AbstractXhtmlSearchElement.php
views/cypress/support/CKEditor.js
views/cypress/support/commands.js
views/cypress/support/manageSchema.js
views/cypress/support/resourceProperties.js

https://oat-sa.atlassian.net/browse/ADF-834
Related PR: https://github.com/oat-sa/extension-tao-item/pull/552
Create a test to cycle through simple type properties and validate them

[Feat] ADF-834 E2E: properties with simple types

---

helpers/form/elements/xhtml/AbstractXhtmlSearchElement.php
views/cypress/support/CKEditor.js
views/cypress/support/commands.js
views/cypress/support/manageSchema.js
views/cypress/support/resourceProperties.js

Release 48.65.0

---

manifest.php

Related to: https://oat-sa.atlassian.net/browse/AUT-1521
Update version to 2022.01

chore: update TAO_VERSION to 2022.01

---

manifest.php

Release 48.66.1

---

views/cypress/support/resourceTree.js

Release 48.66.2

---

test/unit/accessControl/ActionAccessControlTest.php
test/unit/model/routing/RouteAnnotationServiceTest.php
test/unit/models/classes/resources/SecureResourceServiceTest.php

Release 48.66.5

---

helpers/form/AbstractFeatureFlagFormPropertyMapper.php

Release 48.66.6

---

README.md
actions/class.Languages.php
composer.json
manifest.php
models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
models/classes/controllerMap/ControllerDescription.php
models/classes/http/Controller.php
models/classes/routing/ActionEnforcer.php
models/classes/routing/Contract/ActionFinderInterface.php
models/classes/routing/Contract/ActionInterface.php
models/classes/routing/README.md
models/classes/routing/Service/ActionFinder.php
models/classes/routing/ServiceProvider/RoutingServiceProvider.php
test/unit/model/routing/Service/ActionFinderTest.php

Release 48.68.0

---

actions/class.RdfController.php
composer.json
models/classes/ClassServiceTrait.php
models/classes/Context/AbstractContext.php
models/classes/Context/ContextInterface.php
models/classes/resources/Exception/ClassDeletionException.php
models/classes/resources/Exception/PartialClassDeletionException.php
models/classes/resources/ResourcesServiceProvider.php
models/classes/resources/Service/ClassDeleter.php
test/unit/model/ClassServiceTest.php
test/unit/models/classes/Lists/Business/Specification/RemoteListClassSpecificationTest.php
test/unit/models/classes/resources/Service/ClassDeleterTest.php

Release 48.70.0

---

views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/AUT-1300
Depends on:
Added async callback `checkAndCallAdd`

feat/AUT-1300/adder new async callback checkAndCallAdd

---

models/classes/routing/Service/ActionFinder.php

- Validate if reflection class has constructor before trying to get parameters

fix: validate if class has contructor

---

models/classes/routing/Service/ActionFinder.php

Release 48.71.1

---

helpers/form/elements/xhtml/class.AsyncFile.php
helpers/form/elements/xhtml/class.GenerisAsyncFile.php

Related to [REL-470](https://oat-sa.atlassian.net/browse/REL-470)
It fixes missed modules for translation in dynamically generated javascript code.

Fix missed i18n module

---

helpers/form/elements/xhtml/class.AsyncFile.php
helpers/form/elements/xhtml/class.GenerisAsyncFile.php

Release 48.71.2

---

README.md
actions/class.Import.php
actions/class.MetadataImport.php
actions/structures.xml
helpers/form/class.Form.php
manifest.php
migrations/Version202112210823010101_tao.php
models/classes/import/Form/MetadataImportForm.php
models/classes/import/ImportHandlerHelperTrait.php
models/classes/import/Processor/ImportFileErrorHandlerInterface.php
models/classes/import/Processor/ImportFileProcessorInterface.php
models/classes/import/ServiceProvider/ImportServiceProvider.php
models/classes/import/service/AgnosticImportHandler.php
models/classes/task/ImportByHandler.php
models/classes/upload/UploadService.php
test/unit/import/Form/MetadataImportFormTest.php
test/unit/import/service/AgnosticImportHandlerTest.php
test/unit/models/classes/upload/UploadServiceTest.php
views/templates/form/import.tpl

Release 48.72.0

---

migrations/Version202112211127582234_tao.php
models/classes/Lists/Business/Domain/ValueCollection.php
models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
models/classes/Lists/DataAccess/Repository/ValueConflictException.php
scripts/install/CreateRdsListStore.php
test/unit/models/classes/Lists/Business/Domain/ValueCollectionTest.php

Release 48.73.0

---

models/classes/Lists/Business/Service/ValueCollectionService.php

**Associated Jira issue:** [ADF-788]( https://oat-sa.atlassian.net/browse/ADF-788)
Feature needed by https://github.com/oat-sa/extension-tao-backoffice/pull/121

feat: Optional test for max number of items in ValueCollectionService::persist()

---

models/classes/Lists/Business/Service/ValueCollectionService.php

Release 48.74.0

---

views/package-lock.json
views/package.json

Release 48.75.1

---

views/cypress/support/index.js
views/cypress/support/resourceTree.js
views/cypress/support/search.js
views/cypress/utils/selectors.js
views/cypress/utils/urls.js

Release 48.76.0

---

views/cypress/support/genericUIInteractions.js
views/cypress/support/index.js

Related to https://oat-sa.atlassian.net/browse/ADF-909
Part of https://github.com/oat-sa/extension-tao-backoffice/pull/125

feature/ADF-909 feat: add close modal e2e command

---

views/cypress/support/genericUIInteractions.js
views/cypress/support/index.js

Release 48.77.0

---

helpers/form/ElementMapFactory.php

Release 48.78.0

---

views/package-lock.json

Related to https://oat-sa.atlassian.net/browse/TR-3287
- remove the git protocol from the package-lock to prevent issues installing the direct dependency

chore: fix protocol in dependencies

---

views/cypress/support/search.js

Release 48.80.0

---

actions/class.RestController.php
helpers/RestExceptionHandler.php
helpers/class.Http.php
helpers/form/elements/xhtml/class.Calendar.php
models/classes/mvc/error/ExceptionInterpretor.php
models/classes/mvc/error/HtmlResponse.php
models/classes/mvc/error/ResponseAbstract.php

Release 48.81.0

---

views/templates/blocks/careers-js.tpl
views/templates/blocks/careers.tpl

Release 48.82.2

---

views/package-lock.json
views/package.json

Related to https://oat-sa.atlassian.net/browse/ADF-807
Dependency update for https://github.com/oat-sa/tao-core-ui-fe/pull/416#issue-825660345

fix/ADF-807: fix filtering by tags

---

views/package-lock.json
views/package.json

Related to: https://oat-sa.atlassian.net/browse/AUT-1427
How to test:
- go to test Authoring
- create 2 sections
- create inside 1st section 2 subsections
- delete 1st section and restore by clicking undo
- try to add subsection in 2nd section

fix/AUT-1427/databinder - rebind the model after undo

---

views/cypress/fixtures/math_grade_1_1642670091.rdf
views/cypress/support/index.js
views/cypress/support/manageList.js
views/cypress/support/manageSchema.js
views/cypress/support/resourceTree.js
views/cypress/utils/selectors/list.js
views/cypress/utils/urls.js

Release 48.84.0

---

models/classes/Lists/Business/Domain/ValueCollection.php
test/unit/models/classes/Lists/Business/Domain/ValueCollectionTest.php

Release 48.84.1

---

models/classes/Lists/Business/Domain/ValueCollection.php
test/unit/models/classes/Lists/Business/Domain/ValueCollectionTest.php

Backport ADF-915 - Allow create multiple list items
https://oat-sa.atlassian.net/browse/ADF-915

fix: avoid consider duplicated empty URIs

---

models/classes/taskQueue/Task/TaskLanguageLoader.php
models/classes/taskQueue/Task/TaskLanguageLoaderInterface.php
models/classes/taskQueue/Worker/AbstractWorker.php
test/unit/model/taskQueue/Worker/AbstractWorkerTest.php

Release 48.85.0

---

helpers/class.I18n.php
helpers/form/ElementMapFactory.php
locales/en-GB/lang.rdf
locales/en-US/lang.rdf
locales/es-ES/lang.rdf
locales/es-MX/lang.rdf
locales/fr-CA/lang.rdf
locales/fr-FR/lang.rdf
locales/ja-HS/lang.rdf
locales/ja-JP/lang.rdf
locales/ja-LE/lang.rdf
locales/ja-UE/lang.rdf
locales/nb-NO/lang.rdf
locales/nl-BE/lang.rdf
locales/nl-NL/lang.rdf
locales/nn-NO/lang.rdf
locales/se-NO/lang.rdf
locales/zh-CN/lang.rdf
locales/zh-TW/lang.rdf
migrations/Version202201281535482234_tao.php
models/classes/Language/AscendingLabelListSorterComparator.php
models/classes/Language/Business/Specification/LanguageClassSpecification.php
models/classes/Language/Service/LanguageListElementSortService.php
models/classes/LanguageServiceProvider.php
models/classes/Lists/Business/Contract/ListElementSorterComparatorInterface.php
models/classes/Lists/Business/Contract/ListElementSorterInterface.php
models/classes/Lists/ServiceProvider/ListsServiceProvider.php
test/unit/models/classes/Language/Business/Service/LanguageListElementSortServiceTest.php
test/unit/models/classes/Language/Business/Specification/LanguageListClassSpecificationTest.php
test/unit/models/classes/Lists/Business/Specification/EditableListClassSpecificationTest.php

Release 48.87.0

---

models/classes/dataBinding/class.GenerisInstanceDataBinder.php
models/classes/password/PasswordConstraintsService.php
models/classes/taskQueue/Task/TaskLanguageLoader.php
test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php

Release 48.87.1

---

manifest.php
models/classes/oauth/OauthService.php

Backport of https://github.com/oat-sa/tao-core/pull/3368 for https://oat-sa.atlassian.net/browse/TR-2754

[Backport] TR-2754/oauth-1-parameters-in-header

---

actions/class.UserSettings.php

Release 49.0.2

---

actions/class.PropertiesAuthoring.php

https://oat-sa.atlassian.net/browse/ADF-550
Remove wrong condition about depends on property to populate parameter

fix: populate property fields after request

---

actions/class.PropertiesAuthoring.php

Release 49.0.3

---

actions/form/class.SimpleProperty.php
composer.json
helpers/form/ElementMapFactory.php
helpers/form/class.FormElement.php
helpers/form/elements/xhtml/class.Calendar.php
models/classes/Csv/Resource/Reader.php
models/classes/StatisticalMetadata/Import/Extractor/MetadataPropertiesExtractor.php
models/classes/StatisticalMetadata/Import/Processor/ImportProcessor.php
models/classes/StatisticalMetadata/Import/Validator/MetadataPropertiesValidator.php
models/classes/dataBinding/class.GenerisInstanceDataBinder.php
test/unit/models/classes/StatisticalMetadata/Import/Extractor/MetadataPropertiesExtractorTest.php
test/unit/models/classes/StatisticalMetadata/Import/Processor/ImportProcessorTest.php
test/unit/models/classes/StatisticalMetadata/Import/Validator/MetadataPropertiesValidatorTest.php

Release 49.1.0

---

actions/class.Roles.php
composer.json
manifest.php
models/classes/accessControl/AccessControlServiceProvider.php
models/classes/accessControl/Service/DeleteRoleService.php
models/classes/accessControl/Service/InternalRoleSpecification.php
models/classes/class.RoleService.php
test/unit/models/classes/accessControl/Service/DeleteRoleServiceTest.php
test/unit/models/classes/accessControl/Service/InternalRoleSpecificationTest.php

Block edition of not writable roles
https://oat-sa.atlassian.net/browse/ADF-925
- https://github.com/oat-sa/generis/pull/974

fix: block edition of not writable roles

---

actions/class.Roles.php
composer.json
manifest.php
models/classes/accessControl/AccessControlServiceProvider.php
models/classes/accessControl/Service/DeleteRoleService.php
models/classes/accessControl/Service/InternalRoleSpecification.php
models/classes/class.RoleService.php
test/unit/models/classes/accessControl/Service/DeleteRoleServiceTest.php
test/unit/models/classes/accessControl/Service/InternalRoleSpecificationTest.php

Release 49.2.0

---

models/classes/export/implementation/CsvExporter.php

Release 49.2.2

---

README.md
manifest.php
models/classes/Observer/GCP/PubSubClientFactory.php
models/classes/Observer/GCP/PubSubObserver.php
models/classes/Observer/Log/LoggerObserver.php
models/classes/Observer/README.md
models/classes/Observer/ServiceProvider/ObserverServiceProvider.php
models/classes/Observer/Subject.php
models/classes/Observer/SubjectInterface.php
models/classes/StatisticalMetadata/DataStore/Compiler/StatisticalJsonResourceMetadataCompiler.php
models/classes/StatisticalMetadata/Import/Observer/ObserverFactory.php
models/classes/StatisticalMetadata/Import/Processor/ImportProcessor.php
models/classes/StatisticalMetadata/Import/Processor/NotifyImportService.php
models/classes/StatisticalMetadata/StatisticalMetadataServiceProvider.php
models/classes/metadata/ServiceProvider/MetadataServiceProvider.php
models/classes/metadata/compiler/AdvancedJsonResourceMetadataCompiler.php
test/unit/models/classes/Observer/GCP/PubSubClientFactoryTest.php
test/unit/models/classes/Observer/GCP/PubSubObserverTest.php
test/unit/models/classes/Observer/Log/LoggerObserverTest.php
test/unit/models/classes/Observer/SubjectTest.php
test/unit/models/classes/StatisticalMetadata/DataStore/Compiler/StatisticalJsonResourceMetadataCompilerTest.php
test/unit/models/classes/StatisticalMetadata/Import/Observer/ObserverFactoryTest.php
test/unit/models/classes/StatisticalMetadata/Import/Processor/ImportProcessorTest.php
test/unit/models/classes/StatisticalMetadata/Import/Processor/NotifyImportServiceTest.php
test/unit/models/classes/metadata/compiler/AdvancedJsonResourceMetadataCompilerTest.php

Release 49.4.0

---

models/classes/StatisticalMetadata/Import/Processor/NotifyImportService.php
test/unit/models/classes/StatisticalMetadata/Import/Processor/NotifyImportServiceTest.php

https://oat-sa.atlassian.net/browse/ADF-958
Store resources with uri to avoid duplication

fix: store resources with uri to avoid duplication

---

models/classes/StatisticalMetadata/Import/Processor/NotifyImportService.php
test/unit/models/classes/StatisticalMetadata/Import/Processor/NotifyImportServiceTest.php

Release 49.5.1

---

actions/class.Import.php
actions/class.MetadataImport.php
migrations/Version202202171146482234_tao.php
models/classes/task/UnrelatedResourceImportByHandler.php
models/classes/taskQueue/TaskLog.php
models/classes/taskQueue/TaskLog/Decorator/RedirectUrlEntityDecorator.php
models/classes/taskQueue/TaskLogInterface.php
scripts/install/SetUpQueueTasks.php
test/unit/model/taskQueue/TaskLog/Decorator/RedirectUrlEntityDecoratorTest.php
test/unit/model/taskQueue/TaskLogTest.php
test/unit/model/taskQueue/Worker/AbstractWorkerTest.php

Release 49.5.2

---

actions/form/class.Users.php
helpers/class.Display.php
helpers/form/Feeder/SanitizerValidationFeeder.php
helpers/form/Feeder/SanitizerValidationFeederInterface.php
helpers/form/ServiceProvider/FormServiceProvider.php
helpers/form/class.FormContainer.php
helpers/form/validators/class.Regex.php
models/classes/class.UserService.php
test/unit/helpers/form/Feeder/SanitizerValidationFeederTest.php

Release 49.6.0

---

composer.json
helpers/data/class.GenerisAdapterRdf.php
models/classes/export/class.RdfExporter.php
models/classes/import/class.RdfImporter.php

[REL-112: TAO CG EasyRDF PHP 7.4 Support](https://oat-sa.atlassian.net/browse/REL-112)
**ATTENTION** It is require generis to be released first with the merged pull request https://github.com/oat-sa/generis/pull/977

Update usage of EasyRdf library

---

composer.json
helpers/data/class.GenerisAdapterRdf.php
models/classes/export/class.RdfExporter.php
models/classes/import/class.RdfImporter.php

Release 49.7.0

---

views/package-lock.json
views/package.json

Related to https://oat-sa.atlassian.net/browse/TR-3071
Brings https://github.com/oat-sa/tao-core-sdk-fe/pull/130 to tao-core
To be tested along with the other PRs:
- https://github.com/oat-sa/tao-test-runner-qti-fe/pull/469
- https://github.com/oat-sa/tao-core-sdk-fe/pull/130
TODO :

Add a util to detect iOS browsers

---

views/cypress/support/resourceProperties.js
views/cypress/support/resourceTree.js

Related to https://oat-sa.atlassian.net/browse/ADF-835
Complimentary PR for https://github.com/oat-sa/extension-tao-item/pull/571

ADF-835 Add assign value to calendar cypress command

---

views/cypress/plugins/downloads.js
views/cypress/support/resourceTree.js

Release 50.3.0

---

models/classes/theme/ThemeService.php

Release 50.3.1

---

composer.json
controller/Middleware/MiddlewareConfig.php
manifest.php
models/classes/Middleware/MiddlewareManager.php
models/classes/Middleware/MiddlewareRequestHandler.php
models/classes/Middleware/README.md
models/classes/routing/ActionEnforcer.php

Release 50.6.0

---

views/build/Gruntfile.js
views/build/tasks/helpers/extensions.js

Release 50.6.4

---

actions/form/class.Instance.php
helpers/form/ElementMapFactory.php

Release 50.6.5

---

helpers/form/ElementMapFactory.php

Release 50.6.6

---

actions/form/class.Instance.php
helpers/form/ElementMapFactory.php

Backport for https://github.com/oat-sa/tao-core/pull/3467
Related ticket https://oat-sa.atlassian.net/browse/REL-665

[Backport] form label translation on edit form

---

models/classes/theme/LanguageAwareTheme.php
models/classes/theme/ThemeServiceAbstract.php
test/unit/models/classes/theme/ThemeServiceAbstractTest.php

Release 50.7.0

---

views/js/services/features.js
views/js/test/services/features/test.html
views/js/test/services/features/test.js

Release 50.8.0

---

views/package-lock.json

Fix `eve` package protocol to support new github rule.

fix: eve protocol change to support new github rule

---

manifest.php
models/classes/featureVisibility/FeatureVisibilityService.php
models/classes/featureVisibility/FeatureVisibilityServiceProvider.php
test/unit/featureVisibility/FeatureVisibilityServiceTest.php

Release 50.10.0

---

views/package-lock.json
views/package.json

* oat-sa/tao-core-sdk updated from 1.18.0 to 1.18.1

chore: update tao-core-sdk-fe from 1.18.0 to 1.18.1

---

views/package-lock.json
views/package.json

* Update tao-core-sdk from 1.16.3 to 1.16.3-1

[Hotfix][OATSD-1783] Use tokens from store

---

helpers/form/ElementMapFactory.php

Release 50.10.2

---

helpers/form/ElementMapFactory.php

[Backport] Checking empty value of label to avoid fatal errors

---

models/classes/featureVisibility/FeatureVisibilityService.php
test/unit/featureVisibility/FeatureVisibilityServiceTest.php

Release 50.10.3

---

models/classes/Lists/Business/Domain/ValueCollection.php
models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

Release 50.10.4

---

views/package-lock.json
views/package.json

Update tao-core-sdk to revert https://github.com/oat-sa/tao-core-sdk-fe/pull/135
https://github.com/oat-sa/tao-core-sdk-fe/pull/140

chore: update tao-core-sdk from 1.18.1 to 1.18.2

---

views/package-lock.json
views/package.json

Update tao-core-sdk to revert https://github.com/oat-sa/tao-core-sdk-fe/pull/135
https://github.com/oat-sa/tao-core-sdk-fe/pull/140

[Hotfix][50.5.5] Revert token store

---

views/package-lock.json
views/package.json

Update tao-core-sdk to revert https://github.com/oat-sa/tao-core-sdk-fe/pull/138

[Hotfix][49.3.6] Revert token store

---

views/package-lock.json
views/package.json

Update tao-core-sdk to revert https://github.com/oat-sa/tao-core-sdk-fe/pull/138

[Hotfix][49.3.1.2] Revert token store

---

views/package-lock.json
views/package.json

Downgrade tao-core-sdk to revert https://github.com/oat-sa/tao-core-sdk-fe/pull/137

[Hotfix][48.75.7] Revert token store

---

helpers/form/ElementMapFactory.php

Release 50.10.6

---

manifest.php

Release 50.10.8

---

manifest.php

Backport of [AUT-2137](https://oat-sa.atlassian.net/browse/AUT-2137) to update may release branch.

fix: release version corrected for May

---

manifest.php

Fix: TAO_VERSION and TAO_VERSION_NAME constants. Added LTS description.

Fix: TAO_VERSION and TAO_VERSION_NAME constants. Added LTS description.

---

manifest.php

Release 50.10.10

---

manifest.php

updated tao release version to the next candidate (2022.06)

chore: updated tao release version

---

manifest.php

Release 50.10.12 from 50.10.11

Release 50.10.12

---

actions/class.RdfController.php
models/classes/resources/Contract/ClassCopierInterface.php
models/classes/resources/Contract/ClassMetadataCopierInterface.php
models/classes/resources/Contract/InstanceContentCopierInterface.php
models/classes/resources/Contract/InstanceCopierInterface.php
models/classes/resources/Contract/InstanceMetadataCopierInterface.php
models/classes/resources/ResourcesServiceProvider.php
models/classes/resources/Service/ClassCopier.php
models/classes/resources/Service/ClassCopierProxy.php
models/classes/resources/Service/ClassMetadataCopier.php
models/classes/resources/Service/InstanceCopier.php
models/classes/resources/Service/InstanceMetadataCopier.php
models/classes/task/CopyClassTask.php

Release 50.11.0

---

models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php

**Associated Jia issue:** [ADF-1054](https://oat-sa.atlassian.net/browse/ADF-1054).

fix: Fix table alias used on count() query

---

models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepository.php
models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php

Release 50.11.1

---

README.md
actions/class.ClientConfig.php
models/classes/featureFlag/FeatureFlagConfigHandlerInterface.php
models/classes/featureFlag/FeatureFlagConfigSwitcher.php
models/classes/featureFlag/FeatureFlagListService.php
models/classes/featureFlag/FeatureFlagServiceProvider.php
models/classes/featureFlag/README.md
models/classes/featureFlag/Repository/FeatureFlagRepository.php
models/classes/featureFlag/Repository/FeatureFlagRepositoryInterface.php
models/classes/featureVisibility/FeatureVisibilityService.php
models/classes/featureVisibility/FeatureVisibilityServiceProvider.php
scripts/taoUpdate.php
scripts/tools/FeatureFlag/FeatureFlagTool.php
test/unit/AdvancedSearch/FeatureFlagListServiceTest.php
test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
test/unit/models/classes/featureFlag/FeatureFlagCheckerTest.php
test/unit/models/classes/featureFlag/FeatureFlagConfigSwitcherTest.php
test/unit/models/classes/featureFlag/Repository/FeatureFlagRepositoryTest.php
test/unit/models/classes/featureVisibility/FeatureVisibilityServiceTest.php

Release 50.13.0

---

composer.json
manifest.php
migrations/Version202205121753172234_tao.php
models/classes/resources/Contract/ClassMetadataMapperInterface.php
models/classes/resources/CopierServiceProvider.php
models/classes/resources/Service/ClassCopier.php
models/classes/resources/Service/ClassCopierProxy.php
models/classes/resources/Service/ClassMetadataCopier.php
models/classes/resources/Service/ClassMetadataMapper.php
models/classes/resources/Service/InstanceMetadataCopier.php
models/classes/resources/Service/RootClassesListService.php
models/classes/taskQueue/TaskLog.php
models/classes/taskQueue/TaskLogInterface.php
scripts/install/SetUpQueueTasks.php
test/unit/models/classes/resources/Service/ClassCopierProxyTest.php
test/unit/models/classes/resources/Service/ClassCopierTest.php
test/unit/models/classes/resources/Service/ClassMetadataCopierTest.php
test/unit/models/classes/resources/Service/ClassMetadataMapperTest.php
test/unit/models/classes/resources/Service/InstanceCopierTest.php
test/unit/models/classes/resources/Service/InstanceMetadataCopierTest.php

Release 50.14.0

---

models/classes/featureFlag/README.md
models/classes/featureFlag/Repository/FeatureFlagRepository.php
test/unit/models/classes/featureFlag/Repository/FeatureFlagRepositoryTest.php

Release 50.14.1

---

models/classes/resources/Contract/PermissionCopierInterface.php
models/classes/resources/Service/ClassCopier.php
models/classes/resources/Service/InstanceCopier.php

* https://github.com/oat-sa/extension-tao-dac-simple/pull/188
* Added `PermissionCopierInterface`.
* Added possibility to copy class with permission copier.
* Added possibility to copy instance with permission copier.

[Feature] Copy class/instance permissions

---

models/classes/resources/Contract/PermissionCopierInterface.php
models/classes/resources/Service/ClassCopier.php
models/classes/resources/Service/InstanceCopier.php

Release 50.15.0

---

composer.json

Release 50.16.1

---

composer.json

Release 50.16.2

---

models/classes/notifiers/GrafanaNotifier.php

Release 50.17.0

---

composer.json
install/class.Installator.php
scripts/taoUpdate.php

Release 50.18.1

---

composer.json
install/class.Installator.php
scripts/taoUpdate.php

Backport of https://github.com/oat-sa/tao-core/pull/3561

Backport/rel 783/create cachepath on update

---

views/build/package-lock.json
views/build/package.json

Fix branch pushed in https://github.com/oat-sa/tao-core/pull/3569

chore: use fixed version instead of the branch

---

actions/class.Languages.php
locales/ar-arb/lang.rdf
migrations/Version202207041535182168_tao.php
models/classes/Language/Business/Contract/LanguageRepositoryInterface.php
models/classes/Language/Language.php
models/classes/Language/LanguageCollection.php
models/classes/Language/Repository/LanguageRepository.php
models/classes/LanguageServiceProvider.php
test/unit/models/classes/Language/LanguageCollectionTest.php
test/unit/models/classes/Language/LanguageTest.php
test/unit/models/classes/Language/Repository/LanguageRepositoryTest.php

Release 50.19.0

---

manifest.php

Release 50.21.2

---

views/package-lock.json
views/package.json

Related to https://oat-sa.atlassian.net/browse/AUT-2273
Release of https://github.com/oat-sa/tao-core-ui-fe/pull/486

fix/AUT-2273: Fix glitching volume slider

---

models/classes/resources/Service/ClassCopier.php
models/classes/resources/Service/InstanceCopier.php

**Associated Jira issue:** [ADF-1148](https://oat-sa.atlassian.net/browse/ADF-1148)
**Related PRs:**
- https://github.com/oat-sa/extension-tao-dac-simple/pull/195
- https://github.com/oat-sa/extension-tao-item/pull/590
- https://github.com/oat-sa/extension-tao-mediamanager/pull/414

fix: Register copiers in the DI container using tags

---

models/classes/resources/Service/ClassCopier.php
models/classes/resources/Service/InstanceCopier.php

Release 50.22.1

---

manifest.php

fix: change release status to stable

---

.github/workflows/continuous-integration.yaml
models/classes/AdvancedSearch/AdvancedSearchChecker.php
models/classes/search/SearchProxy.php
models/classes/search/tasks/UpdateDataAccessControlInIndex.php
scripts/update/Updater.php
test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
test/unit/models/classes/search/tasks/UpdateDataAccessControlInIndexTest.php

Release 50.24.0

---

actions/class.Search.php
manifest.php
models/classes/search/Contract/SearchSettingsServiceInterface.php
models/classes/search/ResultColumn.php
models/classes/search/ResultSetFilter.php
models/classes/search/ResultSetMapper.php
models/classes/search/SearchProxy.php
models/classes/search/SearchSettings.php
models/classes/search/Service/DefaultSearchSettingsService.php
models/classes/search/ServiceProvider/SearchServiceProvider.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php
test/unit/models/classes/search/ResultColumnTest.php
test/unit/models/classes/search/SearchSettingsTest.php
test/unit/models/classes/search/Service/DefaultSearchSettingsServiceTest.php

https://oat-sa.atlassian.net/browse/ADF-1192

feat: provide selectable columns as search settings

---

manifest.php

Release 50.24.2

---

.github/workflows/continuous-integration.yaml
models/classes/auth/AbstractCredentials.php
test/unit/models/classes/Lists/DataAccess/Repository/RdfValueCollectionRepositoryTest.php

Release 50.24.3

---

.github/workflows/continuous-integration.yaml
composer.json
models/classes/Lists/Business/Event/ListSavedEvent.php
models/classes/Lists/Business/Service/ValueCollectionService.php
models/classes/search/tasks/UpdateResourceInIndex.php
test/unit/models/classes/Lists/Business/Event/ListSavedEventTest.php
test/unit/models/classes/Lists/Business/Service/ValueCollectionServiceTest.php

https://oat-sa.atlassian.net/browse/ADF-1198
- When a remote list os local list gets updated we need to reindex all the resources that are using properties from this list

feat: add new event for lists and trigger it on save

---

helpers/form/validators/class.Numeric.php

Release 50.24.4

---

composer.json

chore: fix generis version

---

models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php

https://oat-sa.atlassian.net/browse/ADF-1213
This typo was disabling save list values

Fix/adf 1213/fix checkbox display

---

actions/class.Search.php
models/classes/Lists/Business/Domain/ClassMetadataSearchRequest.php
models/classes/Lists/Business/Service/ClassMetadataService.php
models/classes/Lists/Business/Service/GetClassMetadataValuesService.php
models/classes/Lists/Presentation/Web/RequestHandler/ClassMetadataSearchRequestHandler.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php
test/unit/models/classes/Lists/Presentation/Web/RequestHandler/ClassMetadataSearchRequestHandlerTest.php

Add support for calendar
https://oat-sa.atlassian.net/browse/ADF-1191

feat: add calendar support

---

composer.json

Release 50.24.8

---

views/package-lock.json
views/package.json

Backport Related to:
https://oat-sa.atlassian.net/browse/AUT-2654
https://oat-sa.atlassian.net/browse/AUT-2639
https://oat-sa.atlassian.net/browse/AUT-2637
https://oat-sa.atlassian.net/browse/AUT-2653
Bump of` tao-core-ui-fe` version

fix: bump tao-core-ui-fe to fix icon issues

---

manifest.php

Release 50.25.1

---

helpers/form/validators/class.Integer.php
test/integration/ValidatorTest.php
test/unit/helpers/form/validators/IntegerValidatorTest.php

Release 50.26.1

---

composer.json
helpers/form/validators/class.Integer.php
test/integration/ValidatorTest.php
test/unit/helpers/form/validators/IntegerValidatorTest.php

- _Fix_ [ADF-1145](https://oat-sa.atlassian.net/browse/ADF-1145) : [] integer form validator on PHP8 [#3599](https://github.com/oat-sa/tao-core/pull/3599)

Backport ADF-1145 to December RC branch

---

helpers/form/class.Form.php
helpers/form/xhtml/class.Form.php
test/unit/helpers/form/FormContainerTest.php

Release 50.27.1

---

models/classes/resources/ResourceWatcher.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilderInterface.php
models/classes/search/tasks/UpdateResourceInIndex.php
test/unit/models/classes/search/index/IndexDocumentBuilderTest.php
test/unit/models/classes/search/tasks/UpdateResourceInIndexTest.php

**Associated Jira issue:** [PISA25-188](https://oat-sa.atlassian.net/browse/PISA25-188)
Related PRs:
- https://github.com/oat-sa/extension-tao-advanced-search/pull/86

feat: Use AdvancedSearch DocumentBuilder from UpdateResourceInIndex if available

---

models/classes/resources/ResourceWatcher.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilder.php
models/classes/search/index/DocumentBuilder/IndexDocumentBuilderInterface.php
models/classes/search/tasks/UpdateResourceInIndex.php
test/unit/models/classes/search/index/IndexDocumentBuilderTest.php
test/unit/models/classes/search/tasks/UpdateResourceInIndexTest.php

Release 50.29.0

---

models/classes/taskQueue/TaskLog/Broker/TaskLogBrokerInterface.php

fix: remove leading backslash

---

models/classes/taskQueue/TaskLog.php
models/classes/taskQueue/TaskLog/Broker/RdsTaskLogBroker.php
models/classes/taskQueue/TaskLog/Broker/TaskLogBrokerInterface.php
models/classes/taskQueue/TaskLogInterface.php
test/unit/models/classes/taskQueue/TaskLog/Broker/RdsTaskLogBrokerTest.php

Release 50.30.0

---

manifest.php

fix: bump tao version

---

manifest.php

Release 50.30.1

---

test/unit/helpers/form/Decorator/ElementDecoratorTest.php

Release 50.30.3

---

models/classes/resources/ListResourceLookup.php

Related to ticket https://oat-sa.atlassian.net/browse/LSI-1550 
Description: Fix Search test by label in left sidebar for TAO Enterprise INVALSI PHP 8.1 
Find the details of this error [here](https://oat-sa.atlassian.net/browse/LSI-1550?focusedCommentId=210578)

fix: Search test by label in left sidebar for TAO Enterprise INVALSI PHP 8.1

---

models/classes/resources/ListResourceLookup.php

Release 50.30.4

---

models/classes/session/Business/Contract/SessionCookieAttributeInterface.php
models/classes/session/Business/Domain/SessionCookieAttribute.php
models/classes/session/Business/Domain/SessionCookiePathAttribute.php
models/classes/session/Business/Service/SessionCookieService.php
test/unit/session/Business/Service/SessionCookieServiceTest.php

Release 51.0.0

---

manifest.php
models/classes/session/Business/Contract/SessionCookieAttributeInterface.php
models/classes/session/Business/Domain/SessionCookieAttribute.php
models/classes/session/Business/Domain/SessionCookiePathAttribute.php
models/classes/session/Business/Service/SessionCookieService.php
test/unit/session/Business/Service/SessionCookieServiceTest.php

backport of https://github.com/oat-sa/tao-core/pull/3712
for  [TR-4934](https://oat-sa.atlassian.net/browse/TR-4934)

Backport of utilising modern `setcookie` signature

---

manifest.php

chore: change version to 2023.02

chore: change version to 2023.02

---

manifest.php

Release 51.0.1

---

views/package-lock.json
views/package.json

Release 51.0.2

---

actions/class.RestTrait.php

Release 51.0.3

---

models/classes/search/ResultSetResponseNormalizer.php
models/classes/search/SearchProxy.php
test/unit/models/classes/search/ResultSetResponseNormalizerTest.php
test/unit/models/classes/search/SearchProxyTest.php

coming from task [ADF-1048](https://oat-sa.atlassian.net/browse/ADF-1048)
changelog:
* fix to allow non data administrators to access search features
* tests
[ADF-1048]: https://oat-sa.atlassian.net/browse/ADF-1048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature/adf 1048/acl search roles users fix

---

models/classes/search/ResultSetResponseNormalizer.php
models/classes/search/SearchProxy.php
test/unit/models/classes/search/ResultSetResponseNormalizerTest.php
test/unit/models/classes/search/SearchProxyTest.php

Release 51.1.0

---

install/class.Setup.php
install/utils/ConfigurationMarkers.php
models/classes/EnvPhpSerializable.php
models/classes/EnvPhpSerializableFactory.php
test/unit/install/utils/ConfigurationMarkersTest.php
test/unit/models/classes/EnvPhpSerializableFactoryTest.php
test/unit/models/classes/EnvPhpSerializableTest.php

Release 51.3.0

---

models/classes/resources/ListResourceLookup.php
views/js/provider/resources.js

Related to ticket https://oat-sa.atlassian.net/browse/LSI-1581
Description: Fix 500 error when actions Delete/Copy to/Duplicate etc on search by label result in the left sidebar for TAO Enterprise INVALSI PHP 8.1
Find the details of this error [here](https://oat-sa.atlassian.net/browse/LSI-1581)
This issue can be reproduced in the following environment
http://test-invalsi_php_8_1.playground.kitchen.it.taocloud.org:49721/
admin/admin

fix: add signature to search results in left sidebar (Search by label) for TAO Enterprise INVALSI PHP 8.1

---

manifest.php

chore: manifest for march release

---

manifest.php

Release 51.3.4

---

models/classes/http/ResponseEmitter.php

Release 51.4.0

---

manifest.php
models/classes/export/CustomizedGenerisAdapterRdf.php
models/classes/export/ServiceProvider/ExportServiceProvider.php
models/classes/import/CustomizedRdfImporter.php
models/classes/import/ServiceProvider/ImportServiceProvider.php
scripts/tools/export/RDF/ExportRdfStructure.php
scripts/tools/import/RDF/ImportMirrorRdfStructure.php

Release 51.5.0

---

manifest.php

chore: change version to 2023.04

---

manifest.php

Release 51.6.1

---

manifest.php

Release 51.11.1

---

manifest.php
models/classes/webhooks/WebHookClassService.php
models/classes/webhooks/WebhookAuthService.php
models/classes/webhooks/WebhookEventsService.php
models/classes/webhooks/WebhookFileRegistry.php
models/classes/webhooks/WebhookRdfRegistry.php
models/classes/webhooks/WebhookRegistryFactory.php
models/classes/webhooks/WebhookRegistryInterface.php
models/classes/webhooks/WebhookRegistryManager.php
models/classes/webhooks/WebhookServiceProvider.php
models/classes/webhooks/task/WebhookTask.php
test/unit/webhooks/WebHookClassServiceTest.php
test/unit/webhooks/WebhookEventsServiceTest.php
test/unit/webhooks/WebhookRegistryManagerTest.php
test/unit/webhooks/task/WebhookTaskTest.php

Switch to DI where it's possible

refactor: implement DI

---

helpers/form/validators/class.Numeric.php

Release 52.1.1

---

actions/class.ClientConfig.php

* Added default value for `action` parameter
* Added default value for `module` parameter
1. Install `taoTestPreviewUILoader` extension
2. Create a test
3. Try to preview it
Test preview is not opened. Errors appear in console
Test is opened in preview mode
[TR-5419]: https://oat-sa.atlassian.net/browse/TR-5419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] Add default values for action and module names

---

actions/class.ClientConfig.php

Release 52.1.2

---

manifest.php

AUT-3099 Release 2023-06 version bump

chore: tao version 2023.06

---

models/classes/resources/Service/ClassMover.php
test/unit/models/classes/resources/Service/ClassMoverTest.php

Release 52.2.1

---

models/classes/auth/BasicAuthType.php

fix: fix empty credentials

---

models/classes/auth/BasicAuthType.php

Release 53.1.1

---

install/class.Setup.php

Add  array check for if block for configs with markers

fix: add array check for if block

---

install/class.Setup.php

Release 53.1.2

---

views/package-lock.json
views/package.json

related to https://oat-sa.atlassian.net/browse/PISA25-364
This PR is on the scope of backporting to Premium release `06-2023`

chore: dependency versions

---

actions/class.Main.php
crowdin.yml

Release 53.2.3

---

composer.json
migrations/Version202306211310042234_tao.php
models/classes/Language/Listener/LanguageCacheWarmupListener.php
models/classes/LanguageServiceProvider.php
models/classes/featureFlag/FeatureFlagServiceProvider.php
models/classes/featureFlag/Listener/FeatureFlagCacheWarmupListener.php
models/classes/menu/Listener/MenuCacheWarmupListener.php
models/classes/menu/MenuServiceProvider.php
models/classes/routing/Listener/AnnotationCacheWarmupListener.php
models/classes/routing/ServiceProvider/RoutingServiceProvider.php
scripts/install/RegisterEvents.php
test/unit/models/classes/Language/Listener/LanguageCacheWarmupListenerTest.php
test/unit/models/classes/featureFlag/Listener/FeatureFlagCacheWarmupListenerTest.php

Release 53.3.0

---

actions/class.Main.php
views/templates/blocks/header-main-navi.tpl

This will show multiple entries in the flyout menu including my setting and logout

fix: base on ff show mutliple entries in flyout menu

---

manifest.php

Release 53.3.1

---

migrations/Version202307101518342234_tao.php
models/classes/TaoOntology.php
models/ontology/tao.rdf
scripts/tools/MigrateSqlToNeo4j.php
scripts/tools/export/RDF/ExportRdfStructure.php

Release 53.4.0

---

models/classes/resources/CopierServiceProvider.php

Release 53.4.1

---

manifest.php

Release 53.4.2

---

helpers/translation/class.POFileReader.php
migrations/Version202312191318372234_tao.php

…tead of targetLanguage attribute (#3943)
* fix: Get Country Code Language List from the file name instead of targetLanguage attribute
Refs: https://oat-sa.atlassian.net/browse/AUT-3418
* fix: php Code Style
* fix: php code styles
* fix: added migration script
* fix: added php empty line

[Backport][AUT-3418] Get Country Code Language List

---

actions/class.File.php

Backport of https://github.com/oat-sa/tao-core/pull/3950

Backport/rel 1418/cache warmup unblock

---

manifest.php

New tao-community version definition

fix: add 2024.03 release version

---

actions/class.TaskQueueWebApi.php
models/classes/export/ServiceProvider/ExportServiceProvider.php
models/classes/taskQueue/TaskLog/Decorator/DynamicEntityDecorator.php
models/classes/taskQueue/TaskLog/Decorator/TaskLogEntityDecorateProcessor.php
test/unit/model/taskQueue/TaskLog/Decorator/Stub/StubEntityDecorator.php
test/unit/model/taskQueue/TaskLog/Decorator/TaskLogDecoratorProcessorTest.php
views/package-lock.json
views/package.json

Ticket - https://oat-sa.atlassian.net/browse/REL-1428
Implement Authoring UI for Paper Booklet Export Functionality
- feat: Implement Authoring UI for Paper Booklet Export Functionality
Select test and click export. Select export to docx

feat: Implement Authoring UI for Paper Booklet Export Functionality

---

manifest.php

feature: tao version 2024.04

---

models/classes/security/Business/Domain/Key/Key.php
test/unit/models/classes/security/Business/Domain/Key/KeyChainCollectionTest.php
test/unit/models/classes/security/Business/Domain/Key/KeyTest.php

* feat: publish to two solar tenants
---------

feat: publish to two solar tenants

---

models/classes/security/Business/Domain/Key/Key.php
test/unit/models/classes/security/Business/Domain/Key/KeyChainCollectionTest.php
test/unit/models/classes/security/Business/Domain/Key/KeyTest.php

Version 54.2.2
**Release notes:**
- [feat] [REL-1466](https://oat-sa.atlassian.net/browse/REL-1466) Publish to two solar tenants [#3972](https://github.com/oat-sa/tao-core/pull/3972), [#3975](https://github.com/oat-sa/tao-core/pull/3975)
[REL-1466]: https://oat-sa.atlassian.net/browse/REL-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix/rel 1466/publish launch multiple tenants

---

helpers/Layout.php
test/unit/helpers/LayoutTest.php
views/templates/layout.tpl

Backport for TR-6036

---

manifest.php

Update manifest version with 2024.05 lts

Fix/aut 3601/fix manifest version

---

manifest.php

chore: bump tao-version

---

actions/class.UserSettings.php
actions/form/class.UserSettings.php
composer.json
migrations/Version202406121231482235_tao.php
models/classes/action/ActionBlackList.php
models/classes/menu/SectionVisibilityFilter.php
models/classes/password/PasswordConstraintsServiceProvider.php
models/classes/user/UserSettingsFormFactory.php
models/classes/user/UserSettingsInterface.php
models/classes/user/UserSettingsServiceProvider.php
models/classes/user/implementation/UserSettings.php
models/classes/user/implementation/UserSettingsService.php
test/unit/models/classes/menu/SectionVisibilityFilterTest.php
test/unit/user/implementation/UserSettingsServiceTest.php

https://oat-sa.atlassian.net/browse/AUT-3625
- Add interface mode in forms
- Implement new way of accessing/updating user settings via set/get
- Add interface mode in user settings
- Update tests

Feat/aut 3625/content creation mode switch

---

models/classes/theme/ThemeService.php
models/classes/theme/ThemeServiceAbstract.php

Remove FEATURE_FLAG_TAO_AS_A_TOOL fro tao-core

fix: remove FEATURE_FLAG_TAO_AS_A_TOOL

---

models/classes/theme/ThemeService.php
models/classes/theme/ThemeServiceAbstract.php

Backport for removing FEATURE_FLAG_TAO_AS_A_TOOL

Backport/solar 777/remove ff

---

actions/form/class.Instance.php

https://oat-sa.atlassian.net/browse/ADF-1728
Fix regression introduced [here](https://github.com/oat-sa/tao-core/pull/3929/files#diff-d663f726bfddec08e0b9a1cc9181ba9ecc8416358b2a1b2f0ad2f2721e063977R100) from https://oat-sa.atlassian.net/browse/REL-1323
Form can actually receive null instances when new instances are created. This was breaking booklets creation
```
2024-07-01 15:18:06 [ERROR] [tao] 'php error(1) in /var/www/html/tao/tao/actions/form/class.Instance.php@100: Uncaught Error: Call to a member function getUri() on null in /var/www/html/tao/tao/actions/form/class.Instance.php:100
Stack trace:
#0 /var/www/html/tao/taoBooklet/form/GenerateForm.php(36): tao_actions_form_Instance->initElements()
#1 /var/www/html/tao/taoBooklet/form/WizardBookletForm.php(50): …
```

fix: allow null instance for forms

---

actions/form/class.Instance.php

Backport https://github.com/oat-sa/tao-core/pull/4062
https://oat-sa.atlassian.net/browse/ADF-1728

Fix/adf 1728/backporting 2

---

manifest.php

fix: bump tao version with 2024-08

---

actions/class.RdfController.php

Error was because class does not have any types as other resources. We had to take different strategy to get parent class

MoveTo Action for class fixed

---

actions/form/class.Instance.php

Backport https://github.com/oat-sa/tao-core/pull/4062
https://oat-sa.atlassian.net/browse/ADF-1728 / https://oat-sa.atlassian.net/browse/LSI-4487

Backport/adf 1728/booklet form not working

---

manifest.php

Update release version with 2024-10

fix: update release version

---

actions/class.Translation.php
models/classes/Translation/Command/CreateTranslationCommand.php
models/classes/Translation/Service/TranslationCreationService.php
models/classes/Translation/ServiceProvider/TranslationServiceProvider.php
test/unit/models/classes/Translation/Command/CreateTranslationCommandTest.php
test/unit/models/classes/Translation/Service/TranslationCreationServiceTest.php

https://oat-sa.atlassian.net/browse/ADF-1783
https://oat-sa.atlassian.net/browse/HKD-6
- Allow to translate resources
* https://github.com/oat-sa/extension-tao-item/pull/660
* https://github.com/oat-sa/extension-tao-test/pull/476
* https://github.com/oat-sa/extension-tao-itemqti/pull/2571
* https://github.com/oat-sa/extension-tao-testqti/pull/2503

feat: add possibility to translate resources agnostically

---

actions/class.Translation.php
manifest.php
models/classes/TaoOntology.php
models/classes/Translation/Form/Modifier/TranslationFormModifier.php
models/classes/Translation/Query/ResourceTranslationQuery.php
models/classes/Translation/Repository/ResourceTranslatableRepository.php
models/classes/Translation/Repository/ResourceTranslationRepository.php
models/classes/Translation/Service/ResourceTranslationRetriever.php
models/classes/Translation/Service/TranslationCreationService.php
models/classes/Translation/Service/TranslationSyncService.php
models/classes/Translation/ServiceProvider/TranslationServiceProvider.php
models/classes/form/Modifier/UniqueIdFormModifier.php
models/classes/form/ServiceProvider/FormServiceProvider.php
models/ontology/tao.rdf
test/unit/models/classes/Translation/Form/Modifier/TranslationFormModifierTest.php
test/unit/models/classes/Translation/Query/ResourceTranslationQueryTest.php
test/unit/models/classes/Translation/Repository/ResourceTranslatableRepositoryTest.php
test/unit/models/classes/Translation/Repository/ResourceTranslationRepositoryTest.php
test/unit/models/classes/Translation/Service/ResourceMetadataPopulateServiceTest.php
test/unit/models/classes/Translation/Service/ResourceTranslatableRetrieverTest.php
test/unit/models/classes/Translation/Service/ResourceTranslationRetrieverTest.php

Create API to translate/sync the test
* https://github.com/oat-sa/extension-tao-testqti/pull/2506
[ADF-1787]: https://oat-sa.atlassian.net/browse/ADF-1787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: create translatable test

---

models/classes/resources/ResourceWatcher.php

This fixes https://github.com/oat-sa/tao-core/pull/3989
it was unable to detect if resource is a test if it's placed in a nested class

fix: properly determine resource indexable type to route index tasks

---

actions/class.Translation.php
doc/taoApi.yml
models/classes/Translation/Service/TranslationDeletionService.php
models/classes/Translation/ServiceProvider/TranslationServiceProvider.php
test/unit/models/classes/Translation/Service/TranslationDeletionServiceTest.php

- Allow delete translation based on master id and locale

feat: add possibility to delete translations

---

manifest.php

Bump release version to 2024.11 LTS

fix: bump version

---

manifest.php
models/classes/GenerisServiceTrait.php
models/classes/IdentifierGenerator/Generator/IdentifierGeneratorInterface.php
models/classes/IdentifierGenerator/Generator/IdentifierGeneratorProxy.php
models/classes/IdentifierGenerator/Generator/NumericIdentifierGenerator.php
models/classes/IdentifierGenerator/ServiceProvider/IdentifierGeneratorServiceProvider.php
models/classes/Translation/Form/Modifier/TranslationFormModifier.php
models/classes/Translation/Service/TranslationCreationService.php
models/classes/resources/Event/InstanceCopiedEvent.php
models/classes/resources/Service/InstanceCopier.php
test/unit/models/classes/Translation/Service/TranslationCreationServiceTest.php

[ADF-1802]: https://oat-sa.atlassian.net/browse/ADF-1802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: better handling for unique IDs

---

manifest.php

fix: bump version with 2024-12

---

manifest.php

Ticket: https://oat-sa.atlassian.net/browse/AUT-4007
- Change version to 2025.01

feature: change version

---

models/classes/resources/Service/ClassDeleter.php
test/unit/models/classes/resources/Service/ClassDeleterTest.php

https://oat-sa.atlassian.net/browse/ADF-1825
- Add existing check before deleting instances

fix: Add existing instance check

---

views/scss/inc/_action-bars.scss

Ticket: https://oat-sa.atlassian.net/browse/AUT-4069
- Updated the actions colours

fix: proper use of gray

---

views/scss/inc/_action-bars.scss
views/scss/inc/_header-footer.scss

[AUT-4067](https://oat-sa.atlassian.net/browse/AUT-4067)
Moving from Red primary color to Blue
[AUT-4067]: https://oat-sa.atlassian.net/browse/AUT-4067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AUT-4067] fix: changing primary color to Blue

---

views/js/layout/nav.js
views/scss/inc/_action-bars.scss
views/scss/inc/_header-footer.scss
views/templates/blocks/header.tpl
views/templates/blocks/sections.tpl

Tickets: [AUT-4064](https://oat-sa.atlassian.net/browse/AUT-4064) [AUT-4068](https://oat-sa.atlassian.net/browse/AUT-4068) 
Fixed actions position, and mobile behavior
[AUT-4064]: https://oat-sa.atlassian.net/browse/AUT-4064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AUT-4068]: https://oat-sa.atlassian.net/browse/AUT-4068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AUT-4064] fix: fixes for search, actions and mobile menu

---

views/scss/inc/_action-bars.scss
views/scss/inc/_header-footer.scss

[AUT-4067] fix: CR for colors on actions hover and header color change, also few minor alignment fix

---

views/package-lock.json
views/package.json

fix: update @oat-sa/tao-core-ui version

Backport INF-291

---

views/package-lock.json
views/package.json

Ticket: https://oat-sa.atlassian.net/browse/AUT-4082
- update @oat-sa/tao-core-ui https://github.com/oat-sa/tao-core-ui-fe/pull/633

feature: update @oat-sa/tao-core-ui

---

locales/ku-IQ/lang.rdf
locales/ug-CN/lang.rdf
models/classes/Translation/Service/TranslationUniqueIdSetter.php
models/classes/class.LanguageService.php
test/unit/models/classes/Translation/Service/TranslationUniqueIdSetterTest.php

https://oat-sa.atlassian.net/browse/ADF-1906
https://oat-sa.atlassian.net/browse/ADF-1899
Make sure that lang oriental can fallback to RDF structure
- https://github.com/oat-sa/extension-tao-itemqti/pull/2698

chore: add missing RTL locales

---

views/package-lock.json
views/package.json

Ticket: https://oat-sa.atlassian.net/browse/INF-283
- update oat-sa/tao-core-shared-libs to 1.7.1

feature: update oat-sa/tao-core-shared-libs to 1.7.1

---

views/js/layout/actions.js

https://oat-sa.atlassian.net/browse/AUT-4121
Fix for incorrect highlighting action buttons after item or test preview.
- Select the item/test from preconditions
- Click 'Preview' button
- Close the preview
- Observe the 'Preview' tab

[AUT-4121] Fix: disabling item and test preview highlighting

---

models/classes/resources/ResourceWatcher.php

Prevent calling catchUpdatedResourceEvent multiple times

fix: prevent multi update events

---

.github/workflows/continuous-integration.yaml
views/package-lock.json
views/package.json

Ticket: https://oat-sa.atlassian.net/browse/AUT-4082
- Add -period ".", and -parenthesis ")") suffixes to list-style in choice interaction
- Add changes to `@oat-sa/tao` by running `npm install --save github:oat-sa/tao-core-ui-fe#feature/AUT-4082-new-classes-to-list-style` in you `/nextgen-stack/tao/tao/views ` folder
- run` npm run sass` in `/nextgen-stack/tao/tao/view/build` folder
- go to Backoffice run item authoring and check new list in choice interaction
##Video
https://github.com/user-attachments/assets/c7b7cf1f-6d8c-4705-b561-408536573371

Feat/aut 4082/add additional list styles

---

.github/workflows/continuous-integration.yaml
views/templates/form/import.tpl

https://oat-sa.atlassian.net/browse/AUT-2120
- Reset form after import with task queue
> Please tick the appropriate points
- Navigate to the "Assets"/ "Items"/"Test" page
- Click "Import" button on the left panel
- Click  "Browse" and select a file
- Click "Import" button on the "Import" form
- Click  "Browse" and select a new file
- Click "Import" button on the "Import" form one more time
https://github.com/user-attachments/assets/95b4c567-1a7d-43b6-ab44-350a9a7216c8

fix: reset form after import with task queue

---

manifest.php

- Update Manifest version with 2025-06 release

chore: update version with 2025-06

---

models/classes/resources/ResourceWatcher.php

https://github.com/oat-sa/tao-core/pull/4249
https://github.com/oat-sa/tao-core/releases/tag/v54.38.1

backport: remove condition for event aggregation

---

views/package-lock.json
views/package.json

https://oat-sa.atlassian.net/browse/AUT-4273
- Update default list of CKEditor plugins
> Please tick the appropriate points

fix: update ckeditor plugins

---

manifest.php

fix: set 2025-09 version
